from __future__ import annotations

"""Runtime Native Contract Test Generation Stage 7.

Generates pytest skeletons from Stage 6 native runtime contract specs.
This script is intentionally non-invasive: it does not modify runtime code.
"""

import json
import pprint
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path.cwd()
BASE = ROOT / "docs" / "architecture" / "runtime_compatibility_inventory"
SPECS_PATH = BASE / "runtime_native_contract_test_specs_stage6.json"
SUMMARY_PATH = BASE / "runtime_native_contract_test_specs_stage6_summary.json"
OUT_DIR = ROOT / "tests" / "runtime_contracts"
REPORT_PATH = BASE / "runtime_native_contract_test_generation_stage7_report.md"
GEN_SUMMARY_PATH = BASE / "runtime_native_contract_test_generation_stage7_summary.json"

DOMAIN_FILES = {
    "runtime_authority": "test_runtime_authority_contracts.py",
    "step_executor": "test_step_executor_contracts.py",
    "task_runner": "test_task_runner_contracts.py",
}

DOMAIN_TITLES = {
    "runtime_authority": "Runtime Authority native contract specs",
    "step_executor": "StepExecutor native contract specs",
    "task_runner": "TaskRunner native contract specs",
}


def _load_json(path: Path) -> Any:
    if not path.exists():
        raise FileNotFoundError(f"missing required input: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def _items_from_specs(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        return [dict(x) for x in payload if isinstance(x, dict)]
    if isinstance(payload, dict):
        for key in ("specs", "items", "contracts", "native_contracts", "extracted"):
            value = payload.get(key)
            if isinstance(value, list):
                return [dict(x) for x in value if isinstance(x, dict)]
    raise ValueError("Stage 6 specs JSON must contain a list or a dict with specs/items/contracts/native_contracts/extracted")


def _safe_ident(value: Any, fallback: str) -> str:
    text = str(value or fallback).strip().lower()
    out = []
    for ch in text:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    ident = "".join(out).strip("_") or fallback
    while "__" in ident:
        ident = ident.replace("__", "_")
    if ident[0].isdigit():
        ident = "contract_" + ident
    return ident[:90]


def _domain(item: dict[str, Any]) -> str:
    raw = str(
        item.get("owner_domain")
        or item.get("native_owner_domain")
        or item.get("owner")
        or item.get("contract_owner")
        or item.get("domain")
        or item.get("contract_domain")
        or ""
    ).strip().lower()
    if "authority" in raw:
        return "runtime_authority"
    if "step" in raw and "executor" in raw:
        return "step_executor"
    if "task" in raw and "runner" in raw:
        return "task_runner"
    if raw in DOMAIN_FILES:
        return raw
    return "runtime_authority"


def _test_name(item: dict[str, Any], index: int) -> str:
    basis = (
        item.get("test_name")
        or item.get("assertion_hint")
        or item.get("contract_id")
        or item.get("id")
        or item.get("source_line")
        or item.get("path")
        or f"contract_{index:03d}"
    )
    return "test_" + _safe_ident(basis, f"contract_{index:03d}")


def _contract_id(item: dict[str, Any], index: int) -> str:
    return str(item.get("contract_id") or item.get("id") or f"native-contract-{index:03d}")


def _spec_payload(item: dict[str, Any], index: int) -> dict[str, Any]:
    return {
        "contract_id": _contract_id(item, index),
        "owner_domain": _domain(item),
        "assertion_hint": str(item.get("assertion_hint") or item.get("next_action") or "native contract assertion required"),
        "source_path": str(item.get("path") or item.get("source_path") or ""),
        "source_line": item.get("line") or item.get("source_line") or None,
        "next_action": str(item.get("next_action") or "extract_native_contract_test"),
        "lifecycle": str(item.get("contract_lifecycle") or item.get("lifecycle") or "native_contract_test_spec"),
    }


def _render_file(domain: str, rows: list[tuple[str, dict[str, Any]]]) -> str:
    title = DOMAIN_TITLES.get(domain, domain)
    lines = [
        "from __future__ import annotations",
        "",
        "# Generated by tools/runtime_native_contract_test_generation_stage7.py",
        "# These tests are native contract anchors. They intentionally assert the",
        "# extracted contract metadata first; Stage 8+ should replace metadata-only",
        "# assertions with direct runtime behavior assertions where appropriate.",
        "",
        f'TEST_SUITE = {title!r}',
        "",
        "",
    ]
    for test_name, spec in rows:
        spec_repr = pprint.pformat(spec, ensure_ascii=False, sort_keys=True, sort_dicts=False, width=120)
        spec_repr = "\n".join("    " + line for line in spec_repr.splitlines())
        lines.extend([
            f"def {test_name}() -> None:",
            f"    spec = {spec_repr}",
            "    assert spec[\"contract_id\"]",
            f"    assert spec[\"owner_domain\"] == {domain!r}",
            "    assert spec[\"assertion_hint\"]",
            "    assert spec[\"next_action\"]",
            "",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def _run(cmd: list[str]) -> tuple[bool, str]:
    proc = subprocess.run(cmd, cwd=str(ROOT), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return proc.returncode == 0, proc.stdout


def main() -> int:
    specs_payload = _load_json(SPECS_PATH)
    stage6_summary = _load_json(SUMMARY_PATH) if SUMMARY_PATH.exists() else {}
    items = _items_from_specs(specs_payload)
    if not items:
        raise RuntimeError("no Stage 6 native contract specs found")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    BASE.mkdir(parents=True, exist_ok=True)

    grouped: dict[str, list[tuple[str, dict[str, Any]]]] = defaultdict(list)
    seen_names: Counter[str] = Counter()
    generated_specs: list[dict[str, Any]] = []

    for index, item in enumerate(items, start=1):
        domain = _domain(item)
        spec = _spec_payload(item, index)
        name = _test_name(item, index)
        seen_names[(domain, name)] += 1
        if seen_names[(domain, name)] > 1:
            name = f"{name}_{seen_names[(domain, name)]}"
        grouped[domain].append((name, spec))
        generated_specs.append({"test_file": DOMAIN_FILES.get(domain, f"test_{domain}.py"), "test_name": name, **spec})

    written: dict[str, int] = {}
    for domain, filename in DOMAIN_FILES.items():
        rows = grouped.get(domain, [])
        if not rows:
            continue
        path = OUT_DIR / filename
        path.write_text(_render_file(domain, rows), encoding="utf-8")
        written[str(path)] = len(rows)

    verify_cmds = [
        [sys.executable, "-m", "pytest", "-q", str(OUT_DIR)],
        [sys.executable, "-m", "pytest", "-q", "tests/test_runtime_evidence_freeze.py"],
        [sys.executable, "-m", "pytest", "-q", "tests/test_runtime_execution_ownership_migration_contract.py"],
        [sys.executable, "-m", "pytest", "-q", "tests/test_runtime_mainline_freeze_contract.py"],
        [sys.executable, "-m", "pytest", "-q", "tests/test_runtime_mode_propagation.py"],
        [sys.executable, "-m", "pytest", "-q", "tests/test_runner_scheduler_boundary_survival.py"],
    ]
    verification = []
    verification_passed = True
    for cmd in verify_cmds:
        ok, output = _run(cmd)
        verification.append({"cmd": cmd, "ok": ok, "output": output})
        verification_passed = verification_passed and ok

    zero_patch_count = 0
    for path in (ROOT / "core").rglob("*.py"):
        try:
            if "ZERO_PATCH_" in path.read_text(encoding="utf-8", errors="ignore"):
                zero_patch_count += 1
        except Exception:
            pass

    summary = {
        "source_stage6_items": len(items),
        "generated_tests": sum(written.values()),
        "written_files": written,
        "owner_domain_counts": dict(Counter(spec["owner_domain"] for spec in generated_specs)),
        "stage6_summary_owner_domain_counts": stage6_summary.get("owner_domain_counts") or stage6_summary.get("domain_counts") or {},
        "zero_patch_residue_count": zero_patch_count,
        "verification_passed": verification_passed,
        "outputs": {
            "tests_dir": str(OUT_DIR),
            "summary": str(GEN_SUMMARY_PATH),
            "report": str(REPORT_PATH),
        },
    }
    GEN_SUMMARY_PATH.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    report_lines = [
        "# Runtime Native Contract Test Generation Stage 7",
        "",
        f"- source Stage 6 items: {len(items)}",
        f"- generated tests: {summary['generated_tests']}",
        f"- ZERO_PATCH residue files: {zero_patch_count}",
        f"- verification passed: {verification_passed}",
        "",
        "## Written files",
    ]
    for path, count in written.items():
        report_lines.append(f"- `{path}`: {count}")
    report_lines.extend(["", "## Verification"])
    for item in verification:
        report_lines.append(f"### {'PASS' if item['ok'] else 'FAIL'}: `{' '.join(item['cmd'])}`")
        report_lines.append("```text")
        report_lines.append(item["output"].strip())
        report_lines.append("```")
        report_lines.append("")
    REPORT_PATH.write_text("\n".join(report_lines).rstrip() + "\n", encoding="utf-8")

    print(f"native contract tests generated: {summary['generated_tests']}")
    print(f"owner domain counts: {summary['owner_domain_counts']}")
    print(f"ZERO_PATCH residue: {zero_patch_count}")
    print(f"tests_dir: {OUT_DIR}")
    print(f"report: {REPORT_PATH}")
    print(f"summary: {GEN_SUMMARY_PATH}")
    print("verification passed" if verification_passed else "verification failed")
    return 0 if verification_passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
