from __future__ import annotations

SESSION_RUNNING = "SESSION_RUNNING"
SESSION_BLOCKED = "SESSION_BLOCKED"
SESSION_SEALED = "SESSION_SEALED"
SESSION_FAILED = "SESSION_FAILED"
SESSION_ROLLED_BACK = "SESSION_ROLLED_BACK"
SESSION_RESTORED = "SESSION_RESTORED"

RUNTIME_FROZEN = "runtime_frozen"
SOVEREIGN_LOCKED = "sovereign_locked"
UNLOCK_APPROVED = "unlock_approved"
EXECUTION_RESTORED = "execution_restored"
EXECUTED = "executed"

CANONICAL_SESSION_STATES = {
    SESSION_RUNNING,
    SESSION_BLOCKED,
    SESSION_SEALED,
    SESSION_FAILED,
    SESSION_ROLLED_BACK,
    SESSION_RESTORED,
}

CANONICAL_RUNTIME_FLAGS = {
    RUNTIME_FROZEN,
    SOVEREIGN_LOCKED,
    UNLOCK_APPROVED,
    EXECUTION_RESTORED,
    EXECUTED,
}