from __future__ import annotations
from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash,_safe
from core.runtime.runtime_capability_decision_readiness_closure_validation import validate_capability_decision_readiness_closure
CONTRACT="zero.runtime.capability_bounded_decision_review_request.v1";SCHEMA_VERSION="1";STATUSES=frozenset({"accepted","not_accepted","blocked","invalid"})
PROPOSAL_OUTCOMES={"confirm_observation":"observation_confirmed","request_additional_observation":"additional_observation_required","accept_no_further_action":"no_further_action","prepare_execution_plan_review":"execution_plan_review_requested"};FORBIDDEN_PROPOSALS=frozenset({"execute","mutate","write","delete","deploy","install","run_process","network_request","invoke_model","approve_mutation","authorize_executor"});EFFECT_CLASSES=frozenset({"none","control_plane_only","future_execution_plan_review"});PERMISSION_FIELDS=frozenset({"filesystem_read","filesystem_write","filesystem_mutation","external_process","network","model_invocation"});PROPOSAL_FIELDS=frozenset({"proposal_id","proposal_type","target_reference","proposed_outcome","rationale_references","limitations_acknowledged"});REFERENCE_FIELDS=frozenset({"artifact_id","artifact_fingerprint"})
def _scope_contained(scope:Any,limit:Any)->bool:return isinstance(scope,Mapping) and bool(scope) and isinstance(limit,Mapping) and all(k in limit and limit[k]==v for k,v in scope.items())
def _proposal_shape(p:Any)->bool:
 return isinstance(p,Mapping) and set(p)==PROPOSAL_FIELDS and isinstance(p.get("proposal_id"),str) and bool(p.get("proposal_id")) and p.get("proposal_type") in PROPOSAL_OUTCOMES and p.get("proposed_outcome")==PROPOSAL_OUTCOMES.get(p.get("proposal_type")) and isinstance(p.get("target_reference"),Mapping) and bool(p.get("target_reference")) and isinstance(p.get("rationale_references"),list) and bool(p.get("rationale_references")) and all(isinstance(r,Mapping) and set(r)==REFERENCE_FIELDS and all(isinstance(r.get(k),str) and r.get(k) for k in REFERENCE_FIELDS) for r in p.get("rationale_references",[])) and isinstance(p.get("limitations_acknowledged"),list) and all(isinstance(x,str) and x for x in p.get("limitations_acknowledged",[]))
def build_capability_bounded_decision_review_request(readiness_closure:Any,decision_proposal:Any,*,requested_scope:Any,requested_effect_class:Any,requested_permissions:Any)->dict[str,Any]:
 c=deepcopy(dict(readiness_closure)) if isinstance(readiness_closure,Mapping) else {}
 try:p=_safe(decision_proposal);scope=_safe(requested_scope);perms=_safe(requested_permissions)
 except (TypeError,ValueError):p={};scope={};perms={};bad=True
 else:bad=False
 q=c.get("decision_question",{}) if isinstance(c.get("decision_question"),Mapping) else {};limit=q.get("decision_scope",{}) if isinstance(q,Mapping) else {};limitations=c.get("limitations",[]) if isinstance(c.get("limitations"),list) else []
 valid=validate_capability_decision_readiness_closure(c).valid;shape=_proposal_shape(p);permission_ok=isinstance(perms,Mapping) and set(perms)==PERMISSION_FIELDS and all(v is False for v in perms.values());target_ok=isinstance(q,Mapping) and p.get("target_reference")==q.get("target_reference");limits_ok=all(x in p.get("limitations_acknowledged",[]) for x in limitations) if isinstance(p,Mapping) else False;scope_ok=_scope_contained(scope,limit)
 if bad or not valid or not shape or requested_effect_class not in EFFECT_CLASSES:status="invalid";why="malformed_decision_review_input"
 elif p.get("proposal_type") in FORBIDDEN_PROPOSALS or not permission_ok or not scope_ok or not target_ok or not limits_ok:status="blocked";why="bounded_decision_review_invariant_violation"
 elif c.get("verification_status")!="verified_closed" or c.get("closed") is not True or c.get("decision_made_claim") is not False or c.get("authorization_claim") is not False or c.get("execution_completion_claim") is not False:status="not_accepted";why="decision_readiness_closure_not_eligible"
 elif not isinstance(c.get("readiness_consistency_results"),Mapping) or c["readiness_consistency_results"].get("valid") is not True:status="not_accepted";why="decision_not_ready"
 else:status="accepted";why="bounded_decision_review_request_accepted"
 b={"contract":CONTRACT,"schema_version":SCHEMA_VERSION,"decision_readiness_closure_id":c.get("decision_readiness_closure_id",""),"decision_readiness_closure_fingerprint":c.get("decision_readiness_closure_fingerprint",""),"authority_id":c.get("authority_id",""),"authority_fingerprint":c.get("authority_fingerprint",""),"execution_request_id":c.get("execution_request_id",""),"execution_request_fingerprint":c.get("execution_request_fingerprint",""),"observation_closure_id":c.get("observation_closure_id",""),"observation_closure_fingerprint":c.get("observation_closure_fingerprint",""),"decision_question":deepcopy(q),"decision_proposal":deepcopy(p),"requested_scope":deepcopy(scope),"requested_effect_class":requested_effect_class if isinstance(requested_effect_class,str) else "","requested_permissions":deepcopy(perms),"review_status":status,"accepted":status=="accepted","reasons":[why],"blocked_reasons":[why] if status=="blocked" else []};f=_hash(b);return {**b,"decision_review_request_id":"capability-bounded-decision-review-request-"+f[:24],"decision_review_request_fingerprint":f}
request_capability_bounded_decision_review=build_capability_bounded_decision_review_request
