from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash
from core.runtime.runtime_capability_bounded_decision_review_request import PROPOSAL_OUTCOMES,PERMISSION_FIELDS,_scope_contained
from core.runtime.runtime_capability_bounded_decision_review_request_validation import validate_capability_bounded_decision_review_request
CONTRACT="zero.runtime.capability_decision_review_eligibility.v1";SCHEMA_VERSION="1";STATUSES=frozenset({"eligible","not_eligible","blocked","invalid"})
def build_capability_decision_review_eligibility(review_request:Any,readiness_closure:Any)->dict[str,Any]:
 r,c=[deepcopy(dict(x)) if isinstance(x,Mapping) else {} for x in (review_request,readiness_closure)];p=r.get("decision_proposal",{}) if isinstance(r.get("decision_proposal"),Mapping) else {};q=r.get("decision_question",{}) if isinstance(r.get("decision_question"),Mapping) else {};links=r.get("decision_readiness_closure_id")==c.get("decision_readiness_closure_id") and r.get("decision_readiness_closure_fingerprint")==c.get("decision_readiness_closure_fingerprint");scope=_scope_contained(r.get("requested_scope"),q.get("decision_scope",{}));limits=all(x in p.get("limitations_acknowledged",[]) for x in c.get("limitations",[]));permissions=isinstance(r.get("requested_permissions"),Mapping) and set(r["requested_permissions"])==PERMISSION_FIELDS and all(x is False for x in r["requested_permissions"].values());claims=not any(k in p for k in ("execution_complete","authorization_obtained","mutation_approved"));mapping=p.get("proposed_outcome")==PROPOSAL_OUTCOMES.get(p.get("proposal_type"));target=p.get("target_reference")==q.get("target_reference")
 if not validate_capability_bounded_decision_review_request(r).valid or not links:status="invalid";why="malformed_review_request_or_linkage"
 elif r.get("review_status")!="accepted":status="not_eligible";why="review_request_not_accepted"
 elif not all((scope,limits,permissions,claims,mapping,target)):status="blocked";why="decision_review_eligibility_invariant_violation"
 else:status="eligible";why="decision_review_eligible"
 check=lambda x:{"valid":bool(x)};b={"contract":CONTRACT,"schema_version":SCHEMA_VERSION,"decision_review_request_id":r.get("decision_review_request_id",""),"decision_review_request_fingerprint":r.get("decision_review_request_fingerprint",""),"decision_readiness_closure_id":c.get("decision_readiness_closure_id",""),"decision_readiness_closure_fingerprint":c.get("decision_readiness_closure_fingerprint",""),"decision_question":deepcopy(q),"proposal_id":p.get("proposal_id",""),"proposal_type":p.get("proposal_type",""),"proposed_outcome":p.get("proposed_outcome",""),"scope_checks":check(scope),"limitation_checks":check(limits),"permission_checks":check(permissions),"claim_checks":check(claims),"eligibility_status":status,"eligible":status=="eligible","reasons":[why],"blocked_reasons":[why] if status=="blocked" else []};f=_hash(b);return {**b,"decision_review_eligibility_id":"capability-decision-review-eligibility-"+f[:24],"decision_review_eligibility_fingerprint":f}
