from __future__ import annotations
from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash
CONTRACT="zero.runtime.capability_runtime_outcome_reconciliation.v1";SCHEMA_VERSION="1";STATUSES=frozenset({"reconciled","not_reconciled","blocked","failed","invalid"})
def build_capability_runtime_outcome_reconciliation(authority:Any,request:Any,admission:Any,plan:Any,result:Any)->dict[str,Any]:
 a,r,d,p,x=[deepcopy(dict(v)) if isinstance(v,Mapping) else {} for v in (authority,request,admission,plan,result)];rs=x.get("result_status");mapping={"simulated":("simulated","not_completed","reconciled"),"not_simulated":("not_simulated","not_completed","not_reconciled"),"blocked":("blocked","blocked","blocked"),"failed":("failed","failed","failed"),"invalid":("invalid","not_completed","invalid")};bridge,recommend,status=mapping.get(rs,("invalid","not_completed","invalid"))
 links=d.get("authority_id")==a.get("authority_id") and d.get("authority_fingerprint")==a.get("fingerprint") and d.get("request_id")==r.get("request_id") and d.get("request_fingerprint")==r.get("fingerprint") and p.get("adapter_admission_id")==d.get("adapter_admission_id") and p.get("dispatch_plan_fingerprint")==x.get("dispatch_plan_fingerprint") and x.get("dispatch_plan_id")==p.get("dispatch_plan_id") and p.get("adapter_id")==x.get("adapter_id") and p.get("operation_class")==x.get("operation_class")
 if not links or p.get("dry_run") is not True or x.get("side_effects_performed")!=[]:status="invalid";why="reconciliation_invariant_violation"
 else:why="dry_run_result_"+status
 b={"contract":CONTRACT,"schema_version":SCHEMA_VERSION,"authority_id":a.get("authority_id",""),"authority_fingerprint":a.get("fingerprint",""),"request_id":r.get("request_id",""),"request_fingerprint":r.get("fingerprint",""),"adapter_admission_id":d.get("adapter_admission_id",""),"adapter_admission_fingerprint":d.get("adapter_admission_fingerprint",""),"dispatch_plan_id":p.get("dispatch_plan_id",""),"dispatch_plan_fingerprint":p.get("dispatch_plan_fingerprint",""),"dispatch_result_id":x.get("dispatch_result_id",""),"dispatch_result_fingerprint":x.get("dispatch_result_fingerprint",""),"adapter_id":d.get("adapter_id",""),"operation_class":r.get("operation_class",""),"bridge_status":bridge,"execution_completion_claim":False,"recommended_v1_2_outcome_status":recommend,"reconciliation_status":status,"evidence_references":x.get("evidence_references",[]) if isinstance(x.get("evidence_references"),list) else [],"reasons":[why],"blocked_reasons":[why] if status=="blocked" else [],"failure_reasons":[why] if status=="failed" else []};f=_hash(b);return {**b,"reconciliation_id":"capability-runtime-outcome-reconciliation-"+f[:24],"reconciliation_fingerprint":f}
def controlled_execution_outcome_arguments(reconciliation):return {"observed_status":reconciliation.get("recommended_v1_2_outcome_status","not_completed"),"evidence_references":reconciliation.get("evidence_references",[]),"result_summary":{"dry_run_bridge_status":reconciliation.get("bridge_status"),"execution_completion_claim":False}}
