from __future__ import annotations


class RuntimeRouteKeys:
    ENGINEERING_TASK = "engineering_task"
    WORK_PACKAGE = "work_package"
    ENGINEERING_GOAL = "engineering_goal"
    PLANNER_RUNTIME = "planner_runtime"
    PERSISTENT_RUNTIME = "persistent_runtime"
    PLANNER_OWNED_CODE_CHAIN = "planner_owned_code_chain"
    CODE_CHAIN_CONTROLLED_SELF_EDIT = "code_chain_controlled_self_edit"
    AUTONOMOUS_REPAIR = "autonomous_repair"
    REPAIR_PREFLIGHT = "repair_preflight"
    CLI_TASK_RUN = "cli_task_run"
    CLI_TASK_DRAIN = "cli_task_drain"
    CLI_WORK_PACKAGE_SUBMIT = "cli_work_package_submit"
    CLI_WORK_PACKAGE_RUN = "cli_work_package_run"
    CLI_WORK_PACKAGE_VALIDATION = "cli_work_package_validation"
    CLI_WORK_PACKAGE_DISPATCH_REQUEST = "cli_work_package_dispatch_request"
    CLI_CONTROL_SUBMIT = "cli_control_submit"
    CLI_GOAL_RUN = "cli_goal_run"
    CLI_GOAL_LOOP = "cli_goal_loop"
    CLI_PORTFOLIO_RUN = "cli_portfolio_run"
    CLI_PORTFOLIO_CYCLE = "cli_portfolio_cycle"
    CLI_PROGRAM_RUN = "cli_program_run"
    CLI_PROGRAM_CYCLE = "cli_program_cycle"
    SCHEDULER_TICK = "scheduler_tick"
    SCHEDULER_RUN_STEP = "scheduler_run_step"
    SCHEDULER_SUBMIT_TASK = "scheduler_submit_task"
    TASK_RUNNER_RUN = "task_runner_run"
    TASK_RUNNER_TICK = "task_runner_tick"
    TASK_RUNNER_EXECUTE_STEP = "task_runner_execute_step"
    TASK_RUNNER_EXECUTE_STEPS = "task_runner_execute_steps"
