from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash
from core.runtime.runtime_capability_bounded_decision_review_request import PERMISSION_FIELDS,PROPOSAL_OUTCOMES,_scope_contained
from core.runtime.runtime_capability_decision_policy_evaluation_validation import validate_capability_decision_policy_evaluation
CONTRACT="zero.runtime.capability_decision_authorization.v1";SCHEMA_VERSION="1";STATUSES=frozenset({"authorized","not_authorized","blocked","invalid"});NEXT_STAGES={"confirm_observation":"observation_confirmation_closure","request_additional_observation":"additional_observation_review","accept_no_further_action":"no_further_action_closure","prepare_execution_plan_review":"execution_plan_review_admission"};NEXT_STAGE_ALLOWLIST=frozenset(set(NEXT_STAGES.values())|{"blocked","invalid"})
def build_capability_decision_authorization(policy:Any,eligibility:Any,review_request:Any,readiness_closure:Any)->dict[str,Any]:
 p,e,r,c=[deepcopy(dict(x)) if isinstance(x,Mapping) else {} for x in (policy,eligibility,review_request,readiness_closure)];proposal=r.get("decision_proposal",{}) if isinstance(r.get("decision_proposal"),Mapping) else {};ptype=proposal.get("proposal_type","");links=p.get("decision_review_eligibility_id")==e.get("decision_review_eligibility_id") and p.get("decision_review_request_id")==r.get("decision_review_request_id") and p.get("decision_readiness_closure_id")==c.get("decision_readiness_closure_id");scope=_scope_contained(p.get("approved_scope"),r.get("requested_scope"));limits=all(x in p.get("limitations",[]) for x in c.get("limitations",[]));permissions=isinstance(p.get("approved_permissions"),Mapping) and set(p["approved_permissions"])==PERMISSION_FIELDS and all(x is False for x in p["approved_permissions"].values())
 if not validate_capability_decision_policy_evaluation(p).valid or not links:status="invalid";why="malformed_policy_or_linkage"
 elif p.get("policy_status")!="approved" or p.get("approved") is not True or e.get("eligibility_status")!="eligible" or r.get("review_status")!="accepted":status="not_authorized";why="decision_chain_not_approved"
 elif not scope or not limits or not permissions or ptype not in NEXT_STAGES:status="blocked";why="authorization_invariant_violation"
 else:status="authorized";why="bounded_decision_authorized"
 perms={k:False for k in PERMISSION_FIELDS};b={"contract":CONTRACT,"schema_version":SCHEMA_VERSION,"decision_policy_evaluation_id":p.get("decision_policy_evaluation_id",""),"decision_policy_evaluation_fingerprint":p.get("decision_policy_evaluation_fingerprint",""),"decision_review_eligibility_id":e.get("decision_review_eligibility_id",""),"decision_review_eligibility_fingerprint":e.get("decision_review_eligibility_fingerprint",""),"decision_review_request_id":r.get("decision_review_request_id",""),"decision_review_request_fingerprint":r.get("decision_review_request_fingerprint",""),"decision_readiness_closure_id":c.get("decision_readiness_closure_id",""),"decision_readiness_closure_fingerprint":c.get("decision_readiness_closure_fingerprint",""),"proposal_id":proposal.get("proposal_id",""),"proposal_type":ptype,"authorized_outcome":PROPOSAL_OUTCOMES.get(ptype,""),"authorized_scope":deepcopy(p.get("approved_scope",{})) if status=="authorized" else {},"authorized_effect_class":p.get("approved_effect_class","none") if status=="authorized" else "none","authorized_permissions":perms,"authorized_next_stage":NEXT_STAGES.get(ptype,"invalid") if status=="authorized" else ("blocked" if status=="blocked" else "invalid"),"authorization_status":status,"authorized":status=="authorized","execution_completion_claim":False,"mutation_authorization_claim":False,"external_execution_authorization_claim":False,"limitations":deepcopy(p.get("limitations",[])),"reasons":[why],"blocked_reasons":[why] if status=="blocked" else []};f=_hash(b);return {**b,"decision_authorization_id":"capability-decision-authorization-"+f[:24],"decision_authorization_fingerprint":f}
