from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash
from core.runtime.runtime_capability_bounded_decision_review_request import PERMISSION_FIELDS,_scope_contained
from core.runtime.runtime_capability_bounded_decision_review_request_validation import validate_capability_bounded_decision_review_request
from core.runtime.runtime_capability_decision_review_eligibility_validation import validate_capability_decision_review_eligibility
from core.runtime.runtime_capability_decision_policy_evaluation_validation import validate_capability_decision_policy_evaluation
from core.runtime.runtime_capability_decision_authorization import NEXT_STAGES
from core.runtime.runtime_capability_decision_authorization_validation import validate_capability_decision_authorization
CONTRACT="zero.runtime.capability_decision_authorization_closure.v1";SCHEMA_VERSION="1";STATUSES=frozenset({"verified_closed","not_verified","blocked","failed","invalid"})
def close_capability_decision_authorization(authority:Any,execution_request:Any,observation_closure:Any,readiness_closure:Any,review_request:Any,eligibility:Any,policy:Any,authorization:Any)->dict[str,Any]:
 a,x,o,c,r,e,p,z=[deepcopy(dict(v)) if isinstance(v,Mapping) else {} for v in (authority,execution_request,observation_closure,readiness_closure,review_request,eligibility,policy,authorization)];proposal=r.get("decision_proposal",{}) if isinstance(r.get("decision_proposal"),Mapping) else {};q=r.get("decision_question",{}) if isinstance(r.get("decision_question"),Mapping) else {}
 validators=validate_capability_bounded_decision_review_request(r).valid and validate_capability_decision_review_eligibility(e).valid and validate_capability_decision_policy_evaluation(p).valid and validate_capability_decision_authorization(z).valid
 links=r.get("decision_readiness_closure_id")==c.get("decision_readiness_closure_id") and e.get("decision_review_request_id")==r.get("decision_review_request_id") and p.get("decision_review_eligibility_id")==e.get("decision_review_eligibility_id") and z.get("decision_policy_evaluation_id")==p.get("decision_policy_evaluation_id") and c.get("authority_id")==a.get("authority_id") and c.get("execution_request_id")==x.get("request_id") and c.get("observation_closure_id")==o.get("observation_closure_id")
 scope=_scope_contained(z.get("authorized_scope"),r.get("requested_scope"));policy_ok=p.get("policy_status")=="approved" and p.get("approved") is True and z.get("authorized_effect_class")==p.get("approved_effect_class") and z.get("authorized_next_stage")==NEXT_STAGES.get(proposal.get("proposal_type"));permissions=all(isinstance(v,Mapping) and set(v)==PERMISSION_FIELDS and all(i is False for i in v.values()) for v in (r.get("requested_permissions"),p.get("approved_permissions"),z.get("authorized_permissions")));limits=all(i in z.get("limitations",[]) for i in c.get("limitations",[])) and all(i in p.get("limitations",[]) for i in c.get("limitations",[]));claims=all(z.get(n) is False for n in ("execution_completion_claim","mutation_authorization_claim","external_execution_authorization_claim"));chain=validators and links and c.get("verification_status")=="verified_closed" and r.get("review_status")=="accepted" and e.get("eligibility_status")=="eligible" and z.get("authorization_status")=="authorized" and z.get("proposal_id")==proposal.get("proposal_id") and z.get("proposal_type")==proposal.get("proposal_type") and z.get("authorized_outcome")==proposal.get("proposed_outcome")
 if chain and scope and policy_ok and permissions and limits and claims:status="verified_closed";why="decision_authorization_verified_closed"
 elif any(v=="blocked" for v in (r.get("review_status"),e.get("eligibility_status"),p.get("policy_status"),z.get("authorization_status"))):status="blocked";why="decision_authorization_chain_blocked"
 elif not validators or not links:status="invalid";why="decision_authorization_chain_invalid"
 else:status="not_verified";why="decision_authorization_not_verified"
 ck=lambda v:{"valid":bool(v)};b={"contract":CONTRACT,"schema_version":SCHEMA_VERSION,"authority_id":a.get("authority_id",""),"authority_fingerprint":a.get("fingerprint",""),"execution_request_id":x.get("request_id",""),"execution_request_fingerprint":x.get("fingerprint",""),"observation_closure_id":o.get("observation_closure_id",""),"observation_closure_fingerprint":o.get("observation_closure_fingerprint",""),"decision_readiness_closure_id":c.get("decision_readiness_closure_id",""),"decision_readiness_closure_fingerprint":c.get("decision_readiness_closure_fingerprint",""),"decision_review_request_id":r.get("decision_review_request_id",""),"decision_review_request_fingerprint":r.get("decision_review_request_fingerprint",""),"decision_review_eligibility_id":e.get("decision_review_eligibility_id",""),"decision_review_eligibility_fingerprint":e.get("decision_review_eligibility_fingerprint",""),"decision_policy_evaluation_id":p.get("decision_policy_evaluation_id",""),"decision_policy_evaluation_fingerprint":p.get("decision_policy_evaluation_fingerprint",""),"decision_authorization_id":z.get("decision_authorization_id",""),"decision_authorization_fingerprint":z.get("decision_authorization_fingerprint",""),"decision_question":deepcopy(q),"proposal_id":proposal.get("proposal_id",""),"proposal_type":proposal.get("proposal_type",""),"proposed_outcome":proposal.get("proposed_outcome",""),"target_reference":deepcopy(proposal.get("target_reference",{})),"chain_validation_results":ck(chain),"scope_consistency_results":ck(scope),"policy_consistency_results":ck(policy_ok),"permission_invariant_results":ck(permissions),"limitation_preservation_results":ck(limits),"claim_invariant_results":ck(claims),"execution_completion_claim":False,"mutation_authorization_claim":False,"external_execution_authorization_claim":False,"decision_executed_claim":False,"verification_status":status,"closed":status=="verified_closed","authorized_next_stage":z.get("authorized_next_stage","invalid"),"limitations":deepcopy(z.get("limitations",[])),"reasons":[why],"blocked_reasons":[why] if status=="blocked" else [],"failure_reasons":[why] if status=="failed" else []};f=_hash(b);return {**b,"decision_authorization_closure_id":"capability-decision-authorization-closure-"+f[:24],"decision_authorization_closure_fingerprint":f}
