from __future__ import annotations
from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash
from core.runtime.runtime_capability_observation_evidence_consumer_acceptance_validation import validate_capability_observation_evidence_consumer_acceptance
from core.runtime.runtime_capability_observation_evidence_relevance_assessment_validation import validate_capability_observation_evidence_relevance_assessment
from core.runtime.runtime_capability_observation_evidence_sufficiency_assessment_validation import validate_capability_observation_evidence_sufficiency_assessment
from core.runtime.runtime_capability_decision_readiness_assessment_validation import validate_capability_decision_readiness_assessment
CONTRACT="zero.runtime.capability_decision_readiness_closure.v1";SCHEMA_VERSION="1";STATUSES=frozenset({"verified_closed","not_verified","blocked","failed","invalid"})
def close_capability_decision_readiness(authority:Any,execution_request:Any,bridge_closure:Any,observation_closure:Any,acceptance:Any,relevance:Any,sufficiency:Any,readiness:Any)->dict[str,Any]:
 a,e,b,o,c,r,s,d=[deepcopy(dict(v)) if isinstance(v,Mapping) else {} for v in (authority,execution_request,bridge_closure,observation_closure,acceptance,relevance,sufficiency,readiness)];question=r.get("decision_question",{}) if isinstance(r.get("decision_question"),Mapping) else {};limits=s.get("limitations",[]) if isinstance(s.get("limitations"),list) else []
 valid=validate_capability_observation_evidence_consumer_acceptance(c).valid and validate_capability_observation_evidence_relevance_assessment(r).valid and validate_capability_observation_evidence_sufficiency_assessment(s).valid and validate_capability_decision_readiness_assessment(d).valid
 chain=valid and a.get("status")=="authorized" and e.get("status")=="accepted" and b.get("verification_status")=="verified_closed" and o.get("verification_status")=="verified_closed" and c.get("acceptance_status")=="accepted" and r.get("relevance_status")=="relevant" and s.get("sufficiency_status")=="sufficient" and d.get("decision_status")=="ready" and o.get("authority_id")==a.get("authority_id") and o.get("request_id")==e.get("request_id") and o.get("bridge_closure_id")==b.get("bridge_closure_id") and c.get("observation_closure_id")==o.get("observation_closure_id") and r.get("consumer_acceptance_id")==c.get("consumer_acceptance_id") and s.get("relevance_assessment_id")==r.get("relevance_assessment_id") and d.get("sufficiency_assessment_id")==s.get("sufficiency_assessment_id")
 integrity=o.get("closed") is True and o.get("execution_completion_claim") is False and all(isinstance(v,str) and v for v in (o.get("observation_result_id"),o.get("observation_result_fingerprint")));rel=r.get("decision_question")==question and r.get("observed_kind") in r.get("required_observation_kinds",[]) and r.get("target_reference")==question.get("target_reference");suf=s.get("decision_question")==question and isinstance(limits,list) and d.get("limitations")==limits;ready=d.get("decision_question")==question and d.get("execution_completion_claim") is False and d.get("authorization_claim") is False and d.get("recommended_next_stage")=="bounded_decision_review"
 if chain and integrity and rel and suf and ready:status="verified_closed";why="decision_readiness_verified_closed"
 elif any(v=="blocked" for v in (c.get("acceptance_status"),r.get("relevance_status"),s.get("sufficiency_status"),d.get("decision_status"))):status="blocked";why="decision_readiness_chain_blocked"
 elif any(v=="invalid" for v in (c.get("acceptance_status"),r.get("relevance_status"),s.get("sufficiency_status"),d.get("decision_status"))):status="invalid";why="decision_readiness_chain_invalid"
 else:status="not_verified";why="decision_readiness_not_verified"
 checks=lambda valid:{"valid":valid}
 bdy={"contract":CONTRACT,"schema_version":SCHEMA_VERSION,"authority_id":a.get("authority_id",""),"authority_fingerprint":a.get("fingerprint",""),"execution_request_id":e.get("request_id",""),"execution_request_fingerprint":e.get("fingerprint",""),"bridge_closure_id":b.get("bridge_closure_id",""),"bridge_closure_fingerprint":b.get("bridge_closure_fingerprint",""),"observation_closure_id":o.get("observation_closure_id",""),"observation_closure_fingerprint":o.get("observation_closure_fingerprint",""),"consumer_acceptance_id":c.get("consumer_acceptance_id",""),"consumer_acceptance_fingerprint":c.get("consumer_acceptance_fingerprint",""),"relevance_assessment_id":r.get("relevance_assessment_id",""),"relevance_assessment_fingerprint":r.get("relevance_assessment_fingerprint",""),"sufficiency_assessment_id":s.get("sufficiency_assessment_id",""),"sufficiency_assessment_fingerprint":s.get("sufficiency_assessment_fingerprint",""),"decision_readiness_id":d.get("decision_readiness_id",""),"decision_readiness_fingerprint":d.get("decision_readiness_fingerprint",""),"decision_question":deepcopy(question),"chain_validation_results":checks(chain),"evidence_integrity_results":checks(integrity),"relevance_consistency_results":checks(rel),"sufficiency_consistency_results":checks(suf),"readiness_consistency_results":checks(ready),"execution_completion_claim":False,"authorization_claim":False,"decision_made_claim":False,"verification_status":status,"closed":status=="verified_closed","limitations":deepcopy(limits),"reasons":[why],"blocked_reasons":[why] if status=="blocked" else [],"failure_reasons":[why] if status=="failed" else []};f=_hash(bdy);return {**bdy,"decision_readiness_closure_id":"capability-decision-readiness-closure-"+f[:24],"decision_readiness_closure_fingerprint":f}
