from __future__ import annotations
from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash
CONTRACT="zero.runtime.capability_observation_evidence_closure.v1";SCHEMA_VERSION="1";STATUSES=frozenset({"verified_closed","not_verified","blocked","failed","invalid"})
def close_capability_observation_evidence(authority:Any,execution_request:Any,bridge_closure:Any,admission:Any,observation_request:Any,resolution:Any,result:Any)->dict[str,Any]:
 a,r,c,d,q,z,x=[deepcopy(dict(v)) if isinstance(v,Mapping) else {} for v in (authority,execution_request,bridge_closure,admission,observation_request,resolution,result)]
 chain=a.get("status")=="authorized" and r.get("status")=="accepted" and c.get("verification_status")=="verified_closed" and d.get("admission_status")=="admitted" and q.get("request_status")=="accepted" and z.get("resolution_status")=="resolved" and x.get("result_status")=="observed" and d.get("authority_id")==a.get("authority_id")==c.get("authority_id") and d.get("request_id")==r.get("request_id")==c.get("request_id") and q.get("read_only_admission_id")==d.get("read_only_admission_id") and z.get("observation_request_id")==q.get("observation_request_id") and x.get("target_resolution_id")==z.get("target_resolution_id")
 contain=z.get("containment_verified") is True and z.get("symlink_or_reparse_detected") is False;readonly=x.get("side_effects_performed")==[];lim=q.get("limits",{}) if isinstance(q.get("limits"),Mapping) else {};bounded=isinstance(x.get("bytes_read"),int) and not isinstance(x.get("bytes_read"),bool) and 0<=x["bytes_read"]<=max(lim.get("max_file_bytes",-1),lim.get("max_preview_bytes",-1)) and isinstance(x.get("entries_observed"),int) and not isinstance(x.get("entries_observed"),bool) and 0<=x["entries_observed"]<=lim.get("max_directory_entries",-1);evidence=isinstance(x.get("evidence_descriptor"),Mapping) and x["evidence_descriptor"].get("bounded") is True and x["evidence_descriptor"].get("kind")==q.get("observation_kind") and x.get("observation_kind")==q.get("observation_kind")
 if chain and contain and readonly and bounded and evidence:status="verified_closed";why="observation_evidence_verified_closed"
 elif x.get("result_status") in {"blocked","failed","invalid"}:status=x.get("result_status");why="observation_"+status
 elif not contain or not readonly or not bounded:status="blocked";why="observation_invariant_violation"
 else:status="not_verified";why="observation_chain_not_verified"
 rec={"observed":"not_completed","not_observed":"not_completed","blocked":"blocked","failed":"failed","invalid":"invalid"}.get(x.get("result_status"),"invalid")
 b={"contract":CONTRACT,"schema_version":SCHEMA_VERSION,"authority_id":a.get("authority_id",""),"authority_fingerprint":a.get("fingerprint",""),"request_id":r.get("request_id",""),"request_fingerprint":r.get("fingerprint",""),"bridge_closure_id":c.get("bridge_closure_id",""),"bridge_closure_fingerprint":c.get("bridge_closure_fingerprint",""),"read_only_admission_id":d.get("read_only_admission_id",""),"read_only_admission_fingerprint":d.get("read_only_admission_fingerprint",""),"observation_request_id":q.get("observation_request_id",""),"observation_request_fingerprint":q.get("observation_request_fingerprint",""),"target_resolution_id":z.get("target_resolution_id",""),"target_resolution_fingerprint":z.get("target_resolution_fingerprint",""),"observation_result_id":x.get("observation_result_id",""),"observation_result_fingerprint":x.get("observation_result_fingerprint",""),"chain_validation_results":{"valid":chain},"containment_validation_results":{"valid":contain},"read_only_invariant_results":{"valid":readonly},"boundedness_validation_results":{"valid":bounded},"evidence_validation_results":{"valid":evidence},"execution_completion_claim":False,"recommended_v1_2_outcome_status":rec,"verification_status":status,"closed":status=="verified_closed","reasons":[why],"blocked_reasons":[why] if status=="blocked" else [],"failure_reasons":[why] if status=="failed" else []};f=_hash(b);return {**b,"observation_closure_id":"capability-observation-evidence-closure-"+f[:24],"observation_closure_fingerprint":f}
