from __future__ import annotations
from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash,_safe
from core.runtime.runtime_capability_decision_authorization_closure_validation import validate_capability_decision_authorization_closure
from core.runtime.runtime_apply_execution_plan_builder import build_runtime_apply_execution_plan
from core.runtime.runtime_execution_plan_review_gate import review_execution_plan,RUNTIME_EXECUTION_PLAN_OPERATOR_REVIEW_CONTRACT
from core.runtime.runtime_executor_admission_token import issue_executor_admission_token,RUNTIME_OPERATOR_EXECUTION_REQUEST_CONTRACT
from core.runtime.runtime_controlled_execution_activation import activate_controlled_execution
from core.runtime.runtime_active_execution_authorization import authorize_active_execution,RUNTIME_ACTIVE_AUTHORIZATION_REQUEST_CONTRACT
from core.runtime.runtime_transactional_active_execution import prepare_transactional_active_plan
from core.runtime.runtime_transactional_active_execution_preparation_validation import validate_transactional_active_plan_preparation
HANDOFF_CONTRACT="zero.runtime.capability_prepared_transaction_handoff.v1";CLOSURE_CONTRACT="zero.runtime.capability_transaction_preparation_integration_closure.v1";SCHEMA_VERSION="1"
PERMISSIONS=("filesystem_read","filesystem_write","filesystem_mutation","external_process","network","model_invocation","transaction_commit")
PROHIBITED=("filesystem_mutation","process_creation","network_access","model_invocation","transaction_commit","external_side_effect")
def _m(v:Any)->dict[str,Any]:return deepcopy(dict(v)) if isinstance(v,Mapping) else {}
def _handoff(c:dict,i:dict,p:dict,r:dict,t:dict,a:dict,z:dict,prep:dict)->dict[str,Any]:
 ok=validate_transactional_active_plan_preparation(prep).valid and prep.get("preparation_status")=="prepared"
 b={"contract":HANDOFF_CONTRACT,"schema_version":SCHEMA_VERSION,"decision_authorization_closure_id":c.get("decision_authorization_closure_id",""),"decision_authorization_closure_fingerprint":c.get("decision_authorization_closure_fingerprint",""),"decision_authorization_id":c.get("decision_authorization_id",""),"decision_authorization_fingerprint":c.get("decision_authorization_fingerprint",""),"execution_intent_id":i.get("intent_id",""),"execution_intent_fingerprint":_hash(i),"execution_plan_id":p.get("plan_id",""),"execution_plan_fingerprint":_hash(p),"execution_review_id":r.get("result_id",""),"execution_review_fingerprint":_hash(r),"admission_token_id":t.get("token_id",""),"admission_token_fingerprint":_hash(t),"controlled_activation_id":a.get("activation_id",""),"controlled_activation_fingerprint":_hash(a),"active_authorization_id":z.get("authorization_result_id",""),"active_authorization_fingerprint":_hash(z),"transaction_preparation_id":prep.get("preparation_id",""),"transaction_preparation_fingerprint":prep.get("preparation_fingerprint",""),"target_boundary":deepcopy(i.get("target_descriptor",{})),"authorized_scope":deepcopy(c.get("authorized_scope",{})),"prepared_scope":deepcopy(prep.get("prepared_scope",[])),"dry_run_only":True,"expected_effects":[],"prohibited_effects":list(PROHIBITED),"permissions":{k:False for k in PERMISSIONS},"limitations":deepcopy(c.get("limitations",[])),"preparation_status":prep.get("preparation_status","invalid"),"handoff_status":"prepared" if ok else "blocked","execution_started_claim":False,"execution_completion_claim":False,"mutation_authorization_claim":False,"mutation_performed_claim":False,"transaction_committed_claim":False,"reasons":["prepared_transaction_handoff" if ok else "transaction_preparation_blocked"],"blocked_reasons":[] if ok else ["transaction_preparation_blocked"],"failure_reasons":[]};f=_hash(b);return {**b,"handoff_id":"capability-prepared-transaction-handoff-"+f[:24],"handoff_fingerprint":f}
def _closure(c:dict,i:dict,p:dict,r:dict,t:dict,a:dict,z:dict,prep:dict,h:dict)->dict[str,Any]:
 chain=(h.get("handoff_status")=="prepared" and prep.get("preparation_status")=="prepared" and c.get("verification_status")=="verified_closed" and c.get("closed") is True and c.get("authorized_next_stage")=="execution_plan_review_admission" and p.get("plan_status")=="ready" and r.get("review_status")=="approved" and t.get("token_status")=="issued" and a.get("activation_status")=="completed" and z.get("authorization_status")=="authorized")
 checks={"chain_valid":chain,"scope_contained":prep.get("prepared_scope")==z.get("authorized_scope"),"limitations_preserved":h.get("limitations")==c.get("limitations"),"permissions_safe":all(v is False for v in h.get("permissions",{}).values()),"zero_side_effect_preparation":all(prep.get(k) is False for k in ("workspace_creation_required","snapshot_creation_required","mutation_required","validation_process_required","commit_required"))}
 ok=all(checks.values());b={"contract":CLOSURE_CONTRACT,"schema_version":SCHEMA_VERSION,"decision_authorization_closure_id":c.get("decision_authorization_closure_id",""),"execution_intent_id":i.get("intent_id",""),"execution_plan_id":p.get("plan_id",""),"execution_review_id":r.get("result_id",""),"admission_token_id":t.get("token_id",""),"controlled_activation_id":a.get("activation_id",""),"active_authorization_id":z.get("authorization_result_id",""),"transaction_preparation_id":prep.get("preparation_id",""),"prepared_handoff_id":h.get("handoff_id",""),"integration_checks":checks,"verification_status":"verified_closed" if ok else "blocked","closed":ok,"execution_started_claim":False,"execution_completion_claim":False,"mutation_authorization_claim":False,"mutation_performed_claim":False,"transaction_committed_claim":False,"limitations":deepcopy(c.get("limitations",[])),"reasons":["transaction_preparation_integration_verified" if ok else "transaction_preparation_integration_blocked"],"blocked_reasons":[] if ok else ["transaction_preparation_integration_blocked"],"failure_reasons":[]};f=_hash(b);return {**b,"integration_closure_id":"capability-transaction-preparation-integration-closure-"+f[:24],"integration_closure_fingerprint":f}
def prepare_capability_decision_transaction(decision_closure:Any,execution_intent:Any,*,proposal:Any,approval_record:Any,admission_record:Any,operator_review:Any,operator_execution_request:Any,active_authorization_request:Any,target_root:Any,now:Any)->dict[str,Any]:
 c,i=[_m(x) for x in (decision_closure,execution_intent)];valid=validate_capability_decision_authorization_closure(c).valid and c.get("verification_status")=="verified_closed" and c.get("authorized_next_stage")=="execution_plan_review_admission"
 try:i=_safe(i)
 except (TypeError,ValueError):valid=False;i={}
 p=build_runtime_apply_execution_plan(proposal=_m(proposal),approval_record=_m(approval_record),admission_record=_m(admission_record),now=now)
 rv=_m(operator_review);rv.update({"contract":RUNTIME_EXECUTION_PLAN_OPERATOR_REVIEW_CONTRACT,"plan_id":p.get("plan_id"),"acknowledged_scope":deepcopy(p.get("allowed_files",[])),"acknowledged_constraints":deepcopy(p.get("execution_constraints",{})),"acknowledged_security_invariants":{k:p.get(k) for k in ("execution_started","mutation_started","mutation_allowed","patch_generation_allowed","patch_application_allowed","autonomous_apply_allowed","requires_controlled_executor","requires_separate_execution_step","requires_post_execution_validation","requires_rollback_capability")},"acknowledged_evidence_requirements":deepcopy(p.get("evidence_requirements",[]))});r=review_execution_plan(p,rv,now=now)
 oq=_m(operator_execution_request);oq.update({"contract":RUNTIME_OPERATOR_EXECUTION_REQUEST_CONTRACT,"plan_id":p.get("plan_id"),"review_result_id":r.get("result_id"),"operator_id":r.get("operator_id"),"requested_mode":"controlled_dry_run","acknowledged_dry_run":True,"acknowledged_no_file_mutation":True,"acknowledged_scope":deepcopy(p.get("allowed_files",[]))});t=issue_executor_admission_token(p,r,oq,target_root=target_root,now=now);a=activate_controlled_execution(p,r,oq,target_root=target_root,now=now)
 az=_m(active_authorization_request);az.update({"contract":RUNTIME_ACTIVE_AUTHORIZATION_REQUEST_CONTRACT,"controlled_execution_result_id":a.get("activation_id"),"token_id":a.get("token",{}).get("token_id"),"plan_id":a.get("plan_id"),"review_result_id":a.get("review_result_id"),"operator_execution_request_id":a.get("operator_request_id"),"operator_id":a.get("token",{}).get("operator_id"),"authorized_mode":"prepared_active_execution","acknowledged_scope":deepcopy(a.get("token",{}).get("allowed_files",[])),"acknowledged_snapshot_manifest_id":a.get("snapshot_manifest",{}).get("manifest_id"),"acknowledged_validation_evidence_id":a.get("validation_evidence",{}).get("validation_evidence_id"),"acknowledged_rollback_state_id":a.get("rollback_prepared_state",{}).get("rollback_state_id")});z=authorize_active_execution(a,az,now=now)
 prep=prepare_transactional_active_plan(p,r,t,a,z,i,limitations=c.get("limitations",[])) if valid else prepare_transactional_active_plan({}, {}, {}, {}, {}, i,limitations=c.get("limitations",[]));h=_handoff(c,i,p,r,t,a,z,prep);cl=_closure(c,i,p,r,t,a,z,prep,h)
 return {"decision_closure":c,"execution_intent":i,"execution_plan":p,"execution_review":r,"admission_token":t,"controlled_activation":a,"active_authorization":z,"transaction_preparation":prep,"prepared_handoff":h,"integration_closure":cl}
