from __future__ import annotations
from copy import deepcopy
from typing import Any,Mapping
from core.runtime.runtime_capability_execution_session_admission import _hash
CONTRACT="zero.runtime.capability_executor_bridge_verification_closure.v1";SCHEMA_VERSION="1";STATUSES=frozenset({"verified_closed","not_verified","blocked","failed","invalid"})
def close_capability_executor_bridge_verification(authority:Any,request:Any,admission:Any,plan:Any,result:Any,reconciliation:Any,*,controlled_execution_outcome:Any=None,execution_verification_closure:Any=None)->dict[str,Any]:
 a,r,d,p,x,c=[deepcopy(dict(v)) if isinstance(v,Mapping) else {} for v in (authority,request,admission,plan,result,reconciliation)];o=deepcopy(dict(controlled_execution_outcome)) if isinstance(controlled_execution_outcome,Mapping) else {};v=deepcopy(dict(execution_verification_closure)) if isinstance(execution_verification_closure,Mapping) else {}
 chain=a.get("status")=="authorized" and r.get("status")=="accepted" and d.get("admission_status")=="admitted" and p.get("plan_status")=="planned" and x.get("result_status")=="simulated" and c.get("reconciliation_status")=="reconciled" and d.get("authority_id")==a.get("authority_id") and d.get("request_id")==r.get("request_id") and p.get("adapter_admission_id")==d.get("adapter_admission_id") and x.get("dispatch_plan_id")==p.get("dispatch_plan_id") and c.get("dispatch_result_id")==x.get("dispatch_result_id")
 dry=p.get("dry_run") is True and d.get("adapter_mode")=="dry_run" and c.get("execution_completion_claim") is False and c.get("recommended_v1_2_outcome_status")=="not_completed";side=x.get("side_effects_performed")==[];outcome_ok=not o or o.get("status")!="completed";closure_ok=not v or v.get("status")!="verified_closed"
 if chain and dry and side and outcome_ok and closure_ok:status="verified_closed";why="dry_run_bridge_verified_closed"
 elif not outcome_ok or not closure_ok or not dry or not side:status="blocked";why="dry_run_completion_invariant_violation"
 else:status="not_verified";why="bridge_chain_not_verified"
 link=lambda q,n:(q.get(n+"_id","") if isinstance(q.get(n+"_id"),str) else "",q.get(n+"_fingerprint","") if isinstance(q.get(n+"_fingerprint"),str) else "")
 b={"contract":CONTRACT,"schema_version":SCHEMA_VERSION,"authority_id":a.get("authority_id",""),"authority_fingerprint":a.get("fingerprint",""),"request_id":r.get("request_id",""),"request_fingerprint":r.get("fingerprint",""),"adapter_admission_id":d.get("adapter_admission_id",""),"adapter_admission_fingerprint":d.get("adapter_admission_fingerprint",""),"dispatch_plan_id":p.get("dispatch_plan_id",""),"dispatch_plan_fingerprint":p.get("dispatch_plan_fingerprint",""),"dispatch_result_id":x.get("dispatch_result_id",""),"dispatch_result_fingerprint":x.get("dispatch_result_fingerprint",""),"reconciliation_id":c.get("reconciliation_id",""),"reconciliation_fingerprint":c.get("reconciliation_fingerprint",""),"controlled_execution_outcome_id":o.get("outcome_id","") if o else "","controlled_execution_outcome_fingerprint":o.get("fingerprint","") if o else "","execution_verification_closure_id":v.get("closure_id","") if v else "","execution_verification_closure_fingerprint":v.get("fingerprint","") if v else "","chain_validation_results":{"valid":chain},"dry_run_invariant_results":{"valid":dry},"side_effect_invariant_results":{"valid":side},"outcome_consistency_results":{"valid":outcome_ok and closure_ok},"verification_status":status,"closed":status=="verified_closed","reasons":[why],"blocked_reasons":[why] if status=="blocked" else [],"failure_reasons":[why] if status=="failed" else []};f=_hash(b);return {**b,"bridge_closure_id":"capability-executor-bridge-verification-closure-"+f[:24],"bridge_closure_fingerprint":f}
