"""Execution + review flow for natural-language repo edit tasks.

Strict H package boundary:
- creates a pending review from a sandbox edit
- does not apply changes during review creation
- apply/reject must be explicit
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from core.repo_sandbox.review import (
    apply_review,
    create_review_from_repo_edit_result,
    reject_review,
)

try:
    from core.repo_sandbox.task_bridge import run_code_edit_task
except Exception:  # pragma: no cover
    run_code_edit_task = None  # type: ignore[assignment]


def run_code_edit_review_task(task_text: str, *, repo_root: str | Path = ".") -> dict[str, Any]:
    """Run a conservative code edit task and return a pending review.

    This function does not apply changes to the repo. It only writes the sandbox
    edit via repo_edit and records review metadata.
    """

    if run_code_edit_task is None:
        return {
            "status": "error",
            "reason": "core.repo_sandbox.task_bridge.run_code_edit_task is unavailable",
        }

    result = run_code_edit_task(task_text)
    review = create_review_from_repo_edit_result(
        result,
        repo_root=repo_root,
        reason="generated by natural-language repo edit review flow",
    )

    payload = review.to_dict()
    payload["source_status"] = result.get("status")
    return payload


def decide_review(
    review_id: str,
    decision: str,
    *,
    repo_root: str | Path = ".",
    reason: str = "",
) -> dict[str, Any]:
    normalized = decision.strip().lower()

    if normalized in {"apply", "approve", "accepted", "yes"}:
        return apply_review(review_id, repo_root=repo_root)

    if normalized in {"reject", "decline", "discard", "no"}:
        return reject_review(review_id, repo_root=repo_root, reason=reason or "rejected by user")

    return {
        "status": "blocked",
        "review_id": review_id,
        "reason": f"unknown review decision: {decision}",
    }


__all__ = ["run_code_edit_review_task", "decide_review"]
