from cli.zero_engineering_mutation_preparation import pipeline
from core.engineering.engineering_mutation_preparation_common import fingerprint

def proposal_bundle():
 ops=[{'operation_id':'op1','operation_type':'create_text_file','target_relative_path':'src/a.txt','fingerprint':'ofp1','proposed_content_id':'c1','proposed_content_fingerprint':'cfp1','precondition_id':'p1','precondition_fingerprint':'pfp1','expected_before_fingerprint':'missing','proposed_after_fingerprint':'afp1'}, {'operation_id':'op2','operation_type':'replace_text_file','target_relative_path':'src/b.txt','fingerprint':'ofp2','proposed_content_id':'c2','proposed_content_fingerprint':'cfp2','precondition_id':'p2','precondition_fingerprint':'pfp2','expected_before_fingerprint':'bfp','proposed_after_fingerprint':'afp2'}]
 prop={'schema':'zero.engineering.change_proposal.v1','proposal_id':'prop1','fingerprint':'propfp','status':'proposed','workspace_id':'ws1','workspace_evidence':{'workspace_root_fingerprint':'rootfp'},'execution_session_id':'sess1','scope_policy':{'scope_policy_id':'scope1','allowed_path_prefixes':['src']},'authority_constraints':['bounded'], 'operations':ops,'contents':[{'content_id':'c1','content_sha256':'cfp1','content_byte_count':5},{'content_id':'c2','content_sha256':'cfp2','content_byte_count':5}], 'diffs':[{'target_relative_path':'src/a.txt','fingerprint':'dfp1'},{'target_relative_path':'src/b.txt','fingerprint':'dfp2'}], 'preconditions':[{'fingerprint':'pfp1'},{'fingerprint':'pfp2'}], 'mutation_authorized':False,'mutation_performed':False,'patch_applied':False,'filesystem_write_performed':False,'git_invoked':False,'shell_invoked':False,'runtime_kernel_invoked':False}
 val={'status':'valid','proposal_id':'prop1','validation_id':'val1','fingerprint':'valfp'}; saf={'status':'approved_for_handoff','proposal_id':'prop1','safety_review_id':'safe1','fingerprint':'safefp'}; ver={'status':'verified','proposal_id':'prop1','verification_id':'ver1','fingerprint':'verfp'}; clo={'status':'closed','proposal_id':'prop1','closure_id':'clo1','fingerprint':'clofp','operator_approval_obtained':False,'mutation_authorized':False,'mutation_prepared':False,'mutation_performed':False,'patch_applied':False,'filesystem_write_performed':False,'git_invoked':False,'runtime_kernel_invoked':False}; hand={'status':'handed_off','proposal_id':'prop1','approval_handoff_id':'hand1','fingerprint':'handfp','workspace_root_fingerprint':'rootfp','operator_approval_obtained':False,'mutation_authorized':False,'mutation_prepared':False,'mutation_performed':False,'patch_applied':False,'filesystem_write_performed':False,'git_invoked':False,'runtime_kernel_invoked':False}
 return {'proposal':prop,'validation':val,'safety_review':saf,'verification':ver,'closure':clo,'approval_handoff':hand}
def valid_payload(decision='approved'):
 p=proposal_bundle(); p.update({'approval_policy':{'allowed_operator_identity_classes':['employee'],'maximum_approved_operations':5,'maximum_approved_files':5,'maximum_approved_content_bytes':100,'maximum_approved_diff_entries':100,'allowed_path_prefixes':['src'],'allowed_authority_constraints':['bounded'],'partial_approval_allowed':True,'operator_reason_required':True,'automated_approval_allowed':False,'self_approval_allowed':False,'delegation_allowed':False,'multi_party_approval_required':False},'requested_operation_ids':['op1','op2'],'requested_scope':['src'],'requested_authority_constraints':['bounded'],'request_reason_code':'review','operator_identity_class_requirement':'employee','decision':{'operator_id':'operator-1','operator_identity_class':'employee','decision':decision,'decision_reason_code':'reviewed','approved_operation_ids':['op1','op2'] if decision=='approved' else (['op1'] if decision=='partially_approved' else []),'approved_target_path_fingerprints':['469fe3c1e59ca84f28b2c356350bab123862b1a5d41cbdd75b9ceb2fd5c0538b'] if decision=='partially_approved' else [],'approved_content_fingerprints':['cfp1'] if decision=='partially_approved' else [],'approved_diff_fingerprints':['dfp1'] if decision=='partially_approved' else [],'approved_scope':['src'],'approved_authority_constraints':['bounded'],'decision_sequence':1,'decision_nonce':'n','automated_decision':False},'preparation_policy':{'maximum_prepared_operations':5,'maximum_prepared_files':5,'maximum_prepared_content_bytes':100,'maximum_prepared_diff_entries':100,'allowed_prepared_operation_classes':['create_text_file','replace_text_file','delete_file','create_directory','rename_path'],'allowed_path_prefixes':['src'],'token_use_limit':1,'allow_symlink':False,'allow_binary':False,'allow_git':False,'allow_shell':False,'allow_external_tools':False},'preparation_request':{'workspace_root_fingerprint':'rootfp'}})
 return p
def chain(decision='approved'):
 return pipeline(valid_payload(decision))
