from cli.zero_engineering_mutation_transaction import pipeline
from core.engineering.engineering_mutation_transaction_common import fingerprint

def upstream():
    ops=[{'operation_id':'op1','operation_type':'replace_text_file','operation_fingerprint':'ofp1','target_path_fingerprint':'tfp1','content_fingerprint':'cfp1','diff_fingerprint':'dfp1','precondition_fingerprint':'pfp1','expected_before_fingerprint':'bfp1','expected_after_fingerprint':'afp1','content_byte_count':5,'diff_entry_count':1},{'operation_id':'op2','operation_type':'create_text_file','operation_fingerprint':'ofp2','target_path_fingerprint':'tfp2','content_fingerprint':'cfp2','diff_fingerprint':'dfp2','precondition_fingerprint':'pfp2','expected_before_fingerprint':None,'expected_after_fingerprint':'afp2','content_byte_count':4,'diff_entry_count':1}]
    pkg={'schema':'zero.engineering.mutation_package.v1','status':'packaged','mutation_package_id':'mpkg1','fingerprint':'mpkgfp','workspace_id':'ws1','workspace_root_fingerprint':'rootfp','execution_session_id':'sess1','operations':ops}
    return {'mutation_handoff':{'schema':'zero.engineering.mutation_handoff.v1','status':'handed_off','handoff_id':'mh1','fingerprint':'mhfp','mutation_package_id':'mpkg1','workspace_id':'ws1','workspace_root_fingerprint':'rootfp','operator_approval_obtained':True,'preparation_completed':True,'mutation_authorized':False,'mutation_executor_invoked':False,'mutation_performed':False,'filesystem_write_performed':False,'patch_applied':False,'git_invoked':False,'shell_invoked':False,'runtime_kernel_invoked':False,'token_consumed':False},'preparation_closure':{'schema':'zero.engineering.mutation_preparation_closure.v1','status':'closed','closure_id':'pclo1','fingerprint':'pclofp','mutation_performed':False},'readiness_verification':{'schema':'zero.engineering.mutation_readiness_verification.v1','status':'ready','readiness_id':'ready1','fingerprint':'readyfp','mutation_performed':False},'preparation_token':{'schema':'zero.engineering.mutation_preparation_token.v1','status':'issued','token_id':'ptok1','fingerprint':'ptokfp','mutation_package_id':'mpkg1','token_purpose':'workspace_mutation_preparation_handoff','use_limit':1,'token_consumed':False,'mutation_performed':False},'token_eligibility':{'schema':'zero.engineering.mutation_preparation_token_eligibility.v1','status':'eligible','eligibility_id':'ptelig1','fingerprint':'pteligfp'},'mutation_package':pkg,'package_validation':{'schema':'zero.engineering.mutation_package_validation.v1','status':'valid','validation_id':'mpval1','fingerprint':'mpvalfp','mutation_package_id':'mpkg1'},'approval_verification':{'schema':'zero.engineering.operator_approval_verification.v1','status':'verified','verification_id':'aver1','fingerprint':'averfp'},'operator_decision':{'schema':'zero.engineering.operator_approval_decision.v1','status':'approved','decision_id':'odec1','fingerprint':'odecfp'},'approved_scope':{'schema':'zero.engineering.operator_approved_scope.v1','status':'sealed','approved_scope_id':'oscope1','fingerprint':'oscopefp','scope_constraints':['src/'],'authority_constraints':['workspace_mutation_prepare']}}

def valid_payload(**kw):
    p={'upstream':upstream(),'authorization_policy':{'partial_authorization_allowed':True},'authorization_decision':{'authorizer_id':'human-a','authorizer_identity_class':'human_operator','decision':'authorized','decision_reason_code':'reviewed','authorized_operation_ids':['op1','op2'],'decision_sequence':1,'decision_nonce':'nonce-1'},'transaction_policy':{}}
    p.update(kw); return p

def chain(**kw): return pipeline(valid_payload(**kw))
