from core.engineering.engineering_change_intent import build_change_intent
from core.engineering.engineering_change_workspace_evidence import bind_workspace_evidence
from core.engineering.engineering_change_scope_policy import build_change_scope_policy
from core.engineering.engineering_change_target_admission import admit_change_target
from core.engineering.engineering_change_file_precondition import build_file_precondition
from core.engineering.engineering_change_content import build_proposed_content
from core.engineering.engineering_change_operation import build_change_operation
from core.engineering.engineering_change_diff import build_change_diff
from core.engineering.engineering_change_proposal import assemble_change_proposal
from core.engineering.engineering_change_proposal_validation import validate_change_proposal
from core.engineering.engineering_change_proposal_safety_review import review_change_proposal_safety
from core.engineering.engineering_change_proposal_verification import verify_change_proposal
from core.engineering.engineering_change_proposal_evidence import build_change_proposal_evidence
from core.engineering.engineering_change_proposal_approval_handoff import build_approval_handoff
from core.engineering.engineering_change_proposal_closure import close_change_proposal

def policy_payload():
 return {'allowed_operation_classes':['create_text_file','replace_text_file','delete_file','create_directory','rename_path'],'allowed_relative_path_prefixes':['src','docs'],'maximum_affected_files':5,'maximum_created_files':3,'maximum_replaced_files':3,'maximum_delete_proposals':2,'maximum_rename_proposals':2,'maximum_directory_proposals':2,'maximum_content_bytes_per_file':2000,'maximum_total_proposed_content_bytes':4000,'maximum_diff_entries':10,'maximum_line_length':120,'maximum_line_count':50,'allow_binary':False,'allow_symlink_targets':False,'allow_hidden_targets':False,'require_existing_evidence_for_replace':True,'require_existing_evidence_for_delete':True,'require_missing_evidence_for_create':True,'allow_scope_narrowing':True,'authority_constraints':['governance_only']}
def upstream(path='src/a.txt', kind='file', sha='b6a98d9ce03bf6a563365bbb267770f6cdd0b6848d345e6e3119d16310c67f2a'):
 return {'closure':{'schema':'zero.engineering.runtime_workspace_execution_closure.v1','closure_status':'closed','closure_id':'cls1','fingerprint':'cfp'},'verification':{'schema':'zero.engineering.runtime_workspace_execution_verification.v1','verification_status':'verified','verification_id':'ver1','fingerprint':'vfp'},'result':{'schema':'zero.engineering.runtime_workspace_execution_result.v1','result_status':'succeeded','result_id':'res1','fingerprint':'rfp','workspace_id':'ws1','workspace_root_fingerprint':'rootfp','relative_path':path,'path_kind':kind,'size_bytes':5,'content_sha256':sha,'execution_session_id':'sess1','adapter_id':'zero.engineering.read_only_workspace','adapter_version':'1','operation':'read_text','filesystem_mutation_performed':False},'observation_output':{'schema':'zero.engineering.runtime_workspace_observation_output.v1','observation_output_id':'out1','fingerprint':'ofp','relative_path':path,'path_kind':kind,'size_bytes':5,'content_sha256':sha},'root_admission':{'schema':'zero.engineering.runtime_workspace_root_admission.v1','workspace_id':'ws1','workspace_root_fingerprint':'rootfp'},'read_scope':{'schema':'zero.engineering.runtime_workspace_read_scope.v1','read_scope_id':'scope1','fingerprint':'sfp'},'path_resolution':{'schema':'zero.engineering.runtime_workspace_path_resolution.v1','path_resolution_status':'resolved','path_resolution_id':'path1','fingerprint':'pfp'}}
def chain():
 pol=build_change_scope_policy(policy_payload()); ev=bind_workspace_evidence(upstream()); intent=build_change_intent({'intent_category':'replace_text_file','summary_code':'demo','requested_target_paths':['src/a.txt'],'requested_operation_classes':['replace_text_file'],'expected_goal_identifiers':['g1'],'expected_validation_identifiers':['v1'],'maximum_affected_files':1,'maximum_proposed_content_bytes':100,'maximum_diff_entries':5,'authority_constraints':['governance_only'],'scope_constraints':['src']}); adm=admit_change_target('src/a.txt',pol); pre=build_file_precondition({'relative_path':'src/a.txt','conditions':{'expected_regular_file':True,'expected_sha256':ev['observed_content_sha256'],'expected_size_bytes':5},'expected_workspace_id':'ws1','expected_workspace_root_fingerprint':'rootfp'},ev); cont=build_proposed_content({'content':'hello\nworld\n'},pol); op=build_change_operation({'operation_type':'replace_text_file','target_relative_path':'src/a.txt','target_admission_id':adm['target_admission_id'],'target_admission_fingerprint':adm['fingerprint'],'precondition_id':pre['precondition_id'],'precondition_fingerprint':pre['fingerprint'],'proposed_content_id':cont['content_id'],'proposed_content_fingerprint':cont['fingerprint'],'expected_before_fingerprint':ev['observed_content_sha256'],'proposed_after_fingerprint':cont['content_sha256']}); diff=build_change_diff({'operation_type':'replace_text_file','target_relative_path':'src/a.txt','before_content':'hello','after_content':'hello\nworld\n','after_sha256':cont['content_sha256']},pol); prop=assemble_change_proposal({'intent':intent,'workspace_evidence':ev,'target_admissions':[adm],'scope_policy':pol,'preconditions':[pre],'operations':[op],'contents':[cont],'diffs':[diff],'authority_constraints':['governance_only']}); val=validate_change_proposal(prop); saf=review_change_proposal_safety(prop,val); ver=verify_change_proposal(prop,val,saf); evidence=build_change_proposal_evidence(prop,val,saf,ver); hand=build_approval_handoff(prop,ver,saf); approval_handoff=hand; clo=close_change_proposal(prop,val,saf,ver,hand); return locals()
