from __future__ import annotations
import copy
from hashlib import sha256
from pathlib import Path
from core.runtime.runtime_active_execution_authorization import RUNTIME_ACTIVE_AUTHORIZATION_REQUEST_CONTRACT
from core.runtime.runtime_executor_admission_token import RUNTIME_OPERATOR_EXECUTION_REQUEST_CONTRACT
from core.runtime.runtime_execution_plan_review_gate import RUNTIME_EXECUTION_PLAN_OPERATOR_REVIEW_CONTRACT
from core.runtime.runtime_goal_executor import create_goal_execution_request
from core.runtime.runtime_mission_orchestrator import advance_mission
from core.runtime.runtime_operator_session import fingerprint,load_runtime_session
from core.runtime.runtime_session_queue import load_scheduler_state,save_scheduler_state
from core.runtime.runtime_session_scheduler import submit_operator_input
from core.runtime.runtime_transactional_active_execution import BUNDLE_CONTRACT,REQUEST_CONTRACT
from core.runtime.runtime_worker_service import create_worker_state,run_worker_iteration,save_worker_state
from tests.test_runtime_natural_mission_e2e import NOW,EXPIRES,_confirm,_drive_session,_envelope,_security,_setup

def _to_candidate(scheduler,target,workspace,session):
 state,session=submit_operator_input(load_scheduler_state(scheduler),_envelope(session,"proposal_approval",{"decision":"approve","expires_at":EXPIRES},1),target_root=target,workspace_root=workspace,now=NOW);save_scheduler_state(state,scheduler);plan=session["artifacts"]["execution_plan"]
 review={"contract":RUNTIME_EXECUTION_PLAN_OPERATOR_REVIEW_CONTRACT,"review_id":"executor-e2e-review","plan_id":plan["plan_id"],"operator_id":"operator","decision":"approved","reviewed_at":NOW,"expires_at":EXPIRES,"acknowledged_scope":copy.deepcopy(plan["allowed_files"]),"acknowledged_constraints":copy.deepcopy(plan["execution_constraints"]),"acknowledged_security_invariants":_security(plan),"acknowledged_evidence_requirements":copy.deepcopy(plan["evidence_requirements"])}
 state,session=submit_operator_input(load_scheduler_state(scheduler),_envelope(session,"execution_plan_review",review,2),target_root=target,workspace_root=workspace,now=NOW);save_scheduler_state(state,scheduler);reviewed=session["artifacts"]["plan_review"]
 controlled={"contract":RUNTIME_OPERATOR_EXECUTION_REQUEST_CONTRACT,"request_id":"executor-e2e-controlled","review_result_id":reviewed["result_id"],"plan_id":plan["plan_id"],"operator_id":"operator","requested_mode":"controlled_dry_run","requested_at":NOW,"expires_at":EXPIRES,"acknowledged_scope":copy.deepcopy(plan["allowed_files"]),"acknowledged_dry_run":True,"acknowledged_no_file_mutation":True}
 state,session=submit_operator_input(load_scheduler_state(scheduler),_envelope(session,"controlled_execution_request",controlled,3),target_root=target,workspace_root=workspace,now=NOW);save_scheduler_state(state,scheduler);activation=session["artifacts"]["controlled_execution_result"]
 authorization={"contract":RUNTIME_ACTIVE_AUTHORIZATION_REQUEST_CONTRACT,"authorization_id":"executor-e2e-auth","controlled_execution_result_id":activation["activation_id"],"token_id":activation["token"]["token_id"],"plan_id":activation["plan_id"],"review_result_id":activation["review_result_id"],"operator_execution_request_id":activation["operator_request_id"],"operator_id":activation["token"]["operator_id"],"decision":"authorized","authorized_mode":"prepared_active_execution","authorized_at":NOW,"expires_at":EXPIRES,"acknowledged_scope":copy.deepcopy(activation["token"]["allowed_files"]),"acknowledged_snapshot_manifest_id":activation["snapshot_manifest"]["manifest_id"],"acknowledged_validation_evidence_id":activation["validation_evidence"]["validation_evidence_id"],"acknowledged_rollback_state_id":activation["rollback_prepared_state"]["rollback_state_id"],"acknowledged_risks":["manual_active_boundary_required"],"acknowledged_no_automatic_commit":True,"acknowledged_manual_rollback_authority":True}
 state,session=submit_operator_input(load_scheduler_state(scheduler),_envelope(session,"active_execution_authorization",authorization,4),target_root=target,workspace_root=workspace,now=NOW);save_scheduler_state(state,scheduler);return session

def _submit_executor_result(scheduler,target,workspace,session,result):
 auth=session["artifacts"]["active_authorization_result"];scope=auth["authorized_scope"];files=[]
 for item in result["candidate_files"]:
  content=Path(item["candidate_reference"]).read_text(encoding="utf-8");files.append({"relative_path":item["relative_path"],"operation":item["operation"],"expected_pre_state":{"expected_exists":item["expected_original_sha256"] is not None,"expected_sha256":item["expected_original_sha256"],"expected_size":item["expected_original_size"]},"candidate_content_encoding":"utf-8","candidate_content":content,"candidate_content_hash":item["candidate_sha256"],"maximum_size":100000,"validation_requirements":[]})
 bundle={"contract":BUNDLE_CONTRACT,"candidate_bundle_id":"executor-e2e-bundle","plan_id":auth["plan_id"],"authorization_result_id":auth["authorization_result_id"],"target_root_identity":session["target_root_identity"],"scope_fingerprint":fingerprint(scope),"created_at":NOW,"expires_at":EXPIRES,"files":files,"validation_profile_id":"python_compile","project_validation_required":True,"approved_test_files":[],"validation_scope":[]};bundle["bundle_fingerprint"]=fingerprint(bundle)
 state,session=submit_operator_input(load_scheduler_state(scheduler),_envelope(session,"candidate_bundle",bundle,5),target_root=target,workspace_root=workspace,now=NOW);save_scheduler_state(state,scheduler)
 invocation={"contract":REQUEST_CONTRACT,"invocation_request_id":"executor-e2e-invoke","authorization_result_id":auth["authorization_result_id"],"authorization_id":auth["authorization_id"],"controlled_execution_result_id":auth["controlled_execution_result_id"],"token_id":auth["token_id"],"plan_id":auth["plan_id"],"review_result_id":auth["review_result_id"],"operator_id":auth["operator_id"],"requested_mode":"transactional_active_execution","requested_at":NOW,"expires_at":EXPIRES,"target_root_identity":session["target_root_identity"],"acknowledged_scope":scope,"candidate_bundle_id":bundle["candidate_bundle_id"],"candidate_bundle_fingerprint":bundle["bundle_fingerprint"],"validation_profile_id":"python_compile","acknowledged_transactional_execution":True,"acknowledged_automatic_rollback":True,"acknowledged_no_git_commit":True,"acknowledged_no_scope_expansion":True}
 state,session=submit_operator_input(load_scheduler_state(scheduler),_envelope(session,"transactional_invocation",invocation,6),target_root=target,workspace_root=workspace,now=NOW);save_scheduler_state(state,scheduler);return session

def test_worker_executor_candidate_then_existing_transaction_commit_and_projection(tmp_path):
 target,workspace,mission_path,scheduler,natural,planned,mission=_setup(tmp_path,"app.py");mission=_confirm(mission,planned);config={"target_root":target,"workspace_root":workspace};mission=advance_mission(mission,scheduler_state=scheduler,now=NOW,runtime_config=config);first=mission["waiting_goal_ids"][0];_drive_session(scheduler,target,workspace,load_runtime_session(mission["goals"][first]["session_path"],now=NOW),content=(target/"app.py").read_text());mission=advance_mission(mission,scheduler_state=scheduler,now=NOW,runtime_config=config);goal_id=mission["waiting_goal_ids"][0];session=_to_candidate(scheduler,target,workspace,load_runtime_session(mission["goals"][goal_id]["session_path"],now=NOW));before=(target/"app.py").read_bytes()
 worker_path=tmp_path/"worker.json";save_worker_state(create_worker_state(scheduler_state_path=scheduler,worker_state_path=worker_path,worker_name="executor-worker",target_root=target,now=NOW),worker_path)
 request={session["session_id"]:{"goal":mission["goals"][goal_id],"operator_context":{"append_text":"# ZERO executor e2e\n"},"artifact_root":tmp_path/"candidates"}}
 worker=run_worker_iteration(scheduler_state_path=scheduler,worker_state_path=worker_path,worker_name="executor-worker",target_root=target,workspace_root=workspace,now=NOW,runtime_config={"goal_execution_requests":request});result=worker["pending_executor_results"][session["session_id"]]
 assert result["execution_status"]=="candidate_ready" and (target/"app.py").read_bytes()==before and session["session_status"]=="waiting_for_candidate_bundle"
 session=_submit_executor_result(scheduler,target,workspace,session,result);assert session["artifacts"]["transaction_result"]["transaction_status"]=="committed" and b"# ZERO executor e2e" in (target/"app.py").read_bytes()
 mission=advance_mission(mission,scheduler_state=scheduler,now=NOW,runtime_config=config);assert mission["goals"][goal_id]["goal_status"]=="completed" and mission["goals"][goal_id]["result_summary"]["validation_status"] is not None

def test_executor_invalid_python_rolls_back_and_can_request_replan(tmp_path):
 target,workspace,mission_path,scheduler,natural,planned,mission=_setup(tmp_path,"app.py");mission=_confirm(mission,planned);config={"target_root":target,"workspace_root":workspace};mission=advance_mission(mission,scheduler_state=scheduler,now=NOW,runtime_config=config);first=mission["waiting_goal_ids"][0];_drive_session(scheduler,target,workspace,load_runtime_session(mission["goals"][first]["session_path"],now=NOW),content=(target/"app.py").read_text());mission=advance_mission(mission,scheduler_state=scheduler,now=NOW,runtime_config=config);goal_id=mission["waiting_goal_ids"][0];session=_to_candidate(scheduler,target,workspace,load_runtime_session(mission["goals"][goal_id]["session_path"],now=NOW));before=(target/"app.py").read_bytes()
 req=create_goal_execution_request(mission["goals"][goal_id],session,operator_context={"replacement_text":"def broken(:\n"},now=NOW)
 from core.runtime.runtime_goal_executor import execute_goal
 result=execute_goal(req,workspace_root=target,artifact_root=tmp_path/"bad-candidates",now=NOW);assert result["execution_status"]=="validation_failed" and (target/"app.py").read_bytes()==before
 session=_submit_executor_result(scheduler,target,workspace,session,result);assert session["artifacts"]["transaction_result"]["transaction_status"]=="rolled_back" and (target/"app.py").read_bytes()==before
 mission=advance_mission(mission,scheduler_state=scheduler,now=NOW,runtime_config=config);envelope={"contract":"zero.runtime.mission_input.v1","mission_id":mission["mission_id"],"input_id":"executor-request-replan","input_type":"request_replan","operator_id":"operator","submitted_at":NOW,"payload":{"operator_instruction":"use sealed executor validation failure","allowed_revision_scope":["app.py"]}}
 from core.runtime.runtime_mission_orchestrator import submit_mission_input
 mission=submit_mission_input(mission,envelope,now=NOW);assert mission["mission_status"]=="waiting_for_replan_confirmation" and mission["replanning_history"][-1]["request"]["failure_evidence_summaries"]
