from core.engineering.engineering_runtime_adapter_activation_authorization_policy import *
def test_policy_frozen_deterministic():
 p=build_default_runtime_adapter_activation_authorization_policy(); assert validate_runtime_adapter_activation_authorization_policy(p).valid; assert build_default_runtime_adapter_activation_authorization_policy()==p
def test_policy_invalid_mapping():
 p=build_default_runtime_adapter_activation_authorization_policy(); p['frozen']=False; assert not validate_runtime_adapter_activation_authorization_policy(p).valid
