from core.engineering.engineering_runtime_adapter_preparation_request import *
from tests.runtime_adapter_preparation_fixtures import request,AUTH
def test_valid_request_deterministic():
 r,_,_,_=request(); assert r==request()[0]; assert validate_runtime_adapter_preparation_request(r).valid; assert inspect_runtime_adapter_preparation_request(r)['valid']
def test_malformed_and_linkage_values():
 assert not validate_runtime_adapter_preparation_request({}).valid
 for kw in ({'operation':{}},{'operation':{'operation_type':'*'}},{'scope':{'files':['a','b']}},{'scope':{'files':['*']}},{'inputs':{}},{'output':{}},{'resources':{}},{'resources':{'cpu':-1}},{'timeout':{}},{'timeout':{'seconds':0,'finite':True,'perpetual':False}},{'timeout':{'seconds':-1,'finite':True,'perpetual':False}},{'timeout':{'seconds':1,'finite':False,'perpetual':True}},{'environment':{}},{'auth':{**AUTH,'non_transferable':False}},{'auth':{**AUTH,'non_reusable':False}},{'auth':{**AUTH,'scope_bound':False}},{'auth':{**AUTH,'perpetual':True}},{'auth':{**AUTH,'passive':False}},{'auth':{**AUTH,'consumed':True}},{'auth':{**AUTH,'closed':True}},{'auth':{**AUTH,'unrestricted':True}},{'auth':{**AUTH,'scope':{'files':['b']}}},{'operation':{'operation_type':'observe','shell':'x'}},{'operation':{'operation_type':'observe','script':'x'}},{'operation':{'operation_type':'observe','source_code':'x'}},{'operation':{'operation_type':'observe','executable':'x'}},{'operation':{'operation_type':'observe','module_path':'x'}},{'operation':{'operation_type':'observe','callable':'x'}},{'operation':{'operation_type':'observe','patch':'x'}},{'inputs':{'api_key':'x'}},{'inputs':{'private_key':'x'}},{'inputs':{'bearer':'x'}},{'inputs':{'environment_secrets':'x'}}): assert not validate_runtime_adapter_preparation_request(request(**kw)[0]).valid
def test_admission_not_admitted():
 r,adm,h,s=request(); bad={**adm,'admission_status':'not_admitted'}; assert 'admission_not_admitted' in validate_runtime_adapter_preparation_request(request(admission=bad)[0]).errors
