from typing import Any, Dict, List, Optional


class Replanner:
    """
    ZERO Replanner
    """

    def __init__(self, llm_client: Any = None) -> None:
        self.llm_client = llm_client

    def should_replan(self, verification_report: Dict[str, Any]) -> Dict[str, Any]:
        if not isinstance(verification_report, dict):
            return {
                "ok": False,
                "should_replan": False,
                "summary": "Invalid verification report.",
                "failed_steps": [],
            }

        failed_steps = self._extract_failed_steps(verification_report)

        return {
            "ok": True,
            "should_replan": len(failed_steps) > 0,
            "summary": f"Failed step count: {len(failed_steps)}",
            "failed_steps": failed_steps,
        }

    def create_replan(
        self,
        user_input: str,
        original_plan: Dict[str, Any],
        step_results: List[Dict[str, Any]],
        verification_report: Dict[str, Any],
    ) -> Dict[str, Any]:
        decision = self.should_replan(verification_report)
        failed_steps = decision.get("failed_steps", [])

        if not failed_steps:
            return {
                "ok": True,
                "replanned": False,
                "summary": "No failed step. Replan not needed.",
                "plan": {
                    "task": "no_replan_needed",
                    "mode": "plan",
                    "summary": "No replan needed.",
                    "steps": [],
                    "meta": {
                        "source": "replanner",
                        "step_count": 0
                    }
                }
            }

        new_steps: List[Dict[str, Any]] = []

        for failed in failed_steps:
            rebuilt = self._build_recovery_step(failed, user_input, original_plan, step_results)
            if rebuilt is not None:
                new_steps.append(rebuilt)

        return {
            "ok": True,
            "replanned": len(new_steps) > 0,
            "summary": f"Generated recovery plan with {len(new_steps)} step(s).",
            "plan": {
                "task": "recovery_plan",
                "mode": "plan",
                "summary": "Recovery plan generated after verification failure.",
                "steps": new_steps,
                "meta": {
                    "source": "replanner",
                    "step_count": len(new_steps)
                }
            }
        }

    def _extract_failed_steps(self, verification_report: Dict[str, Any]) -> List[Dict[str, Any]]:
        results = verification_report.get("results", [])
        failed_steps: List[Dict[str, Any]] = []

        if not isinstance(results, list):
            return failed_steps

        for item in results:
            if isinstance(item, dict) and item.get("ok") is False:
                failed_steps.append(item)

        return failed_steps

    def _build_recovery_step(
        self,
        failed_verification: Dict[str, Any],
        user_input: str,
        original_plan: Dict[str, Any],
        step_results: List[Dict[str, Any]],
    ) -> Optional[Dict[str, Any]]:
        step_id = failed_verification.get("step_id")
        tool = str(failed_verification.get("tool", "")).strip()

        original_step = self._find_original_step(step_id, step_results)
        if not original_step:
            return None

        args = original_step.get("args", {}) or {}

        if tool == "file":
            return self._recover_file_step(step_id, args)

        if tool == "command":
            return self._recover_command_step(step_id, args)

        if tool == "web_search":
            return self._recover_web_search_step(step_id, args, user_input)

        return {
            "id": step_id,
            "title": f"Retry {tool or 'step'}",
            "tool": tool or original_step.get("tool", "respond"),
            "args": args,
            "reason": "Fallback retry generated by replanner."
        }

    def _find_original_step(self, step_id: Any, step_results: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        for item in step_results:
            if not isinstance(item, dict):
                continue
            if item.get("step_id") == step_id:
                return item
        return None

    def _recover_file_step(self, step_id: Any, args: Dict[str, Any]) -> Dict[str, Any]:
        path = str(args.get("path", "")).strip()
        action = str(args.get("action", "")).strip().lower()
        content = args.get("content", "")

        if not path:
            path = "recovered_output.txt"

        if action not in {"write", "read"}:
            action = "write"

        return {
            "id": step_id,
            "title": f"Retry file {action}",
            "tool": "file",
            "args": {
                "action": action,
                "path": path,
                "content": content if action == "write" else args.get("content", "")
            },
            "reason": "Previous file step failed verification, retry with normalized file args."
        }

    def _recover_command_step(self, step_id: Any, args: Dict[str, Any]) -> Dict[str, Any]:
        command = str(args.get("command", "")).strip()

        if not command:
            command = "python --version"

        return {
            "id": step_id,
            "title": "Retry command",
            "tool": "command",
            "args": {
                "command": command
            },
            "reason": "Previous command step failed verification, retry same command."
        }

    def _recover_web_search_step(self, step_id: Any, args: Dict[str, Any], user_input: str) -> Dict[str, Any]:
        query = str(args.get("query", "")).strip()

        if not query:
            query = user_input

        return {
            "id": step_id,
            "title": "Retry web search",
            "tool": "web_search",
            "args": {
                "query": query
            },
            "reason": "Previous web search step failed verification, retry search query."
        }