from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_approval_common import ValidationResult,approval_artifact,validate_approval_artifact,validate_review_closure
SCHEMA="zero.engineering.approval_intake.v1";ID_KEY="approval_intake_id";PREFIX="engineering-approval-intake-";FIELDS={"proposal_review_closure_id","proposal_review_closure_fingerprint","engineering_proposal_review_id","proposal_closure_id","engineering_proposal_id","planning_closure_id","repository_identity","analyzed_revision","approval_objective","requested_decision","evidence_references","constraints","authority_declarations"}
AUTH={"approval_authority":"not_granted","authorization_authority":"not_granted","execution_authority":"not_granted","mutation_authority":"not_granted"}
def build_engineering_approval_intake(c:Mapping[str,Any],intent:Mapping[str,Any]|None=None)->dict[str,Any]:
 i=dict(intent or {});valid=validate_review_closure(c).valid;requested=i.get("requested_decision","approve");valid=valid and requested in {"approve","reject"} and not any(i.get(k) not in (None,False,"not_granted") for k in AUTH)
 p={"proposal_review_closure_id":c.get("proposal_review_closure_id"),"proposal_review_closure_fingerprint":c.get("fingerprint"),"engineering_proposal_review_id":c.get("engineering_proposal_review_id"),"proposal_closure_id":c.get("proposal_closure_id"),"engineering_proposal_id":c.get("engineering_proposal_id"),"planning_closure_id":c.get("planning_closure_id"),"repository_identity":c.get("repository_identity"),"analyzed_revision":c.get("analyzed_revision"),"approval_objective":i.get("approval_objective","evaluate governed engineering approval"),"requested_decision":requested,"evidence_references":sorted(set(i.get("evidence_references",[]))),"constraints":sorted(set(i.get("constraints",[]))),"authority_declarations":dict(AUTH)};return approval_artifact(SCHEMA,"accepted" if valid else "invalid",p,ID_KEY,PREFIX)
def validate_engineering_approval_intake(v:Any)->ValidationResult:return validate_approval_artifact(v,schema=SCHEMA,statuses={"accepted","blocked","invalid","insufficient_evidence"},id_key=ID_KEY,prefix=PREFIX,fields=FIELDS)
__all__=["AUTH","build_engineering_approval_intake","validate_engineering_approval_intake"]
