from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_eligibility_common import *
from core.engineering.engineering_runtime_adapter_preparation_review_handoff import validate_runtime_adapter_preparation_review_handoff
SCHEMA='zero.engineering.runtime_adapter_activation_eligibility_request.v1';ID='activation_eligibility_request_id';PREFIX='engineering-runtime-adapter-activation-eligibility-request-'
FIELDS={'preparation_review_handoff_id','preparation_review_handoff_fingerprint','preparation_review_id','preparation_review_fingerprint','preparation_review_status','preparation_review_closure_id','preparation_review_closure_fingerprint','preparation_review_closure_status','preparation_id','preparation_fingerprint','preparation_closure_id','preparation_closure_fingerprint','invocation_descriptor_id','invocation_descriptor_fingerprint','runtime_adapter_admission_id','runtime_adapter_admission_fingerprint','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','approved_scope','requested_activation_scope','activation_constraints','resource_constraints','timeout_constraints','environment_constraints','authority_reference','authority_constraints','request_context','request_input_fingerprint'}
def build_runtime_adapter_activation_eligibility_request(handoff:Mapping[str,Any],review_closure:Mapping[str,Any],requested_activation_scope:Any,activation_constraints:Mapping[str,Any],resource_constraints:Mapping[str,Any],timeout_constraints:Mapping[str,Any],environment_constraints:Mapping[str,Any],request_context:Mapping[str,Any])->dict[str,Any]:
 p={'schema':SCHEMA,'preparation_review_handoff_id':handoff.get('review_handoff_id'),'preparation_review_handoff_fingerprint':handoff.get('fingerprint'),'preparation_review_id':handoff.get('review_id'),'preparation_review_fingerprint':handoff.get('review_fingerprint'),'preparation_review_status':handoff.get('review_status'),'preparation_review_closure_id':review_closure.get('review_closure_id'),'preparation_review_closure_fingerprint':review_closure.get('fingerprint'),'preparation_review_closure_status':review_closure.get('package_status'),'preparation_id':handoff.get('preparation_id'),'preparation_fingerprint':handoff.get('preparation_fingerprint'),'preparation_closure_id':handoff.get('preparation_closure_id'),'preparation_closure_fingerprint':handoff.get('preparation_closure_fingerprint'),'invocation_descriptor_id':handoff.get('invocation_descriptor_id'),'invocation_descriptor_fingerprint':handoff.get('invocation_descriptor_fingerprint'),'runtime_adapter_admission_id':handoff.get('runtime_adapter_admission_id'),'runtime_adapter_admission_fingerprint':handoff.get('runtime_adapter_admission_fingerprint'),'engineering_runtime_handoff_id':handoff.get('engineering_runtime_handoff_id'),'execution_session_id':handoff.get('execution_session_id'),'adapter_id':handoff.get('adapter_id'),'adapter_version':handoff.get('adapter_version'),'approved_scope':handoff.get('approved_scope'),'requested_activation_scope':requested_activation_scope,'activation_constraints':dict(activation_constraints),'resource_constraints':dict(resource_constraints),'timeout_constraints':dict(timeout_constraints),'environment_constraints':dict(environment_constraints),'authority_reference':handoff.get('authority_reference'),'authority_constraints':handoff.get('authority_constraints'),'request_context':dict(request_context),'request_input_fingerprint':canonical_fingerprint({'handoff':handoff,'review_closure':review_closure,'requested_activation_scope':requested_activation_scope,'activation_constraints':activation_constraints,'resource_constraints':resource_constraints,'timeout_constraints':timeout_constraints,'environment_constraints':environment_constraints,'request_context':request_context})}
 return stable_artifact(p,ID,PREFIX)
def validate_runtime_adapter_activation_eligibility_request(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS); e=list(r.errors)
 if isinstance(v,Mapping):
  if v.get('preparation_review_status')!='approved': e.append('review_not_approved')
  if v.get('preparation_review_closure_status')!='closed': e.append('review_closure_not_closed')
  if not canonical_nonempty(v.get('adapter_id')): e.append('adapter_identity_mismatch')
  if not canonical_nonempty(v.get('adapter_version')): e.append('adapter_version_mismatch')
  if contains_wildcard(v.get('requested_activation_scope')) or contains_wildcard(v.get('approved_scope')): e.append('wildcard_scope')
  if not scope_bounded(v.get('requested_activation_scope'),v.get('approved_scope')): e.append('scope_expansion')
  if not activation_constraints_valid(v.get('activation_constraints')): e.append('invalid_activation_constraints')
  if not resources_valid(v.get('resource_constraints')): e.append('unbounded_resources')
  if not timeout_valid(v.get('timeout_constraints')): e.append('invalid_timeout')
  if not environment_valid(v.get('environment_constraints')): e.append('invalid_environment_constraints')
  if not authority_valid(v.get('authority_constraints'),v.get('approved_scope')): e.append('unbounded_authority')
  if not passive_mapping(v.get('request_context')): e.append('malformed_request_context')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_eligibility_request(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_eligibility_request(v); return {'schema':SCHEMA,'valid':r.valid,'reason_codes':list(r.errors)}
