from __future__ import annotations
from typing import Any, Mapping
from core.engineering.engineering_mutation_transaction_common import fingerprint
from core.engineering.engineering_verification_plan import AUTHORITY_BOUNDARY
SCHEMA='zero.engineering.verification_run.v1'; EVIDENCE_SCHEMA='zero.engineering.verification_evidence.v1'
def _fp_body(a): return fingerprint({k:v for k,v in a.items() if k!='fingerprint'})
def build_evidence_item(*, verification_run_id:str, step_id:str, evidence_type:str, status:str, target_references:list[str], exit_code:int|None, stdout_summary:str='', stderr_summary:str='', reason_codes:list[str]|None=None, original_byte_count:int=0, saved_byte_count:int=0, output_truncated:bool=False)->dict[str,Any]:
 body={'schema':EVIDENCE_SCHEMA,'verification_run_id':verification_run_id,'step_id':step_id,'evidence_type':evidence_type,'status':status,'target_references':list(target_references),'exit_code':exit_code,'bounded_stdout_summary':stdout_summary,'bounded_stderr_summary':stderr_summary,'reason_codes':list(reason_codes or []),'original_byte_count':original_byte_count,'saved_byte_count':saved_byte_count,'output_truncated':bool(output_truncated),'deterministic':True,'immutable':True,'authority_boundary':dict(AUTHORITY_BOUNDARY)}; body['evidence_id']='engineering-verification-evidence-'+fingerprint(body)[:24]; body['fingerprint']=_fp_body(body); return body
def build_verification_run(*, plan:Mapping[str,Any], admission:Mapping[str,Any], step_results:list[Mapping[str,Any]], evidence_references:list[Mapping[str,Any]], run_status:str, replay_count:int=0, duration_milliseconds:int=0, output_truncated:bool=False)->dict[str,Any]:
 body={'schema':SCHEMA,'verification_plan_identity':plan.get('verification_plan_id'),'verification_plan_fingerprint':plan.get('fingerprint'),'verification_admission_identity':admission.get('verification_admission_id'),'verification_admission_fingerprint':admission.get('fingerprint'),'execution_session_id':plan.get('execution_session_id'),'execution_result_identity':plan.get('execution_result_identity'),'runner_identity':admission.get('runner_identity'),'run_status':run_status,'status':run_status,'step_results':[dict(x) for x in step_results],'evidence_references':[dict(x) for x in evidence_references],'started_marker':'deterministic-start','finished_marker':'deterministic-finish','duration_milliseconds':int(duration_milliseconds),'output_truncated':bool(output_truncated),'replay_count':int(replay_count),'deterministic':True,'immutable':True,'authority_boundary':dict(AUTHORITY_BOUNDARY)}; body['verification_run_id']='engineering-verification-run-'+fingerprint(body)[:24]; body['fingerprint']=_fp_body(body); return body
