from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_proposal_review_common import ValidationResult,review_artifact,validate_review_artifact
SCHEMA="zero.engineering.proposal_scope_review.v1";ID_KEY="proposal_scope_review_id";PREFIX="engineering-proposal-scope-review-";FIELDS={"review_intake_id","sealed_proposal_scope_linkage","included_scope_review","excluded_scope_review","containment_checks","scope_expansion_findings","frozen_contract_findings","ambiguity_findings","unresolved_scope_issues"}
def build_engineering_proposal_scope_review(intake:Mapping[str,Any],closure:Mapping[str,Any],intent:Mapping[str,Any]|None=None)->dict[str,Any]:
 i=dict(intent or {}); expansions=sorted(set(i.get("scope_expansions",[]))); ambiguity=sorted(set(i.get("scope_ambiguities",[]))); frozen=sorted(set(i.get("frozen_contract_changes",[]))); unresolved=sorted(set(expansions+ambiguity+frozen)); status="blocked" if expansions or frozen else ("changes_required" if ambiguity else ("contained" if intake.get("status")=="accepted" else "invalid"))
 p={"review_intake_id":intake.get("proposal_review_intake_id"),"sealed_proposal_scope_linkage":closure.get("proposal_closure_id"),"included_scope_review":list(intake.get("review_scope",[])),"excluded_scope_review":sorted(set(i.get("excluded_scope",[]))),"containment_checks":{"sealed_boundary_preserved":not expansions,"frozen_contracts_preserved":not frozen},"scope_expansion_findings":expansions,"frozen_contract_findings":frozen,"ambiguity_findings":ambiguity,"unresolved_scope_issues":unresolved};return review_artifact(SCHEMA,status,p,ID_KEY,PREFIX)
def validate_engineering_proposal_scope_review(v:Any)->ValidationResult:return validate_review_artifact(v,schema=SCHEMA,statuses={"contained","changes_required","blocked","invalid","insufficient_evidence"},id_key=ID_KEY,prefix=PREFIX,fields=FIELDS)
__all__=["build_engineering_proposal_scope_review","validate_engineering_proposal_scope_review"]
