from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_token_common import *
from core.engineering.engineering_runtime_adapter_activation_token_eligibility import validate_runtime_adapter_activation_token_eligibility,validate_runtime_adapter_activation_token_eligibility_request
POLICY_SCHEMA='zero.engineering.runtime_adapter_activation_token_preparation_policy.v1';SCHEMA='zero.engineering.runtime_adapter_activation_token_preparation.v1';POLICY_ID='token_preparation_policy_id';ID='token_preparation_id';POLICY_PREFIX='engineering-runtime-adapter-activation-token-preparation-policy-';PREFIX='engineering-runtime-adapter-activation-token-preparation-'
POLICY_FIELDS={'requires_eligible_decision','requires_exact_linkage','requires_bounded_scope','requires_max_uses','requires_passive_constraints','prohibits_wildcard_scope','prohibits_secret_or_executable','prohibits_runtime_activation','invalid_input_fails_closed'}
FIELDS={'token_eligibility_request_id','token_eligibility_request_fingerprint','token_eligibility_id','token_eligibility_fingerprint','token_preparation_policy_id','token_preparation_policy_fingerprint','activation_authorization_handoff_id','activation_authorization_handoff_fingerprint','activation_authorization_id','activation_authorization_fingerprint','adapter_id','adapter_version','authorized_scope','prepared_token_scope','max_uses','token_constraints','authority_reference','authority_constraints','preparation_status','reason_codes','passive_only','token_generated','token_issued','token_consumed','token_material_present','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed'}
def build_default_runtime_adapter_activation_token_preparation_policy()->dict[str,Any]: return stable_artifact({'schema':POLICY_SCHEMA,'requires_eligible_decision':True,'requires_exact_linkage':True,'requires_bounded_scope':True,'requires_max_uses':1,'requires_passive_constraints':True,'prohibits_wildcard_scope':True,'prohibits_secret_or_executable':True,'prohibits_runtime_activation':True,'invalid_input_fails_closed':True},POLICY_ID,POLICY_PREFIX)
def validate_runtime_adapter_activation_token_preparation_policy(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=POLICY_SCHEMA,id_key=POLICY_ID,prefix=POLICY_PREFIX,fields=POLICY_FIELDS); e=list(r.errors)
 if isinstance(v,Mapping) and not all([v.get('requires_eligible_decision') is True,v.get('requires_exact_linkage') is True,v.get('requires_bounded_scope') is True,v.get('requires_max_uses')==1,v.get('requires_passive_constraints') is True,v.get('prohibits_wildcard_scope') is True,v.get('prohibits_secret_or_executable') is True,v.get('prohibits_runtime_activation') is True,v.get('invalid_input_fails_closed') is True]): e.append('invalid_policy')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_token_preparation_policy(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_token_preparation_policy(v); return {'schema':POLICY_SCHEMA,'valid':r.valid,'reason_codes':list(r.errors)}
def build_runtime_adapter_activation_token_preparation(request:Mapping[str,Any],eligibility:Mapping[str,Any],policy:Mapping[str,Any])->dict[str,Any]:
 rv=validate_runtime_adapter_activation_token_eligibility_request(request).valid; ev=validate_runtime_adapter_activation_token_eligibility(eligibility).valid; pv=validate_runtime_adapter_activation_token_preparation_policy(policy).valid
 linked=eligibility.get('token_eligibility_request_id')==request.get('token_eligibility_request_id') and eligibility.get('token_eligibility_request_fingerprint')==request.get('fingerprint')
 ok=rv and ev and pv and linked and eligibility.get('eligibility_status')=='eligible'
 reasons=[] if ok else ['token_preparation_not_permitted']
 return stable_artifact({'schema':SCHEMA,'token_eligibility_request_id':request.get('token_eligibility_request_id'),'token_eligibility_request_fingerprint':request.get('fingerprint'),'token_eligibility_id':eligibility.get('token_eligibility_id'),'token_eligibility_fingerprint':eligibility.get('fingerprint'),'token_preparation_policy_id':policy.get(POLICY_ID),'token_preparation_policy_fingerprint':policy.get('fingerprint'),'activation_authorization_handoff_id':request.get('activation_authorization_handoff_id'),'activation_authorization_handoff_fingerprint':request.get('activation_authorization_handoff_fingerprint'),'activation_authorization_id':request.get('activation_authorization_id'),'activation_authorization_fingerprint':request.get('activation_authorization_fingerprint'),'adapter_id':request.get('adapter_id'),'adapter_version':request.get('adapter_version'),'authorized_scope':request.get('authorized_scope'),'prepared_token_scope':request.get('requested_token_scope') if ok else {},'max_uses':request.get('requested_max_uses'),'token_constraints':request.get('token_constraints'),'authority_reference':request.get('authority_reference'),'authority_constraints':request.get('authority_constraints'),'preparation_status':'prepared' if ok else ('invalid' if not (rv and ev and pv) else 'not_prepared'),'reason_codes':normalize_reasons(reasons),'passive_only':True,'token_generated':False,'token_issued':False,'token_consumed':False,'token_material_present':False,'adapter_loaded':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'authority_consumed':False,'mutation_performed':False},ID,PREFIX)
def validate_runtime_adapter_activation_token_preparation(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='preparation_status',statuses={'prepared','not_prepared','invalid'}); e=list(r.errors)
 if isinstance(v,Mapping):
  if not passive_invariants_valid(v) or v.get('token_generated') is not False or v.get('token_issued') is not False or v.get('token_consumed') is not False: e.append('passive_invariant_violation')
  if v.get('preparation_status')=='prepared' and not (scope_bounded(v.get('prepared_token_scope'),v.get('authorized_scope')) and v.get('max_uses')==1 and token_constraints_valid(v.get('token_constraints'),v.get('prepared_token_scope'))): e.append('invalid_prepared_bounds')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_token_preparation(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_token_preparation(v); return {'schema':SCHEMA,'valid':r.valid,'preparation_status':v.get('preparation_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
