from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_preparation_common import *
from core.engineering.engineering_runtime_adapter_preparation_request import validate_runtime_adapter_preparation_request
from core.engineering.engineering_runtime_adapter_preparation_policy import validate_runtime_adapter_preparation_policy
from core.engineering.engineering_runtime_adapter_preparation_eligibility import validate_runtime_adapter_preparation_eligibility
from core.engineering.engineering_runtime_adapter_invocation_descriptor import validate_runtime_adapter_invocation_descriptor
from core.engineering.engineering_runtime_adapter_preparation import validate_runtime_adapter_preparation
SCHEMA='zero.engineering.runtime_adapter_preparation_closure.v1';ID='preparation_closure_id';PREFIX='engineering-runtime-adapter-preparation-closure-'
FIELDS={'request_valid','policy_valid','eligibility_valid','eligibility_status','invocation_descriptor_valid','preparation_valid','preparation_status','exact_linkage_valid','scope_boundary_valid','resource_bound_valid','timeout_bound_valid','environment_constraint_valid','authority_valid','passive_only_invariant','adapter_invocation_prohibited','runtime_invocation_prohibited','executor_invocation_prohibited','scheduler_invocation_prohibited','mutation_prohibited','authority_consumption_prohibited','package_status','reason_codes'}
def build_runtime_adapter_preparation_closure(request:Mapping[str,Any],policy:Mapping[str,Any],eligibility:Mapping[str,Any],descriptor:Mapping[str,Any],preparation:Mapping[str,Any])->dict[str,Any]:
 rv=validate_runtime_adapter_preparation_request(request).valid; pv=validate_runtime_adapter_preparation_policy(policy).valid; ev=validate_runtime_adapter_preparation_eligibility(eligibility).valid; dv=validate_runtime_adapter_invocation_descriptor(descriptor).valid; prv=validate_runtime_adapter_preparation(preparation).valid
 exact=preparation.get('preparation_request_id')==request.get('preparation_request_id') and preparation.get('preparation_policy_id')==policy.get('preparation_policy_id') and preparation.get('preparation_eligibility_id')==eligibility.get('preparation_eligibility_id') and preparation.get('invocation_descriptor_id')==descriptor.get('invocation_descriptor_id')
 passive=preparation.get('passive_only') is True and not any(preparation.get(k) for k in ('adapter_invoked','runtime_invoked','executor_invoked','scheduler_invoked','mutation_performed','authority_consumed'))
 reasons=[]
 for ok,code in ((rv,'invalid_request'),(pv,'invalid_policy'),(ev,'invalid_eligibility'),(dv,'invalid_descriptor'),(prv,'invalid_preparation'),(exact,'linkage_mismatch'),(passive,'passive_invariant_violation')):
  if not ok: reasons.append(code)
 status='invalid' if any(r.startswith('invalid') for r in reasons) else ('not_closed' if reasons or preparation.get('preparation_status')!='prepared' else 'closed')
 return stable_artifact({'schema':SCHEMA,'request_valid':rv,'policy_valid':pv,'eligibility_valid':ev,'eligibility_status':eligibility.get('eligibility_status'),'invocation_descriptor_valid':dv,'preparation_valid':prv,'preparation_status':preparation.get('preparation_status'),'exact_linkage_valid':exact,'scope_boundary_valid':scope_bounded(request.get('requested_scope'),descriptor.get('admitted_scope')),'resource_bound_valid':resources_valid(request.get('resource_constraints')),'timeout_bound_valid':timeout_valid(request.get('timeout_constraints')),'environment_constraint_valid':environment_valid(request.get('environment_constraints')),'authority_valid':authority_valid(request.get('authority_constraints'),request.get('requested_scope')),'passive_only_invariant':passive,'adapter_invocation_prohibited':preparation.get('adapter_invoked') is False,'runtime_invocation_prohibited':preparation.get('runtime_invoked') is False,'executor_invocation_prohibited':preparation.get('executor_invoked') is False,'scheduler_invocation_prohibited':preparation.get('scheduler_invoked') is False,'mutation_prohibited':preparation.get('mutation_performed') is False,'authority_consumption_prohibited':preparation.get('authority_consumed') is False,'package_status':status,'reason_codes':normalize_reasons(reasons)},ID,PREFIX)
def validate_runtime_adapter_preparation_closure(v:Any)->ValidationResult: return validate_artifact(v,schema=SCHEMA,statuses={'closed','not_closed','invalid'},id_key=ID,prefix=PREFIX,fields=FIELDS)
def inspect_runtime_adapter_preparation_closure(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_preparation_closure(v); return {'schema':SCHEMA,'valid':r.valid,'package_status':v.get('package_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
