from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_eligibility_common import *
from core.engineering.engineering_runtime_adapter_activation_eligibility_request import validate_runtime_adapter_activation_eligibility_request
from core.engineering.engineering_runtime_adapter_activation_eligibility_policy import validate_runtime_adapter_activation_eligibility_policy
from core.engineering.engineering_runtime_adapter_activation_constraint_profile import validate_runtime_adapter_activation_constraint_profile
from core.engineering.engineering_runtime_adapter_activation_eligibility_evaluation import validate_runtime_adapter_activation_eligibility_evaluation
SCHEMA='zero.engineering.runtime_adapter_activation_eligibility.v1';ID='activation_eligibility_id';PREFIX='engineering-runtime-adapter-activation-eligibility-'
FIELDS={'activation_eligibility_request_id','activation_eligibility_request_fingerprint','activation_eligibility_policy_id','activation_eligibility_policy_fingerprint','activation_constraint_profile_id','activation_constraint_profile_fingerprint','activation_eligibility_evaluation_id','activation_eligibility_evaluation_fingerprint','preparation_review_handoff_id','preparation_review_handoff_fingerprint','preparation_review_id','preparation_review_fingerprint','preparation_review_closure_id','preparation_review_closure_fingerprint','preparation_id','invocation_descriptor_id','runtime_adapter_admission_id','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','approved_scope','eligible_activation_scope','authority_reference','authority_constraints','eligibility_status','reason_codes','passive_only','activation_authorized','activation_token_issued','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','executor_invoked','scheduler_invoked','authority_consumed','mutation_performed'}
def build_runtime_adapter_activation_eligibility(request:Mapping[str,Any],policy:Mapping[str,Any],profile:Mapping[str,Any],evaluation:Mapping[str,Any])->dict[str,Any]:
 reasons=list(evaluation.get('reason_codes',[])); valid=validate_runtime_adapter_activation_eligibility_request(request).valid and validate_runtime_adapter_activation_eligibility_policy(policy).valid and validate_runtime_adapter_activation_constraint_profile(profile).valid and validate_runtime_adapter_activation_eligibility_evaluation(evaluation).valid and evaluation.get('eligibility_status')=='eligible'
 status='eligible' if valid else evaluation.get('eligibility_status','invalid')
 return stable_artifact({'schema':SCHEMA,'activation_eligibility_request_id':request.get('activation_eligibility_request_id'),'activation_eligibility_request_fingerprint':request.get('fingerprint'),'activation_eligibility_policy_id':policy.get('activation_eligibility_policy_id'),'activation_eligibility_policy_fingerprint':policy.get('fingerprint'),'activation_constraint_profile_id':profile.get('activation_constraint_profile_id'),'activation_constraint_profile_fingerprint':profile.get('fingerprint'),'activation_eligibility_evaluation_id':evaluation.get('activation_eligibility_evaluation_id'),'activation_eligibility_evaluation_fingerprint':evaluation.get('fingerprint'),'preparation_review_handoff_id':request.get('preparation_review_handoff_id'),'preparation_review_handoff_fingerprint':request.get('preparation_review_handoff_fingerprint'),'preparation_review_id':request.get('preparation_review_id'),'preparation_review_fingerprint':request.get('preparation_review_fingerprint'),'preparation_review_closure_id':request.get('preparation_review_closure_id'),'preparation_review_closure_fingerprint':request.get('preparation_review_closure_fingerprint'),'preparation_id':request.get('preparation_id'),'invocation_descriptor_id':request.get('invocation_descriptor_id'),'runtime_adapter_admission_id':request.get('runtime_adapter_admission_id'),'engineering_runtime_handoff_id':request.get('engineering_runtime_handoff_id'),'execution_session_id':request.get('execution_session_id'),'adapter_id':request.get('adapter_id'),'adapter_version':request.get('adapter_version'),'approved_scope':request.get('approved_scope'),'eligible_activation_scope':request.get('requested_activation_scope') if status=='eligible' else {},'authority_reference':request.get('authority_reference'),'authority_constraints':request.get('authority_constraints'),'eligibility_status':status,'reason_codes':normalize_reasons(reasons),'passive_only':True,'activation_authorized':False,'activation_token_issued':False,'adapter_loaded':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'executor_invoked':False,'scheduler_invoked':False,'authority_consumed':False,'mutation_performed':False},ID,PREFIX)
def validate_runtime_adapter_activation_eligibility(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='eligibility_status',statuses={'eligible','ineligible','invalid'}); e=list(r.errors)
 if isinstance(v,Mapping) and not passive_invariants_valid(v): e.append('passive_invariant_violation')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_eligibility(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_eligibility(v); return {'schema':SCHEMA,'valid':r.valid,'eligibility_status':v.get('eligibility_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
