from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_authorization_common import *
from core.engineering.engineering_runtime_adapter_activation_authorization import validate_runtime_adapter_activation_authorization
SCHEMA='zero.engineering.runtime_adapter_activation_authorization_handoff.v1';ID='activation_authorization_handoff_id';PREFIX='engineering-runtime-adapter-activation-authorization-handoff-'
FIELDS={'activation_authorization_id','activation_authorization_fingerprint','authorization_status','activation_authorization_request_id','activation_authorization_policy_id','activation_authorization_review_id','activation_eligibility_handoff_id','activation_eligibility_id','activation_eligibility_closure_id','preparation_review_handoff_id','preparation_review_id','preparation_id','invocation_descriptor_id','runtime_adapter_admission_id','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','authorized_scope','authority_reference','authority_constraints','eligible_for_activation_token_review','activation_authorized','activation_token_issued','token_material_present','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed'}
def build_runtime_adapter_activation_authorization_handoff(authorization:Mapping[str,Any])->dict[str,Any]:
 ok=validate_runtime_adapter_activation_authorization(authorization).valid and authorization.get('authorization_status')=='authorized'
 return stable_artifact({'schema':SCHEMA,'activation_authorization_id':authorization.get('activation_authorization_id'),'activation_authorization_fingerprint':authorization.get('fingerprint'),'authorization_status':authorization.get('authorization_status'),'activation_authorization_request_id':authorization.get('activation_authorization_request_id'),'activation_authorization_policy_id':authorization.get('activation_authorization_policy_id'),'activation_authorization_review_id':authorization.get('activation_authorization_review_id'),'activation_eligibility_handoff_id':authorization.get('activation_eligibility_handoff_id'),'activation_eligibility_id':authorization.get('activation_eligibility_id'),'activation_eligibility_closure_id':authorization.get('activation_eligibility_closure_id'),'preparation_review_handoff_id':authorization.get('preparation_review_handoff_id'),'preparation_review_id':authorization.get('preparation_review_id'),'preparation_id':authorization.get('preparation_id'),'invocation_descriptor_id':authorization.get('invocation_descriptor_id'),'runtime_adapter_admission_id':authorization.get('runtime_adapter_admission_id'),'engineering_runtime_handoff_id':authorization.get('engineering_runtime_handoff_id'),'execution_session_id':authorization.get('execution_session_id'),'adapter_id':authorization.get('adapter_id'),'adapter_version':authorization.get('adapter_version'),'authorized_scope':authorization.get('authorized_scope') if ok else {},'authority_reference':authorization.get('authority_reference'),'authority_constraints':authorization.get('authority_constraints'),'eligible_for_activation_token_review':ok,'activation_authorized':ok,'activation_token_issued':False,'token_material_present':False,'adapter_loaded':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'authority_consumed':False,'mutation_performed':False},ID,PREFIX)
def validate_runtime_adapter_activation_authorization_handoff(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS); e=list(r.errors)
 if isinstance(v,Mapping):
  ok=v.get('authorization_status')=='authorized'
  if v.get('eligible_for_activation_token_review') is not ok or v.get('activation_authorized') is not ok: e.append('passive_invariant_violation')
  if not passive_invariants_valid(v,authorized_ok=True): e.append('passive_invariant_violation')
  if ok and not authority_valid(v.get('authority_constraints'),v.get('authorized_scope')): e.append('unbounded_authority')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_authorization_handoff(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_authorization_handoff(v); return {'schema':SCHEMA,'valid':r.valid,'eligible_for_activation_token_review':v.get('eligible_for_activation_token_review') if isinstance(v,Mapping) else False,'reason_codes':list(r.errors)}
