from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_preparation_review_common import *
from core.engineering.engineering_runtime_adapter_preparation_review_request import validate_runtime_adapter_preparation_review_request
from core.engineering.engineering_runtime_adapter_preparation_review_policy import validate_runtime_adapter_preparation_review_policy
from core.engineering.engineering_runtime_adapter_preparation_review_eligibility import validate_runtime_adapter_preparation_review_eligibility
from core.engineering.engineering_runtime_adapter_preparation_review_findings import validate_runtime_adapter_preparation_review_findings
from core.engineering.engineering_runtime_adapter_preparation_review import validate_runtime_adapter_preparation_review
from core.engineering.engineering_runtime_adapter_preparation_review_handoff import validate_runtime_adapter_preparation_review_handoff
SCHEMA='zero.engineering.runtime_adapter_preparation_review_closure.v1';ID='review_closure_id';PREFIX='engineering-runtime-adapter-preparation-review-closure-'
FIELDS={'review_request_valid','review_policy_valid','review_eligibility_status','findings_valid','review_decision_status','handoff_valid','exact_linkage_valid','scope_boundary_valid','resource_bound_valid','timeout_bound_valid','environment_valid','authority_valid','passive_only_invariant','activation_prohibited','adapter_invocation_prohibited','runtime_invocation_prohibited','executor_invocation_prohibited','scheduler_invocation_prohibited','mutation_prohibited','authority_consumption_prohibited','package_status','reason_codes'}
def build_runtime_adapter_preparation_review_closure(request:Mapping[str,Any],policy:Mapping[str,Any],eligibility:Mapping[str,Any],findings:Mapping[str,Any],review:Mapping[str,Any],handoff:Mapping[str,Any])->dict[str,Any]:
 rv=validate_runtime_adapter_preparation_review_request(request).valid; pv=validate_runtime_adapter_preparation_review_policy(policy).valid; ev=validate_runtime_adapter_preparation_review_eligibility(eligibility).valid; fv=validate_runtime_adapter_preparation_review_findings(findings).valid; dv=validate_runtime_adapter_preparation_review(review).valid; hv=validate_runtime_adapter_preparation_review_handoff(handoff).valid
 exact=review.get('review_request_id')==request.get('review_request_id') and handoff.get('review_id')==review.get('review_id')
 passive=review.get('passive_only') is True and not any(review.get(k) for k in ('activation_authorized','adapter_activated','adapter_invoked','runtime_invoked','executor_invoked','scheduler_invoked','mutation_performed','authority_consumed')) and not any(handoff.get(k) for k in ('activation_authorized','adapter_activated','adapter_invoked','runtime_invoked','mutation_performed','authority_consumed'))
 reasons=[]
 for ok,code in ((rv,'invalid_review_request'),(pv,'invalid_review_policy'),(ev,'invalid_review_eligibility'),(fv,'invalid_findings'),(dv,'invalid_review'),(hv,'invalid_handoff'),(exact,'linkage_mismatch'),(passive,'passive_invariant_violation')):
  if not ok: reasons.append(code)
 status='invalid' if any(r.startswith('invalid') for r in reasons) else ('not_closed' if reasons or review.get('review_status')!='approved' else 'closed')
 return stable_artifact({'schema':SCHEMA,'review_request_valid':rv,'review_policy_valid':pv,'review_eligibility_status':eligibility.get('eligibility_status'),'findings_valid':fv,'review_decision_status':review.get('review_status'),'handoff_valid':hv,'exact_linkage_valid':exact,'scope_boundary_valid':findings.get('scope_valid') is True,'resource_bound_valid':findings.get('resources_valid') is True,'timeout_bound_valid':findings.get('timeout_valid') is True,'environment_valid':findings.get('environment_valid') is True,'authority_valid':findings.get('authority_valid') is True,'passive_only_invariant':passive,'activation_prohibited':handoff.get('activation_authorized') is False,'adapter_invocation_prohibited':handoff.get('adapter_invoked') is False,'runtime_invocation_prohibited':handoff.get('runtime_invoked') is False,'executor_invocation_prohibited':review.get('executor_invoked') is False,'scheduler_invocation_prohibited':review.get('scheduler_invoked') is False,'mutation_prohibited':handoff.get('mutation_performed') is False,'authority_consumption_prohibited':handoff.get('authority_consumed') is False,'package_status':status,'reason_codes':normalize_reasons(reasons)},ID,PREFIX)
def validate_runtime_adapter_preparation_review_closure(v:Any)->ValidationResult: return validate_artifact(v,schema=SCHEMA,statuses={'closed','not_closed','invalid'},id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='package_status')
def inspect_runtime_adapter_preparation_review_closure(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_preparation_review_closure(v); return {'schema':SCHEMA,'valid':r.valid,'package_status':v.get('package_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
