from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_preparation_review_common import *
from core.engineering.engineering_runtime_adapter_preparation_review_request import validate_runtime_adapter_preparation_review_request
from core.engineering.engineering_runtime_adapter_preparation_review_policy import validate_runtime_adapter_preparation_review_policy
from core.engineering.engineering_runtime_adapter_preparation_review_eligibility import validate_runtime_adapter_preparation_review_eligibility
from core.engineering.engineering_runtime_adapter_preparation_review_findings import validate_runtime_adapter_preparation_review_findings
SCHEMA='zero.engineering.runtime_adapter_preparation_review.v1';ID='review_id';PREFIX='engineering-runtime-adapter-preparation-review-'
FIELDS={'review_request_id','review_request_fingerprint','review_policy_id','review_policy_fingerprint','review_eligibility_id','review_eligibility_fingerprint','review_findings_id','review_findings_fingerprint','preparation_id','preparation_fingerprint','preparation_closure_id','preparation_closure_fingerprint','invocation_descriptor_id','invocation_descriptor_fingerprint','runtime_adapter_admission_id','runtime_adapter_admission_fingerprint','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','reviewed_scope','review_status','reason_codes','passive_only','activation_authorized','adapter_activated','adapter_invoked','runtime_invoked','executor_invoked','scheduler_invoked','authority_consumed','mutation_performed'}
def build_runtime_adapter_preparation_review(request:Mapping[str,Any],policy:Mapping[str,Any],eligibility:Mapping[str,Any],findings:Mapping[str,Any])->dict[str,Any]:
 reasons=[]
 for ok,code in ((validate_runtime_adapter_preparation_review_request(request).valid,'invalid_review_request'),(validate_runtime_adapter_preparation_review_policy(policy).valid,'invalid_review_policy'),(validate_runtime_adapter_preparation_review_eligibility(eligibility).valid,'invalid_review_eligibility'),(validate_runtime_adapter_preparation_review_findings(findings).valid,'invalid_review_findings')):
  if not ok: reasons.append(code)
 reasons.extend(eligibility.get('reason_codes',[]) or []); reasons.extend(findings.get('blocking_findings',[]) or [])
 if eligibility.get('eligibility_status')!='eligible': reasons.append('not_eligible')
 if findings.get('blocking_findings'): reasons.append('blocking_findings_present')
 status='invalid' if any(r in ('invalid_review_request','invalid_review_policy') for r in reasons) else ('not_approved' if reasons else 'approved')
 return stable_artifact({'schema':SCHEMA,'review_request_id':request.get('review_request_id'),'review_request_fingerprint':request.get('fingerprint'),'review_policy_id':policy.get('review_policy_id'),'review_policy_fingerprint':policy.get('fingerprint'),'review_eligibility_id':eligibility.get('review_eligibility_id'),'review_eligibility_fingerprint':eligibility.get('fingerprint'),'review_findings_id':findings.get('review_findings_id'),'review_findings_fingerprint':findings.get('fingerprint'),'preparation_id':request.get('runtime_adapter_preparation_id'),'preparation_fingerprint':request.get('runtime_adapter_preparation_fingerprint'),'preparation_closure_id':request.get('runtime_adapter_preparation_closure_id'),'preparation_closure_fingerprint':request.get('runtime_adapter_preparation_closure_fingerprint'),'invocation_descriptor_id':request.get('invocation_descriptor_id'),'invocation_descriptor_fingerprint':request.get('invocation_descriptor_fingerprint'),'runtime_adapter_admission_id':request.get('runtime_adapter_admission_id'),'runtime_adapter_admission_fingerprint':request.get('runtime_adapter_admission_fingerprint'),'engineering_runtime_handoff_id':request.get('engineering_runtime_handoff_id'),'execution_session_id':request.get('execution_session_id'),'adapter_id':request.get('adapter_id'),'adapter_version':request.get('adapter_version'),'reviewed_scope':request.get('prepared_scope') if status=='approved' else {},'review_status':status,'reason_codes':normalize_reasons(reasons),'passive_only':True,'activation_authorized':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'executor_invoked':False,'scheduler_invoked':False,'authority_consumed':False,'mutation_performed':False},ID,PREFIX)
def validate_runtime_adapter_preparation_review(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,statuses={'approved','not_approved','invalid'},id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='review_status'); e=list(r.errors)
 if isinstance(v,Mapping) and not passive_invariants_valid(v): e.append('passive_invariant_violation')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_preparation_review(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_preparation_review(v); return {'schema':SCHEMA,'valid':r.valid,'review_status':v.get('review_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
