from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_authorization_common import *
from core.engineering.engineering_runtime_adapter_activation_authorization_request import validate_runtime_adapter_activation_authorization_request
from core.engineering.engineering_runtime_adapter_activation_authorization_policy import validate_runtime_adapter_activation_authorization_policy
from core.engineering.engineering_runtime_adapter_activation_authorization_review import validate_runtime_adapter_activation_authorization_review
from core.engineering.engineering_runtime_adapter_activation_authorization import validate_runtime_adapter_activation_authorization
from core.engineering.engineering_runtime_adapter_activation_authorization_handoff import validate_runtime_adapter_activation_authorization_handoff
SCHEMA='zero.engineering.runtime_adapter_activation_authorization_closure.v1';ID='activation_authorization_closure_id';PREFIX='engineering-runtime-adapter-activation-authorization-closure-'
FIELDS={'request_valid','policy_valid','review_valid','review_status','authorization_status','handoff_valid','linkage_valid','scope_bound_valid','resource_bound_valid','timeout_bound_valid','environment_valid','authority_valid','passive_only','activation_authorization_decision_complete','activation_token_prohibited','token_material_prohibited','adapter_loading_prohibited','adapter_activation_prohibited','adapter_invocation_prohibited','runtime_invocation_prohibited','executor_invocation_prohibited','scheduler_invocation_prohibited','mutation_prohibited','authority_consumption_prohibited','package_status','reason_codes'}
def build_runtime_adapter_activation_authorization_closure(request:Mapping[str,Any],policy:Mapping[str,Any],review:Mapping[str,Any],authorization:Mapping[str,Any],handoff:Mapping[str,Any])->dict[str,Any]:
 rv=validate_runtime_adapter_activation_authorization_request(request).valid; pv=validate_runtime_adapter_activation_authorization_policy(policy).valid; ev=validate_runtime_adapter_activation_authorization_review(review).valid; av=validate_runtime_adapter_activation_authorization(authorization).valid; hv=validate_runtime_adapter_activation_authorization_handoff(handoff).valid
 closed=rv and pv and ev and av and hv and authorization.get('authorization_status')=='authorized' and handoff.get('eligible_for_activation_token_review') is True
 reasons=[] if closed else ['authorization_pipeline_not_closed']
 return stable_artifact({'schema':SCHEMA,'request_valid':rv,'policy_valid':pv,'review_valid':ev,'review_status':review.get('review_status'),'authorization_status':authorization.get('authorization_status'),'handoff_valid':hv,'linkage_valid':av and hv,'scope_bound_valid':scope_bounded(request.get('requested_authorized_scope'),request.get('eligible_activation_scope')) if isinstance(request,Mapping) else False,'resource_bound_valid':resources_valid(request.get('resource_constraints')) if isinstance(request,Mapping) else False,'timeout_bound_valid':timeout_valid(request.get('timeout_constraints')) if isinstance(request,Mapping) else False,'environment_valid':environment_valid(request.get('environment_constraints')) if isinstance(request,Mapping) else False,'authority_valid':authority_valid(request.get('authority_constraints'),request.get('eligible_activation_scope')) if isinstance(request,Mapping) else False,'passive_only':True,'activation_authorization_decision_complete':av,'activation_token_prohibited':True,'token_material_prohibited':True,'adapter_loading_prohibited':True,'adapter_activation_prohibited':True,'adapter_invocation_prohibited':True,'runtime_invocation_prohibited':True,'executor_invocation_prohibited':True,'scheduler_invocation_prohibited':True,'mutation_prohibited':True,'authority_consumption_prohibited':True,'package_status':'closed' if closed else ('invalid' if not (rv and pv and ev and av and hv) else 'not_closed'),'reason_codes':normalize_reasons(reasons+list(review.get('reason_codes',[])))},ID,PREFIX)
def validate_runtime_adapter_activation_authorization_closure(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='package_status',statuses={'closed','not_closed','invalid'}); e=list(r.errors)
 if isinstance(v,Mapping):
  if v.get('passive_only') is not True or not all(v.get(k) is True for k in ('activation_token_prohibited','token_material_prohibited','adapter_loading_prohibited','adapter_activation_prohibited','adapter_invocation_prohibited','runtime_invocation_prohibited','executor_invocation_prohibited','scheduler_invocation_prohibited','mutation_prohibited','authority_consumption_prohibited')): e.append('passive_invariant_violation')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_authorization_closure(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_authorization_closure(v); return {'schema':SCHEMA,'valid':r.valid,'package_status':v.get('package_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
