from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_token_common import *
from core.engineering.engineering_runtime_adapter_activation_token_eligibility import validate_runtime_adapter_activation_token_eligibility_request,validate_runtime_adapter_activation_token_eligibility
from core.engineering.engineering_runtime_adapter_activation_token_preparation import validate_runtime_adapter_activation_token_preparation_policy,validate_runtime_adapter_activation_token_preparation
from core.engineering.engineering_runtime_adapter_activation_token_review import validate_runtime_adapter_activation_token_review_request,validate_runtime_adapter_activation_token_review
from core.engineering.engineering_runtime_adapter_activation_token_authorization import validate_runtime_adapter_activation_token_authorization_policy,validate_runtime_adapter_activation_token_authorization
from core.engineering.engineering_runtime_adapter_activation_token_issuance import validate_runtime_adapter_activation_token_issuance
from core.engineering.engineering_runtime_adapter_activation_token_verification import validate_runtime_adapter_activation_token_verification
from core.engineering.engineering_runtime_adapter_activation_token_handoff import validate_runtime_adapter_activation_token_handoff
SCHEMA='zero.engineering.runtime_adapter_activation_token_governance_closure.v1';ID='token_governance_closure_id';PREFIX='engineering-runtime-adapter-activation-token-governance-closure-'
FIELDS={'eligibility_request_valid','eligibility_valid','eligibility_status','preparation_policy_valid','preparation_valid','preparation_status','review_request_valid','review_valid','review_status','authorization_policy_valid','authorization_valid','authorization_status','issuance_valid','issuance_status','verification_valid','verification_status','handoff_valid','exact_linkage_valid','scope_bound_valid','max_use_valid','session_binding_valid','adapter_binding_valid','authorization_binding_valid','authority_valid','credential_free_invariant','non_secret_token_invariant','non_bearer_invariant','non_executable_invariant','passive_only_invariant','token_unconsumed_invariant','adapter_loading_prohibition','adapter_activation_prohibition','adapter_invocation_prohibition','runtime_invocation_prohibition','executor_invocation_prohibition','scheduler_invocation_prohibition','mutation_prohibition','authority_consumption_prohibition','package_status','reason_codes'}
def build_runtime_adapter_activation_token_governance_closure(eligibility_request:Mapping[str,Any],eligibility:Mapping[str,Any],preparation_policy:Mapping[str,Any],preparation:Mapping[str,Any],review_request:Mapping[str,Any],review:Mapping[str,Any],authorization_policy:Mapping[str,Any],authorization:Mapping[str,Any],issuance:Mapping[str,Any],verification:Mapping[str,Any],handoff:Mapping[str,Any])->dict[str,Any]:
 vals={'eligibility_request_valid':validate_runtime_adapter_activation_token_eligibility_request(eligibility_request).valid,'eligibility_valid':validate_runtime_adapter_activation_token_eligibility(eligibility).valid,'preparation_policy_valid':validate_runtime_adapter_activation_token_preparation_policy(preparation_policy).valid,'preparation_valid':validate_runtime_adapter_activation_token_preparation(preparation).valid,'review_request_valid':validate_runtime_adapter_activation_token_review_request(review_request).valid,'review_valid':validate_runtime_adapter_activation_token_review(review).valid,'authorization_policy_valid':validate_runtime_adapter_activation_token_authorization_policy(authorization_policy).valid,'authorization_valid':validate_runtime_adapter_activation_token_authorization(authorization).valid,'issuance_valid':validate_runtime_adapter_activation_token_issuance(issuance).valid,'verification_valid':validate_runtime_adapter_activation_token_verification(verification).valid,'handoff_valid':validate_runtime_adapter_activation_token_handoff(handoff).valid}
 exact=eligibility.get('token_eligibility_request_id')==eligibility_request.get('token_eligibility_request_id') and preparation.get('token_eligibility_id')==eligibility.get('token_eligibility_id') and review.get('token_preparation_id')==preparation.get('token_preparation_id') and authorization.get('token_review_id')==review.get('token_review_id') and issuance.get('token_authorization_id')==authorization.get('token_authorization_id') and verification.get('token_id')==issuance.get('token_id') and handoff.get('token_id')==issuance.get('token_id')
 scope=scope_bounded(issuance.get('issued_scope'),authorization.get('authorized_token_scope')); use=issuance.get('max_uses')==1 and issuance.get('current_uses')==0 and handoff.get('max_uses')==1 and handoff.get('current_uses')==0
 session=issuance.get('execution_session_id')==review_request.get('execution_session_id')==handoff.get('execution_session_id'); adapter=issuance.get('adapter_id')==authorization.get('adapter_id')==handoff.get('adapter_id') and issuance.get('adapter_version')==authorization.get('adapter_version')==handoff.get('adapter_version')
 authbind=issuance.get('activation_authorization_id')==handoff.get('activation_authorization_id') and authorization.get('activation_authorization_id')==issuance.get('activation_authorization_id')
 authok=authority_valid(issuance.get('authority_constraints'),authorization.get('authorized_token_scope'))
 passive=not any(x.get(k) for x in (preparation,review,authorization,issuance,handoff) if isinstance(x,Mapping) for k in ('adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed','token_material_present'))
 closed=all(vals.values()) and eligibility.get('eligibility_status')=='eligible' and preparation.get('preparation_status')=='prepared' and review.get('review_status')=='approved' and authorization.get('authorization_status')=='authorized' and issuance.get('issuance_status')=='issued' and verification.get('verification_status')=='verified' and handoff.get('eligible_for_adapter_activation_admission') is True and exact and scope and use and session and adapter and authbind and authok and passive and issuance.get('consumed') is False and issuance.get('token_is_secret') is False and issuance.get('bearer_credential') is False and issuance.get('executable') is False
 body={'schema':SCHEMA,**vals,'eligibility_status':eligibility.get('eligibility_status'),'preparation_status':preparation.get('preparation_status'),'review_status':review.get('review_status'),'authorization_status':authorization.get('authorization_status'),'issuance_status':issuance.get('issuance_status'),'verification_status':verification.get('verification_status'),'exact_linkage_valid':exact,'scope_bound_valid':scope,'max_use_valid':use,'session_binding_valid':session,'adapter_binding_valid':adapter,'authorization_binding_valid':authbind,'authority_valid':authok,'credential_free_invariant':not contains_prohibited(issuance),'non_secret_token_invariant':issuance.get('token_is_secret') is False,'non_bearer_invariant':issuance.get('bearer_credential') is False,'non_executable_invariant':issuance.get('executable') is False,'passive_only_invariant':passive,'token_unconsumed_invariant':issuance.get('consumed') is False,'adapter_loading_prohibition':True,'adapter_activation_prohibition':True,'adapter_invocation_prohibition':True,'runtime_invocation_prohibition':True,'executor_invocation_prohibition':True,'scheduler_invocation_prohibition':True,'mutation_prohibition':True,'authority_consumption_prohibition':True,'package_status':'closed' if closed else ('invalid' if not all(vals.values()) else 'not_closed'),'reason_codes':normalize_reasons([] if closed else ['token_governance_not_closed'])}
 return stable_artifact(body,ID,PREFIX)
def validate_runtime_adapter_activation_token_governance_closure(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='package_status',statuses={'closed','not_closed','invalid'}); e=list(r.errors)
 if isinstance(v,Mapping) and not all(v.get(k) is True for k in ('adapter_loading_prohibition','adapter_activation_prohibition','adapter_invocation_prohibition','runtime_invocation_prohibition','executor_invocation_prohibition','scheduler_invocation_prohibition','mutation_prohibition','authority_consumption_prohibition')): e.append('passive_invariant_violation')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_token_governance_closure(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_token_governance_closure(v); return {'schema':SCHEMA,'valid':r.valid,'package_status':v.get('package_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
