from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_governed_execution_common import *
SCHEMA="zero.engineering.governed_execution_closure.v1";ID_KEY="governed_execution_closure_id";PREFIX="engineering-governed-execution-closure-";KIND="governed_execution_closure"
FIELDS={"engineering_execution_session_id","engineering_execution_session_fingerprint","engineering_runtime_handoff_id","engineering_runtime_handoff_fingerprint","engineering_execution_outcome_id","engineering_execution_outcome_fingerprint","governed_execution_verification_id","governed_execution_verification_fingerprint","execution_preparation_closure_id","authorization_closure_id","approval_closure_id","repository_identity","analyzed_revision","closure_status","execution_summary","completed_scope","unresolved_scope","evidence_summary","authority_closure_declaration","governance_boundary_declaration","next_boundary_declaration"}
def build_engineering_governed_execution_closure(intake:Mapping[str,Any],session:Mapping[str,Any],handoff:Mapping[str,Any],evidence:Mapping[str,Any],outcome:Mapping[str,Any],verification:Mapping[str,Any])->dict[str,Any]:
 result=outcome.get("result_status"); verified=verification.get("verification_status")=="verified"
 status="closed_completed" if result=="completed" and verified else {"partially_completed":"closed_partial","failed":"failed","invalid":"invalid","insufficient_evidence":"insufficient_evidence"}.get(result,"blocked")
 p={"engineering_execution_session_id":session.get("engineering_execution_session_id"),"engineering_execution_session_fingerprint":session.get("fingerprint"),"engineering_runtime_handoff_id":handoff.get("engineering_runtime_handoff_id"),"engineering_runtime_handoff_fingerprint":handoff.get("fingerprint"),"engineering_execution_outcome_id":outcome.get("engineering_execution_outcome_id"),"engineering_execution_outcome_fingerprint":outcome.get("fingerprint"),"governed_execution_verification_id":verification.get("governed_execution_verification_id"),"governed_execution_verification_fingerprint":verification.get("fingerprint"),"execution_preparation_closure_id":intake.get("execution_preparation_closure_id"),"authorization_closure_id":intake.get("authorization_closure_id"),"approval_closure_id":intake.get("approval_closure_id"),"repository_identity":intake.get("repository_identity"),"analyzed_revision":intake.get("analyzed_revision"),"closure_status":status,"execution_summary":result,"completed_scope":outcome.get("completed_scope",{}),"unresolved_scope":outcome.get("incomplete_scope",{}) or outcome.get("blocked_scope",{}),"evidence_summary":{"integrity_status":evidence.get("integrity_status"),"record_count":len(evidence.get("evidence_records",[]))},"authority_closure_declaration":{"approval_authority":"historical_granted","authorization_authority":"historical_granted","execution_authority":"consumed_closed","mutation_authority":"not_retained","reusable_execution_token":False,"permanent_execution_grant":False},"governance_boundary_declaration":{"sealed":True,"ungoverned_mutation":False,"forbidden_payload":False},"next_boundary_declaration":["Engineering Execution Result Review","Engineering Verification Closure","Engineering Activity Memory / Reflection intake","operator inspection"]}
 return artifact(SCHEMA,status,p,ID_KEY,PREFIX,KIND,closed=True)
def validate_engineering_governed_execution_closure(v:Any)->ValidationResult:return validate_artifact(v,schema=SCHEMA,statuses={"closed_completed","closed_partial","blocked","failed","invalid","insufficient_evidence"},id_key=ID_KEY,prefix=PREFIX,kind=KIND,fields=FIELDS,closed=True)
build_governed_execution_closure=build_engineering_governed_execution_closure
__all__=["build_engineering_governed_execution_closure","build_governed_execution_closure","validate_engineering_governed_execution_closure"]
