from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_preparation_review_common import *
from core.engineering.engineering_runtime_adapter_invocation_descriptor import validate_runtime_adapter_invocation_descriptor
SCHEMA='zero.engineering.runtime_adapter_preparation_review_request.v1';ID='review_request_id';PREFIX='engineering-runtime-adapter-preparation-review-request-'
FIELDS={'runtime_adapter_preparation_id','runtime_adapter_preparation_fingerprint','runtime_adapter_preparation_status','runtime_adapter_preparation_closure_id','runtime_adapter_preparation_closure_fingerprint','runtime_adapter_preparation_closure_status','invocation_descriptor_id','invocation_descriptor_fingerprint','preparation_request_id','preparation_request_fingerprint','preparation_policy_id','preparation_policy_fingerprint','preparation_eligibility_id','preparation_eligibility_fingerprint','runtime_adapter_admission_id','runtime_adapter_admission_fingerprint','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','prepared_scope','authority_reference','authority_constraints','review_context','request_input_fingerprint'}
def build_runtime_adapter_preparation_review_request(preparation:Mapping[str,Any],closure:Mapping[str,Any],descriptor:Mapping[str,Any],review_context:Mapping[str,Any])->dict[str,Any]:
 p={'schema':SCHEMA,'runtime_adapter_preparation_id':preparation.get('preparation_id'),'runtime_adapter_preparation_fingerprint':preparation.get('fingerprint'),'runtime_adapter_preparation_status':preparation.get('preparation_status'),'runtime_adapter_preparation_closure_id':closure.get('preparation_closure_id'),'runtime_adapter_preparation_closure_fingerprint':closure.get('fingerprint'),'runtime_adapter_preparation_closure_status':closure.get('package_status'),'invocation_descriptor_id':descriptor.get('invocation_descriptor_id'),'invocation_descriptor_fingerprint':descriptor.get('fingerprint'),'preparation_request_id':preparation.get('preparation_request_id'),'preparation_request_fingerprint':preparation.get('preparation_request_fingerprint'),'preparation_policy_id':preparation.get('preparation_policy_id'),'preparation_policy_fingerprint':preparation.get('preparation_policy_fingerprint'),'preparation_eligibility_id':preparation.get('preparation_eligibility_id'),'preparation_eligibility_fingerprint':preparation.get('preparation_eligibility_fingerprint'),'runtime_adapter_admission_id':preparation.get('runtime_adapter_admission_id'),'runtime_adapter_admission_fingerprint':preparation.get('runtime_adapter_admission_fingerprint'),'engineering_runtime_handoff_id':preparation.get('engineering_runtime_handoff_id'),'execution_session_id':preparation.get('execution_session_id'),'adapter_id':preparation.get('adapter_id'),'adapter_version':preparation.get('adapter_version'),'prepared_scope':preparation.get('prepared_scope'),'authority_reference':descriptor.get('authority_reference'),'authority_constraints':descriptor.get('authority_constraints'),'review_context':dict(review_context),'request_input_fingerprint':canonical_fingerprint({'preparation':preparation,'closure':closure,'descriptor':descriptor,'review_context':review_context})}
 return stable_artifact(p,ID,PREFIX)
def validate_runtime_adapter_preparation_review_request(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,statuses=set(),id_key=ID,prefix=PREFIX,fields=FIELDS); e=list(r.errors)
 if isinstance(v,Mapping):
  if v.get('runtime_adapter_preparation_status')!='prepared': e.append('preparation_not_prepared')
  if v.get('runtime_adapter_preparation_closure_status')!='closed': e.append('closure_not_closed')
  if not validate_runtime_adapter_invocation_descriptor({'schema':'zero.engineering.runtime_adapter_invocation_descriptor.v1','invocation_descriptor_id':v.get('invocation_descriptor_id'),'fingerprint':v.get('invocation_descriptor_fingerprint'),'preparation_request_id':v.get('preparation_request_id'),'preparation_request_fingerprint':v.get('preparation_request_fingerprint'),'preparation_eligibility_id':v.get('preparation_eligibility_id'),'preparation_eligibility_fingerprint':v.get('preparation_eligibility_fingerprint'),'runtime_adapter_admission_id':v.get('runtime_adapter_admission_id'),'runtime_adapter_admission_fingerprint':v.get('runtime_adapter_admission_fingerprint'),'engineering_runtime_handoff_id':v.get('engineering_runtime_handoff_id'),'execution_session_id':v.get('execution_session_id'),'adapter_id':v.get('adapter_id'),'adapter_version':v.get('adapter_version'),'operation':{'operation_type':'review'},'admitted_scope':v.get('prepared_scope'),'prepared_scope':v.get('prepared_scope'),'input_bindings':{'ref':'opaque'},'expected_output_contract':{'format':'json'},'resource_constraints':{'units':1},'environment_constraints':{'network':'disabled'},'timeout_constraints':{'seconds':1,'finite':True,'perpetual':False},'authority_reference':v.get('authority_reference'),'authority_constraints':v.get('authority_constraints'),'passive_only':True,'executable':False,'adapter_loaded':False,'adapter_invoked':False,'runtime_invoked':False,'executor_invoked':False,'scheduler_invoked':False,'authority_consumed':False,'mutation_performed':False}).valid: pass
  if not canonical_nonempty(v.get('adapter_id')): e.append('adapter_identity_mismatch')
  if not canonical_nonempty(v.get('adapter_version')): e.append('adapter_version_mismatch')
  if contains_wildcard(v.get('prepared_scope')): e.append('wildcard_scope')
  if not authority_valid(v.get('authority_constraints'),v.get('prepared_scope')): e.append('invalid_authority_constraints')
  if not passive_mapping(v.get('review_context')): e.append('malformed_review_context')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_preparation_review_request(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_preparation_review_request(v); return {'schema':SCHEMA,'valid':r.valid,'reason_codes':list(r.errors)}
