from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_proposal_review import validate_engineering_proposal_review
from core.engineering.engineering_proposal_review_common import ValidationResult,review_artifact,validate_review_artifact
from core.engineering.engineering_proposal_review_verification import validate_engineering_proposal_review_verification
SCHEMA="zero.engineering.proposal_review_closure.v1";ID_KEY="proposal_review_closure_id";PREFIX="engineering-proposal-review-closure-";FIELDS={"engineering_proposal_review_id","engineering_proposal_review_fingerprint","proposal_review_verification_id","proposal_review_verification_fingerprint","proposal_review_decision_id","proposal_review_decision_fingerprint","proposal_closure_id","engineering_proposal_id","planning_closure_id","repository_identity","analyzed_revision","review_summary","decision","unresolved_findings","blocking_findings","approval_readiness_declaration","governance_boundary_declaration","next_boundary_declaration"}
APPROVAL={"readiness":"eligible_for_approval_review","approved":False,"approval_decision_made":False,"authorization_decision_made":False,"executable":False};GOVERNANCE={"approval_granted":False,"authorization_granted":False,"execution_granted":False,"mutation_granted":False,"proposal_mutable":False,"repository_mutable":False,"executor_invocation_allowed":False};NEXT={"foundation":"Engineering Approval Foundation","boundary":"governed approval intake boundary","authorization":False,"executor":False,"scheduler":False,"mutation_adapter":False,"runtime_activation":False,"deployment":False}
def build_engineering_proposal_review_closure(review:Mapping[str,Any],verification:Mapping[str,Any])->dict[str,Any]:
 valid=validate_engineering_proposal_review(review).valid and validate_engineering_proposal_review_verification(verification).valid;decision=review.get("review_decision",{});d=decision.get("decision","invalid");status="closed" if valid and d=="ready_for_approval" and verification.get("status")=="verified" and not decision.get("blocking_finding_ids") else ("changes_requested" if d=="changes_requested" else d)
 intake=review.get("review_intake",{});p={"engineering_proposal_review_id":review.get("engineering_proposal_review_id"),"engineering_proposal_review_fingerprint":review.get("fingerprint"),"proposal_review_verification_id":verification.get("proposal_review_verification_id"),"proposal_review_verification_fingerprint":verification.get("fingerprint"),"proposal_review_decision_id":decision.get("proposal_review_decision_id"),"proposal_review_decision_fingerprint":decision.get("fingerprint"),"proposal_closure_id":intake.get("proposal_closure_id"),"engineering_proposal_id":intake.get("engineering_proposal_id"),"planning_closure_id":intake.get("planning_closure_id"),"repository_identity":intake.get("repository_identity"),"analyzed_revision":intake.get("analyzed_revision"),"review_summary":{"finding_count":len(review.get("review_findings",[])),"ready_for_approval":d=="ready_for_approval","approved":False},"decision":d,"unresolved_findings":decision.get("unresolved_finding_ids",[]),"blocking_findings":decision.get("blocking_finding_ids",[]),"approval_readiness_declaration":dict(APPROVAL) if d=="ready_for_approval" else {**APPROVAL,"readiness":"not_eligible"},"governance_boundary_declaration":dict(GOVERNANCE),"next_boundary_declaration":dict(NEXT)};return review_artifact(SCHEMA,status,p,ID_KEY,PREFIX)
def validate_engineering_proposal_review_closure(v:Any)->ValidationResult:return validate_review_artifact(v,schema=SCHEMA,statuses={"closed","changes_requested","blocked","invalid","insufficient_evidence"},id_key=ID_KEY,prefix=PREFIX,fields=FIELDS)
__all__=["build_engineering_proposal_review_closure","validate_engineering_proposal_review_closure"]
