from __future__ import annotations
from typing import Any, Mapping
from core.engineering.engineering_planning_common import freeze, seal
SCHEMA='zero.engineering.feedback_persistence.v1'
def _ref(a:Mapping[str,Any], key:str)->dict[str,Any]: return {'identity':a.get(key), 'fingerprint':a.get('fingerprint'), 'schema':a.get('schema')}
def persist_feedback_state(*, failure_analysis:Mapping[str,Any], eligibility:Mapping[str,Any], continuation_cycle:Mapping[str,Any], candidate:Mapping[str,Any]|None=None, plan:Mapping[str,Any]|None=None, proposal:Mapping[str,Any]|None=None, proposal_linkage:Mapping[str,Any]|None=None, replay_count:int=0, resume_count:int=0)->Mapping[str,Any]:
 body={'schema':SCHEMA,'task_id':failure_analysis.get('task_id'),'failure_analysis_reference':_ref(failure_analysis,'failure_analysis_id'),'eligibility_reference':_ref(eligibility,'repair_continuation_eligibility_id'),'continuation_cycle_reference':_ref(continuation_cycle,'repair_continuation_cycle_id'),'candidate_reference':_ref(candidate or {},'candidate_id'),'plan_reference':_ref(plan or {},'repair_plan_id'),'proposal_reference':_ref(proposal or {},'proposal_id'),'proposal_linkage_reference':_ref(proposal_linkage or {},'proposal_linkage_id'),'cycle_number':eligibility.get('cycle_number'),'maximum_cycles':eligibility.get('maximum_cycles'),'cycle_status':continuation_cycle.get('cycle_status'),'reason_codes':list(continuation_cycle.get('reason_codes') or []),'replay_count':int(replay_count),'resume_count':int(resume_count),'deterministic':True,'immutable':True}
 return seal(body,'feedback_state_id','engineering-feedback-state')
def resume_feedback_state(state:Mapping[str,Any])->Mapping[str,Any]:
 if state.get('schema')!=SCHEMA: raise ValueError('schema_mismatch')
 return persist_feedback_state(failure_analysis={'failure_analysis_id':state['failure_analysis_reference']['identity'],'fingerprint':state['failure_analysis_reference']['fingerprint'],'schema':state['failure_analysis_reference']['schema'],'task_id':state.get('task_id')}, eligibility={'repair_continuation_eligibility_id':state['eligibility_reference']['identity'],'fingerprint':state['eligibility_reference']['fingerprint'],'schema':state['eligibility_reference']['schema'],'cycle_number':state.get('cycle_number'),'maximum_cycles':state.get('maximum_cycles')}, continuation_cycle={'repair_continuation_cycle_id':state['continuation_cycle_reference']['identity'],'fingerprint':state['continuation_cycle_reference']['fingerprint'],'schema':state['continuation_cycle_reference']['schema'],'cycle_status':state.get('cycle_status'),'reason_codes':state.get('reason_codes',[])}, replay_count=state.get('replay_count',0), resume_count=int(state.get('resume_count',0))+1)
