from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_token_common import *
from core.engineering.engineering_runtime_adapter_activation_authorization_handoff import validate_runtime_adapter_activation_authorization_handoff
REQ_SCHEMA='zero.engineering.runtime_adapter_activation_token_eligibility_request.v1';ELIG_SCHEMA='zero.engineering.runtime_adapter_activation_token_eligibility.v1';REQ_ID='token_eligibility_request_id';ELIG_ID='token_eligibility_id';REQ_PREFIX='engineering-runtime-adapter-activation-token-eligibility-request-';ELIG_PREFIX='engineering-runtime-adapter-activation-token-eligibility-'
REQ_FIELDS={'activation_authorization_handoff_id','activation_authorization_handoff_fingerprint','activation_authorization_id','activation_authorization_fingerprint','activation_authorization_status','activation_authorization_closure_id','activation_authorization_closure_fingerprint','activation_authorization_closure_status','activation_authorization_request_id','activation_authorization_policy_id','activation_authorization_review_id','activation_eligibility_handoff_id','activation_eligibility_id','preparation_review_handoff_id','preparation_id','invocation_descriptor_id','runtime_adapter_admission_id','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','authorized_scope','requested_token_scope','requested_max_uses','token_constraints','authority_reference','authority_constraints','request_context','request_input_fingerprint'}
ELIG_FIELDS=REQ_FIELDS|{REQ_ID,'token_eligibility_request_fingerprint','eligibility_status','reason_codes','eligible_for_token_preparation','passive_only','token_issued','token_consumed','token_material_present','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed'}
def build_runtime_adapter_activation_token_eligibility_request(handoff:Mapping[str,Any],closure:Mapping[str,Any],requested_token_scope:Any,requested_max_uses:int,token_constraints:Mapping[str,Any],authority_reference:Any,authority_constraints:Mapping[str,Any],request_context:Mapping[str,Any]|None=None)->dict[str,Any]:
 return stable_artifact({'schema':REQ_SCHEMA,'activation_authorization_handoff_id':handoff.get('activation_authorization_handoff_id'),'activation_authorization_handoff_fingerprint':handoff.get('fingerprint'),'activation_authorization_id':handoff.get('activation_authorization_id'),'activation_authorization_fingerprint':handoff.get('activation_authorization_fingerprint'),'activation_authorization_status':handoff.get('authorization_status'),'activation_authorization_closure_id':closure.get('activation_authorization_closure_id'),'activation_authorization_closure_fingerprint':closure.get('fingerprint'),'activation_authorization_closure_status':closure.get('package_status'),'activation_authorization_request_id':handoff.get('activation_authorization_request_id'),'activation_authorization_policy_id':handoff.get('activation_authorization_policy_id'),'activation_authorization_review_id':handoff.get('activation_authorization_review_id'),'activation_eligibility_handoff_id':handoff.get('activation_eligibility_handoff_id'),'activation_eligibility_id':handoff.get('activation_eligibility_id'),'preparation_review_handoff_id':handoff.get('preparation_review_handoff_id'),'preparation_id':handoff.get('preparation_id'),'invocation_descriptor_id':handoff.get('invocation_descriptor_id'),'runtime_adapter_admission_id':handoff.get('runtime_adapter_admission_id'),'engineering_runtime_handoff_id':handoff.get('engineering_runtime_handoff_id'),'execution_session_id':handoff.get('execution_session_id'),'adapter_id':handoff.get('adapter_id'),'adapter_version':handoff.get('adapter_version'),'authorized_scope':handoff.get('authorized_scope'),'requested_token_scope':requested_token_scope,'requested_max_uses':requested_max_uses,'token_constraints':dict(token_constraints),'authority_reference':authority_reference,'authority_constraints':dict(authority_constraints),'request_context':dict(request_context or {}),'request_input_fingerprint':canonical_fingerprint({'handoff':handoff.get('fingerprint'),'closure':closure.get('fingerprint'),'scope':requested_token_scope,'max_uses':requested_max_uses,'constraints':token_constraints,'authority':authority_reference})},REQ_ID,REQ_PREFIX)
def validate_runtime_adapter_activation_token_eligibility_request(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=REQ_SCHEMA,id_key=REQ_ID,prefix=REQ_PREFIX,fields=REQ_FIELDS); e=list(r.errors)
 if isinstance(v,Mapping):
  if v.get('activation_authorization_status')!='authorized': e.append('authorization_not_authorized')
  if v.get('activation_authorization_closure_status')!='closed': e.append('authorization_closure_not_closed')
  if not scope_bounded(v.get('requested_token_scope'),v.get('authorized_scope')): e.append('scope_not_bounded')
  if v.get('requested_max_uses')!=1: e.append('max_uses_not_one')
  if not token_constraints_valid(v.get('token_constraints'),v.get('requested_token_scope')): e.append('invalid_token_constraints')
  if not authority_valid(v.get('authority_constraints'),v.get('authorized_scope')): e.append('invalid_authority')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_token_eligibility_request(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_token_eligibility_request(v); return {'schema':REQ_SCHEMA,'valid':r.valid,'reason_codes':list(r.errors)}
def evaluate_runtime_adapter_activation_token_eligibility(request:Mapping[str,Any],handoff:Mapping[str,Any]|None=None,closure:Mapping[str,Any]|None=None)->dict[str,Any]:
 rv=validate_runtime_adapter_activation_token_eligibility_request(request).valid; reasons=[]
 hv=True if handoff is None else validate_runtime_adapter_activation_authorization_handoff(handoff).valid and request.get('activation_authorization_handoff_id')==handoff.get('activation_authorization_handoff_id') and request.get('activation_authorization_handoff_fingerprint')==handoff.get('fingerprint') and handoff.get('eligible_for_activation_token_review') is True and handoff.get('activation_authorized') is True and not any(handoff.get(k) for k in ('activation_token_issued','token_material_present','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed'))
 cv=True if closure is None else request.get('activation_authorization_closure_id')==closure.get('activation_authorization_closure_id') and request.get('activation_authorization_closure_fingerprint')==closure.get('fingerprint') and closure.get('package_status')=='closed'
 ok=rv and hv and cv
 if not rv: reasons+=list(validate_runtime_adapter_activation_token_eligibility_request(request).errors)
 if not hv: reasons.append('authorization_handoff_not_eligible')
 if not cv: reasons.append('authorization_closure_linkage_invalid')
 status='eligible' if ok else ('invalid' if not isinstance(request,Mapping) or contains_prohibited(request) else 'ineligible')
 body={k:request.get(k) for k in REQ_FIELDS}; body.update({'schema':ELIG_SCHEMA,REQ_ID:request.get(REQ_ID),'token_eligibility_request_fingerprint':request.get('fingerprint'),'eligibility_status':status,'reason_codes':normalize_reasons(reasons),'eligible_for_token_preparation':status=='eligible','passive_only':True,'token_issued':False,'token_consumed':False,'token_material_present':False,'adapter_loaded':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'authority_consumed':False,'mutation_performed':False})
 return stable_artifact(body,ELIG_ID,ELIG_PREFIX)
def validate_runtime_adapter_activation_token_eligibility(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=ELIG_SCHEMA,id_key=ELIG_ID,prefix=ELIG_PREFIX,fields=ELIG_FIELDS,status_key='eligibility_status',statuses={'eligible','ineligible','invalid'}); e=list(r.errors)
 if isinstance(v,Mapping) and (v.get('eligible_for_token_preparation') is not (v.get('eligibility_status')=='eligible') or not passive_invariants_valid(v)): e.append('passive_invariant_violation')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_token_eligibility(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_token_eligibility(v); return {'schema':ELIG_SCHEMA,'valid':r.valid,'eligibility_status':v.get('eligibility_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
