from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_eligibility_common import *
from core.engineering.engineering_runtime_adapter_activation_eligibility import validate_runtime_adapter_activation_eligibility
SCHEMA='zero.engineering.runtime_adapter_activation_eligibility_handoff.v1';ID='activation_eligibility_handoff_id';PREFIX='engineering-runtime-adapter-activation-eligibility-handoff-'
FIELDS={'activation_eligibility_id','activation_eligibility_fingerprint','eligibility_status','activation_eligibility_request_id','activation_eligibility_policy_id','activation_constraint_profile_id','activation_eligibility_evaluation_id','preparation_review_handoff_id','preparation_review_handoff_fingerprint','preparation_review_id','preparation_review_closure_id','preparation_id','invocation_descriptor_id','runtime_adapter_admission_id','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','eligible_activation_scope','authority_reference','authority_constraints','eligible_for_activation_authorization','activation_authorized','activation_token_issued','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed'}
def build_runtime_adapter_activation_eligibility_handoff(eligibility:Mapping[str,Any])->dict[str,Any]:
 ok=validate_runtime_adapter_activation_eligibility(eligibility).valid and eligibility.get('eligibility_status')=='eligible'
 return stable_artifact({'schema':SCHEMA,'activation_eligibility_id':eligibility.get('activation_eligibility_id'),'activation_eligibility_fingerprint':eligibility.get('fingerprint'),'eligibility_status':eligibility.get('eligibility_status'),'activation_eligibility_request_id':eligibility.get('activation_eligibility_request_id'),'activation_eligibility_policy_id':eligibility.get('activation_eligibility_policy_id'),'activation_constraint_profile_id':eligibility.get('activation_constraint_profile_id'),'activation_eligibility_evaluation_id':eligibility.get('activation_eligibility_evaluation_id'),'preparation_review_handoff_id':eligibility.get('preparation_review_handoff_id'),'preparation_review_handoff_fingerprint':eligibility.get('preparation_review_handoff_fingerprint'),'preparation_review_id':eligibility.get('preparation_review_id'),'preparation_review_closure_id':eligibility.get('preparation_review_closure_id'),'preparation_id':eligibility.get('preparation_id'),'invocation_descriptor_id':eligibility.get('invocation_descriptor_id'),'runtime_adapter_admission_id':eligibility.get('runtime_adapter_admission_id'),'engineering_runtime_handoff_id':eligibility.get('engineering_runtime_handoff_id'),'execution_session_id':eligibility.get('execution_session_id'),'adapter_id':eligibility.get('adapter_id'),'adapter_version':eligibility.get('adapter_version'),'eligible_activation_scope':eligibility.get('eligible_activation_scope') if ok else {},'authority_reference':eligibility.get('authority_reference'),'authority_constraints':eligibility.get('authority_constraints'),'eligible_for_activation_authorization':ok,'activation_authorized':False,'activation_token_issued':False,'adapter_loaded':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'authority_consumed':False,'mutation_performed':False},ID,PREFIX)
def validate_runtime_adapter_activation_eligibility_handoff(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS); e=list(r.errors)
 if isinstance(v,Mapping):
  if v.get('eligible_for_activation_authorization') is not (v.get('eligibility_status')=='eligible'): e.append('handoff_not_eligible')
  if any(v.get(k) for k in ('activation_authorized','activation_token_issued','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed')): e.append('passive_invariant_violation')
  if not authority_valid(v.get('authority_constraints'),v.get('authority_constraints',{}).get('scope')): e.append('unbounded_authority')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_eligibility_handoff(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_eligibility_handoff(v); return {'schema':SCHEMA,'valid':r.valid,'eligible_for_activation_authorization':v.get('eligible_for_activation_authorization') if isinstance(v,Mapping) else False,'reason_codes':list(r.errors)}
