from __future__ import annotations
from typing import Any
from core.engineering.engineering_mutation_preparation_common import *
def assemble_mutation_package(policy,request,eligibility,decision,approved_scope,approval_verification,prep_policy,prep_request,admission,prepared_operations,proposal,package_sequence=0):
 ops=sorted(seq(prepared_operations),key=lambda x:x.get('sequence_index',0)); rs=[]
 if not ops: rs.append('no_prepared_operations')
 if any(o.get('status')!='prepared' for o in ops): rs.append('prepared_operation_invalid')
 c=counts(ops)
 if c['file_count']>prep_policy.get('maximum_prepared_files',0): rs.append('file_bound_exceeded')
 body={'proposal_id':proposal.get('proposal_id'),'proposal_fingerprint':proposal.get('fingerprint'),'approval_request_id':request.get('request_id'),'eligibility_id':eligibility.get('eligibility_id'),'decision_id':decision.get('decision_id'),'decision_fingerprint':decision.get('fingerprint'),'approved_scope_id':approved_scope.get('approved_scope_id'),'approved_scope_fingerprint':approved_scope.get('fingerprint'),'approval_verification_id':approval_verification.get('approval_verification_id'),'approval_verification_fingerprint':approval_verification.get('fingerprint'),'preparation_policy_id':prep_policy.get('preparation_policy_id'),'preparation_policy_fingerprint':prep_policy.get('fingerprint'),'preparation_request_id':prep_request.get('preparation_request_id'),'preparation_request_fingerprint':prep_request.get('fingerprint'),'preparation_admission_id':admission.get('preparation_admission_id'),'preparation_admission_fingerprint':admission.get('fingerprint'),'workspace_id':proposal.get('workspace_id'),'workspace_root_fingerprint':proposal.get('workspace_evidence',{}).get('workspace_root_fingerprint'),'execution_session_id':proposal.get('execution_session_id'),'ordered_prepared_operations':ops,'content_references':[o.get('content_fingerprint') for o in ops if o.get('content_fingerprint')],'diff_references':[o.get('diff_fingerprint') for o in ops if o.get('diff_fingerprint')],'precondition_references':[o.get('precondition_fingerprint') for o in ops if o.get('precondition_fingerprint')],'scope_constraints':approved_scope.get('approved_scope_prefixes',[]),'authority_constraints':approved_scope.get('approved_authority_constraints',[]),**c,'package_sequence':package_sequence,'package_mode':'preparation_only','mutation_authorized':False,'mutation_performed':False,'filesystem_write_performed':False,'patch_applied':False,'git_invoked':False,'shell_invoked':False,'adapter_invoked':False,'runtime_kernel_invoked':False,'status':'packaged' if not rs else 'not_packaged','reason_codes':reasons(rs)}
 return artifact('mpkg',SCHEMAS['mutation_package'],body,'package_id')
