from __future__ import annotations
from typing import Any, Mapping
from core.engineering.engineering_runtime_adapter_invocation_common import *

SCHEMA='zero.engineering.runtime_adapter_invocation_handoff.v1'; ID_KEY='invocation_handoff_id'; PREFIX='rth-'; FIELDS=set('invocation_result_id invocation_result_fingerprint invocation_verification_id invocation_verification_fingerprint controlled_invocation_id invocation_authorization_id activation_handoff_id adapter_id adapter_version execution_session_id invocation_descriptor_id invocation_scope operation input_bindings expected_output_contract authority_reference authority_constraints eligible_for_concrete_adapter_execution invocation_governance_completed real_execution_authorized real_execution_performed adapter_loaded adapter_code_executed adapter_invoked runtime_invoked authority_consumed mutation_performed'.split())
def build_runtime_adapter_invocation_handoff(result, verification, controlled_invocation):
 r=result if isinstance(result,Mapping) else {}; v=verification if isinstance(verification,Mapping) else {}; c=controlled_invocation if isinstance(controlled_invocation,Mapping) else {}; ok=r.get('result_status')=='invoked' and v.get('verification_status')=='verified' and r.get('governance_transition_committed') is True and r.get('observation_complete') is True and r.get('evidence_complete') is True
 return stable_artifact({'schema':SCHEMA,'invocation_result_id':r.get('invocation_result_id'),'invocation_result_fingerprint':r.get('fingerprint'),'invocation_verification_id':v.get('invocation_verification_id'),'invocation_verification_fingerprint':v.get('fingerprint'),'controlled_invocation_id':r.get('controlled_invocation_id'),'invocation_authorization_id':r.get('invocation_authorization_id'),'activation_handoff_id':r.get('activation_handoff_id'),'adapter_id':r.get('adapter_id'),'adapter_version':r.get('adapter_version'),'execution_session_id':r.get('execution_session_id'),'invocation_descriptor_id':r.get('invocation_descriptor_id'),'invocation_scope':r.get('invoked_scope'),'operation':r.get('operation'),'input_bindings':c.get('input_bindings'),'expected_output_contract':r.get('expected_output_contract'),'authority_reference':c.get('authority_reference'),'authority_constraints':c.get('authority_constraints'),'eligible_for_concrete_adapter_execution':ok,'invocation_governance_completed':ok,'real_execution_authorized':False,'real_execution_performed':False,'adapter_loaded':False,'adapter_code_executed':False,'adapter_invoked':False,'runtime_invoked':False,'authority_consumed':False,'mutation_performed':False},ID_KEY,PREFIX)
def validate_runtime_adapter_invocation_handoff(v):
 r=validate_artifact(v,schema=SCHEMA,id_key=ID_KEY,prefix=PREFIX,fields=FIELDS); extra=validate_common_invocation(v) if isinstance(v,Mapping) else []
 return ValidationResult(r.valid and not extra and v.get('real_execution_authorized') is False, tuple(list(r.errors)+extra))
def inspect_runtime_adapter_invocation_handoff(v):
 r=validate_runtime_adapter_invocation_handoff(v); return inspect_result(r.valid,r.errors)
