from __future__ import annotations
from typing import Any
from core.engineering.engineering_mutation_preparation_common import *
def build_operator_approval_request(payload:dict[str,Any])->dict[str,Any]:
 proposal=payload.get('proposal',{}); handoff=payload.get('approval_handoff',{}); ops=selected_ops(proposal,payload.get('requested_operation_ids') or ids(proposal_ops(proposal),'operation_id'))
 reqids=payload.get('requested_operation_ids') or ids(ops,'operation_id'); rs=[]
 if handoff.get('status')!='handed_off': rs.append('invalid_proposal_handoff')
 if not subset(reqids,ids(proposal_ops(proposal),'operation_id')): rs.append('requested_operation_expansion')
 summaries=[op_summary(proposal,o) for o in ops]
 body={'proposal_id':proposal.get('proposal_id'),'proposal_fingerprint':proposal.get('fingerprint'),'proposal_closure_id':payload.get('closure',{}).get('closure_id'),'proposal_closure_fingerprint':payload.get('closure',{}).get('fingerprint'),'verification_id':payload.get('verification',{}).get('verification_id'),'verification_fingerprint':payload.get('verification',{}).get('fingerprint'),'safety_review_id':payload.get('safety_review',{}).get('safety_review_id'),'safety_review_fingerprint':payload.get('safety_review',{}).get('fingerprint'),'workspace_id':proposal.get('workspace_id'),'workspace_root_fingerprint':handoff.get('workspace_root_fingerprint'),'requested_operation_ids':reqids,'requested_target_path_fingerprints':[x.get('target_path_fingerprint') for x in summaries],'requested_content_fingerprints':[x.get('content_fingerprint') for x in summaries if x.get('content_fingerprint')],'requested_diff_fingerprints':[x.get('diff_fingerprint') for x in summaries if x.get('diff_fingerprint')],'requested_scope':seq(payload.get('requested_scope') or proposal.get('scope_policy',{}).get('allowed_path_prefixes')),'requested_authority_constraints':seq(payload.get('requested_authority_constraints') or proposal.get('authority_constraints')),'request_reason_code':payload.get('request_reason_code'),'operator_identity_class_requirement':payload.get('operator_identity_class_requirement'),'human_decision_required':True,'automated_decision_allowed':False,'mutation_authorized':False,'mutation_performed':False,'status':'requested' if not rs else 'invalid','reason_codes':reasons(rs)}
 return artifact('oar',SCHEMAS['operator_approval_request'],body,'request_id')
