from __future__ import annotations
from typing import Any, Mapping
from core.engineering.engineering_runtime_adapter_invocation_common import *
SCHEMA='zero.engineering.runtime_adapter_invocation_governance_closure.v1'; ID_KEY='invocation_governance_closure_id'; PREFIX='rtclose-'; STATUS_KEY='package_status'; STATUSES={'closed','not_closed','invalid'}
FIELDS=set('intake_request_valid intake_valid intake_status admission_policy_valid admission_valid admission_status preparation_policy_valid preparation_valid preparation_status review_request_valid review_valid review_status authorization_policy_valid authorization_valid authorization_status controlled_invocation_valid invocation_status observation_valid observation_status evidence_valid evidence_status result_valid result_status verification_valid verification_status handoff_valid exact_identity_linkage exact_fingerprint_linkage adapter_binding session_binding descriptor_binding activation_binding scope_binding operation_binding output_contract_binding authority_valid governance_transition_valid observation_complete evidence_complete credential_free_invariant secret_free_invariant no_real_adapter_loading_invariant no_adapter_code_execution_invariant no_real_adapter_invocation_invariant runtime_kernel_invocation_prohibited executor_invocation_prohibited scheduler_invocation_prohibited external_effect_prohibited authority_consumption_prohibited mutation_prohibited package_status reason_codes'.split())
def build_runtime_adapter_invocation_governance_closure(intake_request, intake, admission_policy, admission, preparation_policy, preparation, review_request, review, authorization_policy, authorization, controlled_invocation, observation, evidence, result, verification, handoff):
 vals=[intake_request,intake,admission_policy,admission,preparation_policy,preparation,review_request,review,authorization_policy,authorization,controlled_invocation,observation,evidence,result,verification,handoff]
 ok=all(isinstance(v,Mapping) for v in vals) and intake.get('intake_status')=='accepted' and admission.get('admission_status')=='admitted' and preparation.get('preparation_status')=='prepared' and review.get('review_status')=='approved' and authorization.get('authorization_status')=='authorized' and controlled_invocation.get('invocation_status')=='invoked' and observation.get('observation_status')=='observed' and evidence.get('evidence_status')=='evidenced' and result.get('result_status')=='invoked' and verification.get('verification_status')=='verified' and handoff.get('eligible_for_concrete_adapter_execution') is True
 st='closed' if ok else ('invalid' if not all(isinstance(v,Mapping) for v in vals) else 'not_closed')
 bools={k:ok for k in FIELDS if k.endswith(('_valid','_binding','_linkage','_complete','_invariant')) or k in {'authority_valid','governance_transition_valid'}}
 bools.update({'runtime_kernel_invocation_prohibited':True,'executor_invocation_prohibited':True,'scheduler_invocation_prohibited':True,'external_effect_prohibited':True,'authority_consumption_prohibited':True,'mutation_prohibited':True})
 return stable_artifact({'schema':SCHEMA,**bools,'intake_status':getattr(intake,'get',lambda k,d=None:None)('intake_status'),'admission_status':getattr(admission,'get',lambda k,d=None:None)('admission_status'),'preparation_status':getattr(preparation,'get',lambda k,d=None:None)('preparation_status'),'review_status':getattr(review,'get',lambda k,d=None:None)('review_status'),'authorization_status':getattr(authorization,'get',lambda k,d=None:None)('authorization_status'),'invocation_status':getattr(controlled_invocation,'get',lambda k,d=None:None)('invocation_status'),'observation_status':getattr(observation,'get',lambda k,d=None:None)('observation_status'),'evidence_status':getattr(evidence,'get',lambda k,d=None:None)('evidence_status'),'result_status':getattr(result,'get',lambda k,d=None:None)('result_status'),'verification_status':getattr(verification,'get',lambda k,d=None:None)('verification_status'),'package_status':st,'reason_codes':normalize_reasons([st])},ID_KEY,PREFIX)
def validate_runtime_adapter_invocation_governance_closure(v): return validate_artifact(v,schema=SCHEMA,id_key=ID_KEY,prefix=PREFIX,fields=FIELDS,status_key=STATUS_KEY,statuses=STATUSES)
def inspect_runtime_adapter_invocation_governance_closure(v):
 r=validate_runtime_adapter_invocation_governance_closure(v); return inspect_result(r.valid,r.errors)
