from __future__ import annotations
from typing import Any, Mapping
from core.engineering.engineering_runtime_adapter_invocation_common import *

SCHEMA='zero.engineering.runtime_adapter_invocation_verification.v1'; ID_KEY='invocation_verification_id'; PREFIX='rtver-'; STATUS_KEY='verification_status'; STATUSES={'verified','not_verified','invalid'}
FIELDS=set('invocation_intake_id invocation_admission_id invocation_preparation_id invocation_review_id invocation_authorization_id controlled_invocation_id invocation_observation_id invocation_evidence_id invocation_result_id activation_handoff_id adapter_id adapter_version execution_session_id invocation_descriptor_id verified_scope operation expected_output_contract verification_status reason_codes exact_identity_linkage exact_fingerprint_linkage adapter_binding session_binding descriptor_binding activation_binding scope_binding operation_binding output_contract_binding authority_valid governance_transition_committed observation_complete evidence_complete real_execution_performed adapter_loaded adapter_code_executed adapter_invoked runtime_invoked executor_invoked scheduler_invoked external_effect_performed authority_consumed mutation_performed'.split())
def verify_runtime_adapter_invocation_governance(intake, admission, preparation, review, authorization, controlled_invocation, observation, evidence, result):
 arts=[intake,admission,preparation,review,authorization,controlled_invocation,observation,evidence,result]
 ok=all(isinstance(a,Mapping) for a in arts) and intake.get('intake_status')=='accepted' and admission.get('admission_status')=='admitted' and preparation.get('preparation_status')=='prepared' and review.get('review_status')=='approved' and authorization.get('authorization_status')=='authorized' and controlled_invocation.get('invocation_status')=='invoked' and observation.get('observation_status')=='observed' and evidence.get('evidence_status')=='evidenced' and result.get('result_status')=='invoked' and result.get('real_execution_performed') is False
 st='verified' if ok else ('invalid' if not all(isinstance(a,Mapping) for a in arts) else 'not_verified')
 return stable_artifact({'schema':SCHEMA,'invocation_intake_id':intake.get('invocation_intake_id') if isinstance(intake,Mapping) else None,'invocation_admission_id':admission.get('invocation_admission_id') if isinstance(admission,Mapping) else None,'invocation_preparation_id':preparation.get('invocation_preparation_id') if isinstance(preparation,Mapping) else None,'invocation_review_id':review.get('invocation_review_id') if isinstance(review,Mapping) else None,'invocation_authorization_id':authorization.get('invocation_authorization_id') if isinstance(authorization,Mapping) else None,'controlled_invocation_id':controlled_invocation.get('controlled_invocation_id') if isinstance(controlled_invocation,Mapping) else None,'invocation_observation_id':observation.get('invocation_observation_id') if isinstance(observation,Mapping) else None,'invocation_evidence_id':evidence.get('invocation_evidence_id') if isinstance(evidence,Mapping) else None,'invocation_result_id':result.get('invocation_result_id') if isinstance(result,Mapping) else None,'activation_handoff_id':result.get('activation_handoff_id') if isinstance(result,Mapping) else None,'adapter_id':result.get('adapter_id') if isinstance(result,Mapping) else None,'adapter_version':result.get('adapter_version') if isinstance(result,Mapping) else None,'execution_session_id':result.get('execution_session_id') if isinstance(result,Mapping) else None,'invocation_descriptor_id':result.get('invocation_descriptor_id') if isinstance(result,Mapping) else None,'verified_scope':result.get('invoked_scope') if isinstance(result,Mapping) else None,'operation':result.get('operation') if isinstance(result,Mapping) else None,'expected_output_contract':result.get('expected_output_contract') if isinstance(result,Mapping) else None,'verification_status':st,'reason_codes':normalize_reasons([st]),'exact_identity_linkage':ok,'exact_fingerprint_linkage':ok,'adapter_binding':ok,'session_binding':ok,'descriptor_binding':ok,'activation_binding':ok,'scope_binding':ok,'operation_binding':ok,'output_contract_binding':ok,'authority_valid':ok,'governance_transition_committed':ok,'observation_complete':ok,'evidence_complete':ok,'real_execution_performed':False,'adapter_loaded':False,'adapter_code_executed':False,'adapter_invoked':False,'runtime_invoked':False,'executor_invoked':False,'scheduler_invoked':False,'external_effect_performed':False,'authority_consumed':False,'mutation_performed':False},ID_KEY,PREFIX)
def validate_runtime_adapter_invocation_verification(v):
 r=validate_artifact(v,schema=SCHEMA,id_key=ID_KEY,prefix=PREFIX,fields=FIELDS,status_key=STATUS_KEY,statuses=STATUSES); extra=validate_common_invocation(v) if isinstance(v,Mapping) else []
 return ValidationResult(r.valid and not extra, tuple(list(r.errors)+extra))
def inspect_runtime_adapter_invocation_verification(v):
 r=validate_runtime_adapter_invocation_verification(v); return inspect_result(r.valid,r.errors)
