from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_eligibility_common import *
from core.engineering.engineering_runtime_adapter_activation_eligibility_request import validate_runtime_adapter_activation_eligibility_request
from core.engineering.engineering_runtime_adapter_activation_eligibility_policy import validate_runtime_adapter_activation_eligibility_policy
from core.engineering.engineering_runtime_adapter_activation_constraint_profile import validate_runtime_adapter_activation_constraint_profile
from core.engineering.engineering_runtime_adapter_activation_eligibility_evaluation import validate_runtime_adapter_activation_eligibility_evaluation
from core.engineering.engineering_runtime_adapter_activation_eligibility import validate_runtime_adapter_activation_eligibility
from core.engineering.engineering_runtime_adapter_activation_eligibility_handoff import validate_runtime_adapter_activation_eligibility_handoff
SCHEMA='zero.engineering.runtime_adapter_activation_eligibility_closure.v1';ID='activation_eligibility_closure_id';PREFIX='engineering-runtime-adapter-activation-eligibility-closure-'
FIELDS={'activation_eligibility_request_id','activation_eligibility_policy_id','activation_constraint_profile_id','activation_eligibility_evaluation_id','activation_eligibility_id','activation_eligibility_handoff_id','request_valid','policy_valid','activation_constraint_profile_valid','evaluation_valid','evaluation_status','eligibility_status','handoff_valid','exact_linkage_valid','scope_bound_valid','resource_bound_valid','timeout_bound_valid','environment_valid','authority_valid','passive_only_invariant','activation_authorization_prohibited','activation_token_prohibited','adapter_loading_prohibited','adapter_activation_prohibited','adapter_invocation_prohibited','runtime_invocation_prohibited','executor_invocation_prohibited','scheduler_invocation_prohibited','mutation_prohibited','authority_consumption_prohibited','package_status','reason_codes'}
def build_runtime_adapter_activation_eligibility_closure(request:Mapping[str,Any],policy:Mapping[str,Any],profile:Mapping[str,Any],evaluation:Mapping[str,Any],eligibility:Mapping[str,Any],handoff:Mapping[str,Any])->dict[str,Any]:
 vals={'request_valid':validate_runtime_adapter_activation_eligibility_request(request).valid,'policy_valid':validate_runtime_adapter_activation_eligibility_policy(policy).valid,'activation_constraint_profile_valid':validate_runtime_adapter_activation_constraint_profile(profile).valid,'evaluation_valid':validate_runtime_adapter_activation_eligibility_evaluation(evaluation).valid,'handoff_valid':validate_runtime_adapter_activation_eligibility_handoff(handoff).valid}
 passive=passive_invariants_valid(eligibility) and not any(handoff.get(k) for k in ('activation_authorized','activation_token_issued','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed'))
 closed=all(vals.values()) and validate_runtime_adapter_activation_eligibility(eligibility).valid and passive
 status='closed' if closed else ('invalid' if not vals['request_valid'] or not vals['policy_valid'] else 'not_closed')
 reasons=[]
 for name,ok in vals.items():
  if not ok: reasons.append(name.replace('_valid','_invalid'))
 return stable_artifact({'schema':SCHEMA,'activation_eligibility_request_id':request.get('activation_eligibility_request_id'),'activation_eligibility_policy_id':policy.get('activation_eligibility_policy_id'),'activation_constraint_profile_id':profile.get('activation_constraint_profile_id'),'activation_eligibility_evaluation_id':evaluation.get('activation_eligibility_evaluation_id'),'activation_eligibility_id':eligibility.get('activation_eligibility_id'),'activation_eligibility_handoff_id':handoff.get('activation_eligibility_handoff_id'),**vals,'evaluation_status':evaluation.get('eligibility_status'),'eligibility_status':eligibility.get('eligibility_status'),'exact_linkage_valid':True,'scope_bound_valid':profile.get('scope_valid') is True,'resource_bound_valid':profile.get('resources_valid') is True,'timeout_bound_valid':profile.get('timeout_valid') is True,'environment_valid':profile.get('environment_valid') is True,'authority_valid':profile.get('authority_valid') is True,'passive_only_invariant':passive,'activation_authorization_prohibited':True,'activation_token_prohibited':True,'adapter_loading_prohibited':True,'adapter_activation_prohibited':True,'adapter_invocation_prohibited':True,'runtime_invocation_prohibited':True,'executor_invocation_prohibited':True,'scheduler_invocation_prohibited':True,'mutation_prohibited':True,'authority_consumption_prohibited':True,'package_status':status,'reason_codes':normalize_reasons(reasons+list(eligibility.get('reason_codes',[])))},ID,PREFIX)
def validate_runtime_adapter_activation_eligibility_closure(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='package_status',statuses={'closed','not_closed','invalid'}); return r
def inspect_runtime_adapter_activation_eligibility_closure(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_eligibility_closure(v); return {'schema':SCHEMA,'valid':r.valid,'package_status':v.get('package_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
