from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_token_common import *
from core.engineering.engineering_runtime_adapter_activation_token_authorization import validate_runtime_adapter_activation_token_authorization
SCHEMA='zero.engineering.runtime_adapter_activation_token_issuance.v1';ID='token_issuance_id';PREFIX='engineering-runtime-adapter-activation-token-issuance-';TOKEN_PREFIX='engineering-runtime-adapter-activation-token-'
FIELDS={'token_id','token_authorization_id','token_authorization_fingerprint','token_review_id','token_preparation_id','token_eligibility_id','activation_authorization_handoff_id','activation_authorization_id','adapter_id','adapter_version','execution_session_id','invocation_descriptor_id','issued_scope','max_uses','current_uses','token_constraints','authority_reference','authority_constraints','issuance_status','token_state','passive_only','token_is_secret','bearer_credential','executable','consumed','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed'}
def deterministic_token_id(auth:Mapping[str,Any])->str: return TOKEN_PREFIX+canonical_fingerprint({'token_authorization_id':auth.get('token_authorization_id'),'token_authorization_fingerprint':auth.get('fingerprint'),'activation_authorization_id':auth.get('activation_authorization_id'),'adapter_id':auth.get('adapter_id'),'adapter_version':auth.get('adapter_version'),'scope':auth.get('authorized_token_scope'),'max_uses':auth.get('max_uses')})[:32]
def build_runtime_adapter_activation_token_issuance(authorization:Mapping[str,Any],review_request:Mapping[str,Any]|None=None)->dict[str,Any]:
 av=validate_runtime_adapter_activation_token_authorization(authorization).valid; ok=av and authorization.get('authorization_status')=='authorized' and authorization.get('token_issuance_authorized') is True
 return stable_artifact({'schema':SCHEMA,'token_id':deterministic_token_id(authorization),'token_authorization_id':authorization.get('token_authorization_id'),'token_authorization_fingerprint':authorization.get('fingerprint'),'token_review_id':authorization.get('token_review_id'),'token_preparation_id':authorization.get('token_preparation_id'),'token_eligibility_id':authorization.get('token_eligibility_id'),'activation_authorization_handoff_id':authorization.get('activation_authorization_handoff_id'),'activation_authorization_id':authorization.get('activation_authorization_id'),'adapter_id':authorization.get('adapter_id'),'adapter_version':authorization.get('adapter_version'),'execution_session_id':(review_request or {}).get('execution_session_id'),'invocation_descriptor_id':(review_request or {}).get('invocation_descriptor_id'),'issued_scope':authorization.get('authorized_token_scope') if ok else {},'max_uses':authorization.get('max_uses'),'current_uses':0,'token_constraints':authorization.get('token_constraints'),'authority_reference':authorization.get('authority_reference'),'authority_constraints':authorization.get('authority_constraints'),'issuance_status':'issued' if ok else ('invalid' if not av else 'not_issued'),'token_state':'issued_unconsumed' if ok else 'not_issued','passive_only':True,'token_is_secret':False,'bearer_credential':False,'executable':False,'consumed':False,'adapter_loaded':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'authority_consumed':False,'mutation_performed':False},ID,PREFIX)
def validate_runtime_adapter_activation_token_issuance(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='issuance_status',statuses={'issued','not_issued','invalid'}); e=list(r.errors)
 if isinstance(v,Mapping):
  if v.get('issuance_status')=='issued' and not (v.get('token_state')=='issued_unconsumed' and v.get('max_uses')==1 and v.get('current_uses')==0): e.append('invalid_issuance_bounds')
  if v.get('token_is_secret') is not False or v.get('bearer_credential') is not False or v.get('executable') is not False or v.get('consumed') is not False or not passive_invariants_valid(v): e.append('passive_invariant_violation')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_token_issuance(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_token_issuance(v); return {'schema':SCHEMA,'valid':r.valid,'issuance_status':v.get('issuance_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
