from __future__ import annotations
from typing import Any
from core.engineering.engineering_mutation_preparation_common import *
def build_mutation_handoff(package,package_validation,readiness,token,proposal,decision,approved_scope):
 rs=[]
 if readiness.get('status')!='ready': rs.append('readiness_not_ready')
 if token.get('status')!='issued': rs.append('token_not_issued')
 ops=package.get('ordered_prepared_operations',[])
 body={'mutation_package_id':package.get('package_id'),'mutation_package_fingerprint':package.get('fingerprint'),'package_validation_id':package_validation.get('package_validation_id'),'package_validation_fingerprint':package_validation.get('fingerprint'),'readiness_verification_id':readiness.get('readiness_verification_id'),'readiness_verification_fingerprint':readiness.get('fingerprint'),'preparation_token_id':token.get('token_id'),'preparation_token_fingerprint':token.get('fingerprint'),'proposal_id':proposal.get('proposal_id'),'proposal_fingerprint':proposal.get('fingerprint'),'operator_decision_id':decision.get('decision_id'),'operator_decision_fingerprint':decision.get('fingerprint'),'approved_scope_id':approved_scope.get('approved_scope_id'),'approved_scope_fingerprint':approved_scope.get('fingerprint'),'workspace_id':package.get('workspace_id'),'workspace_root_fingerprint':package.get('workspace_root_fingerprint'),'operation_count':len(ops),'operation_fingerprints':[o.get('original_proposal_operation_fingerprint') for o in ops],'content_fingerprints':package.get('content_references',[]),'diff_fingerprints':package.get('diff_references',[]),'precondition_fingerprints':package.get('precondition_references',[]),'scope_constraints':package.get('scope_constraints',[]),'authority_constraints':package.get('authority_constraints',[]),'token_use_limit':1,'operator_approval_obtained':decision.get('status') in ('approved','partially_approved'),'preparation_completed':not rs,'mutation_authorized':False,'mutation_executor_invoked':False,'mutation_performed':False,'filesystem_write_performed':False,'patch_applied':False,'git_invoked':False,'shell_invoked':False,'runtime_kernel_invoked':False,'token_consumed':False,'status':'handed_off' if not rs else 'not_handed_off','reason_codes':reasons(rs)}
 return artifact('mho',SCHEMAS['mutation_handoff'],body,'handoff_id')
