from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_authorization_common import *
from core.engineering.engineering_runtime_adapter_activation_authorization_request import validate_runtime_adapter_activation_authorization_request
from core.engineering.engineering_runtime_adapter_activation_authorization_policy import validate_runtime_adapter_activation_authorization_policy
from core.engineering.engineering_runtime_adapter_activation_authorization_review import validate_runtime_adapter_activation_authorization_review
SCHEMA='zero.engineering.runtime_adapter_activation_authorization.v1';ID='activation_authorization_id';PREFIX='engineering-runtime-adapter-activation-authorization-'
FIELDS={'activation_authorization_request_id','activation_authorization_request_fingerprint','activation_authorization_policy_id','activation_authorization_policy_fingerprint','activation_authorization_review_id','activation_authorization_review_fingerprint','activation_eligibility_handoff_id','activation_eligibility_handoff_fingerprint','activation_eligibility_id','activation_eligibility_fingerprint','activation_eligibility_closure_id','activation_eligibility_closure_fingerprint','preparation_review_handoff_id','preparation_review_id','preparation_id','invocation_descriptor_id','runtime_adapter_admission_id','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','eligible_activation_scope','authorized_scope','authority_reference','authority_constraints','authorization_status','reason_codes','passive_only','activation_authorized','activation_token_issued','token_material_present','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','executor_invoked','scheduler_invoked','authority_consumed','mutation_performed'}
def build_runtime_adapter_activation_authorization(request:Mapping[str,Any],policy:Mapping[str,Any],review:Mapping[str,Any])->dict[str,Any]:
 valid=validate_runtime_adapter_activation_authorization_request(request).valid and validate_runtime_adapter_activation_authorization_policy(policy).valid and validate_runtime_adapter_activation_authorization_review(review).valid and review.get('review_status')=='approved' and review.get('activation_authorization_request_id')==request.get('activation_authorization_request_id') and review.get('activation_authorization_policy_id')==policy.get('activation_authorization_policy_id')
 status='authorized' if valid else ('invalid' if not validate_runtime_adapter_activation_authorization_review(review).valid else 'not_authorized')
 return stable_artifact({'schema':SCHEMA,'activation_authorization_request_id':request.get('activation_authorization_request_id'),'activation_authorization_request_fingerprint':request.get('fingerprint'),'activation_authorization_policy_id':policy.get('activation_authorization_policy_id'),'activation_authorization_policy_fingerprint':policy.get('fingerprint'),'activation_authorization_review_id':review.get('activation_authorization_review_id'),'activation_authorization_review_fingerprint':review.get('fingerprint'),'activation_eligibility_handoff_id':request.get('activation_eligibility_handoff_id'),'activation_eligibility_handoff_fingerprint':request.get('activation_eligibility_handoff_fingerprint'),'activation_eligibility_id':request.get('activation_eligibility_id'),'activation_eligibility_fingerprint':request.get('activation_eligibility_fingerprint'),'activation_eligibility_closure_id':request.get('activation_eligibility_closure_id'),'activation_eligibility_closure_fingerprint':request.get('activation_eligibility_closure_fingerprint'),'preparation_review_handoff_id':request.get('preparation_review_handoff_id'),'preparation_review_id':request.get('preparation_review_id'),'preparation_id':request.get('preparation_id'),'invocation_descriptor_id':request.get('invocation_descriptor_id'),'runtime_adapter_admission_id':request.get('runtime_adapter_admission_id'),'engineering_runtime_handoff_id':request.get('engineering_runtime_handoff_id'),'execution_session_id':request.get('execution_session_id'),'adapter_id':request.get('adapter_id'),'adapter_version':request.get('adapter_version'),'eligible_activation_scope':request.get('eligible_activation_scope'),'authorized_scope':request.get('requested_authorized_scope') if status=='authorized' else {},'authority_reference':request.get('authority_reference'),'authority_constraints':request.get('authority_constraints'),'authorization_status':status,'reason_codes':normalize_reasons(review.get('reason_codes',[])),'passive_only':True,'activation_authorized':status=='authorized','activation_token_issued':False,'token_material_present':False,'adapter_loaded':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'executor_invoked':False,'scheduler_invoked':False,'authority_consumed':False,'mutation_performed':False},ID,PREFIX)
def validate_runtime_adapter_activation_authorization(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='authorization_status',statuses={'authorized','not_authorized','invalid'}); e=list(r.errors)
 if isinstance(v,Mapping):
  if v.get('activation_authorized') is not (v.get('authorization_status')=='authorized'): e.append('passive_invariant_violation')
  if not passive_invariants_valid(v,authorized_ok=True): e.append('passive_invariant_violation')
  if v.get('authorization_status')=='authorized' and not authority_valid(v.get('authority_constraints'),v.get('eligible_activation_scope')): e.append('unbounded_authority')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_authorization(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_authorization(v); return {'schema':SCHEMA,'valid':r.valid,'authorization_status':v.get('authorization_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
