from __future__ import annotations
from typing import Any,Mapping,Sequence
from core.engineering.engineering_proposal_review_common import ValidationResult,review_artifact,validate_review_artifact
SCHEMA="zero.engineering.engineering_proposal_review.v1";ID_KEY="engineering_proposal_review_id";PREFIX="engineering-proposal-review-";FIELDS={"review_intake","evidence_review","scope_review","dependency_review","validation_review","risk_review_assessment","governance_review","review_findings","review_decision","proposal_closure_linkage","engineering_proposal_linkage","repository_linkage","review_invariants"}
INVARIANTS={"proposal_closure_verified":True,"evidence_reviewed":True,"scope_reviewed":True,"dependencies_reviewed":True,"validation_reviewed":True,"risks_reviewed":True,"governance_reviewed":True,"findings_traceable":True,"no_proposal_mutation":True,"no_patch_generated":True,"no_diff_generated":True,"no_repository_mutation":True,"no_execution_authority":True,"no_mutation_authority":True,"no_approval_authority":True,"no_authorization_authority":True,"deterministic":True,"decision_consistent":True}
def build_engineering_proposal_review(intake:Mapping[str,Any],evidence:Mapping[str,Any],scope:Mapping[str,Any],dependency:Mapping[str,Any],validation:Mapping[str,Any],risk:Mapping[str,Any],governance:Mapping[str,Any],findings:Sequence[Mapping[str,Any]],decision:Mapping[str,Any])->dict[str,Any]:
 p={"review_intake":dict(intake),"evidence_review":dict(evidence),"scope_review":dict(scope),"dependency_review":dict(dependency),"validation_review":dict(validation),"risk_review_assessment":dict(risk),"governance_review":dict(governance),"review_findings":list(findings),"review_decision":dict(decision),"proposal_closure_linkage":{"proposal_closure_id":intake.get("proposal_closure_id"),"proposal_closure_fingerprint":intake.get("proposal_closure_fingerprint")},"engineering_proposal_linkage":{"engineering_proposal_id":intake.get("engineering_proposal_id"),"proposal_verification_id":intake.get("proposal_verification_id")},"repository_linkage":{"repository_identity":intake.get("repository_identity"),"analyzed_revision":intake.get("analyzed_revision")},"review_invariants":dict(INVARIANTS)};return review_artifact(SCHEMA,decision.get("decision","invalid"),p,ID_KEY,PREFIX)
def validate_engineering_proposal_review(v:Any)->ValidationResult:return validate_review_artifact(v,schema=SCHEMA,statuses={"ready_for_approval","changes_requested","blocked","invalid","insufficient_evidence"},id_key=ID_KEY,prefix=PREFIX,fields=FIELDS)
__all__=["INVARIANTS","build_engineering_proposal_review","validate_engineering_proposal_review"]
