from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_proposal import validate_engineering_proposal
from core.engineering.engineering_proposal_common import ValidationResult,proposal_artifact,validate_proposal_artifact
from core.engineering.engineering_proposal_verification import validate_engineering_proposal_verification
SCHEMA="zero.engineering.proposal_closure.v1";ID_KEY="proposal_closure_id";PREFIX="engineering-proposal-closure-";FIELDS={"engineering_proposal_id","engineering_proposal_fingerprint","proposal_verification_id","proposal_verification_fingerprint","planning_closure_id","repository_identity","analyzed_revision","proposal_summary","unresolved_risks","blocked_proposed_changes","governance_boundary_declaration","next_boundary_declaration"}
GOVERNANCE={"approved":False,"authorized":False,"executable":False,"repository_mutation_allowed":False,"executor_allowed":False,"review_gate_required":True}
NEXT={"permitted_destination":"Engineering Proposal Review Foundation or governed review intake boundary","executor":False,"scheduler":False,"mutation_adapter":False,"runtime_activation":False,"deployment":False}
def build_engineering_proposal_closure(proposal:Mapping[str,Any],verification:Mapping[str,Any])->dict[str,Any]:
 valid=validate_engineering_proposal(proposal).valid and validate_engineering_proposal_verification(verification).valid and verification.get("engineering_proposal_id")==proposal.get("engineering_proposal_id");blocking=[x for x in proposal.get("risk_review",[]) if x.get("proposal_blocking")]
 status="closed" if valid and proposal.get("status")=="ready_for_review" and verification.get("status")=="verified" and not blocking else ("blocked" if blocking or verification.get("status")=="blocked" else ("insufficient_evidence" if proposal.get("status")=="insufficient_evidence" else "invalid"))
 intake=proposal.get("proposal_intake",{});changes=proposal.get("proposed_change_set",[]);payload={"engineering_proposal_id":proposal.get("engineering_proposal_id"),"engineering_proposal_fingerprint":proposal.get("fingerprint"),"proposal_verification_id":verification.get("proposal_verification_id"),"proposal_verification_fingerprint":verification.get("fingerprint"),"planning_closure_id":intake.get("planning_closure_id"),"repository_identity":intake.get("repository_identity"),"analyzed_revision":intake.get("analyzed_revision"),"proposal_summary":{"proposed_change_count":len(changes),"validation_count":len(proposal.get("validation_plan",[])),"risk_count":len(proposal.get("risk_review",[])),"ready_for_review":proposal.get("status")=="ready_for_review","approved":False},"unresolved_risks":[x.get("proposal_risk_id") for x in proposal.get("risk_review",[]) if x.get("residual_risk") not in {None,"none"}],"blocked_proposed_changes":proposal.get("dependency_mapping",{}).get("blocked_changes",[]),"governance_boundary_declaration":dict(GOVERNANCE),"next_boundary_declaration":dict(NEXT)}
 return proposal_artifact(SCHEMA,status,payload,ID_KEY,PREFIX)
def validate_engineering_proposal_closure(v:Any)->ValidationResult:return validate_proposal_artifact(v,schema=SCHEMA,statuses={"closed","blocked","invalid","insufficient_evidence"},id_key=ID_KEY,prefix=PREFIX,fields=FIELDS)
build_proposal_closure=build_engineering_proposal_closure
__all__=["GOVERNANCE","NEXT","build_engineering_proposal_closure","build_proposal_closure","validate_engineering_proposal_closure"]
