from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_preparation_common import *
from core.engineering.engineering_runtime_adapter_preparation_request import validate_runtime_adapter_preparation_request
from core.engineering.engineering_runtime_adapter_preparation_eligibility import validate_runtime_adapter_preparation_eligibility
SCHEMA='zero.engineering.runtime_adapter_invocation_descriptor.v1';ID='invocation_descriptor_id';PREFIX='engineering-runtime-adapter-invocation-descriptor-'
FIELDS={'preparation_request_id','preparation_request_fingerprint','preparation_eligibility_id','preparation_eligibility_fingerprint','runtime_adapter_admission_id','runtime_adapter_admission_fingerprint','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','operation','admitted_scope','prepared_scope','input_bindings','expected_output_contract','resource_constraints','environment_constraints','timeout_constraints','authority_reference','authority_constraints','passive_only','executable','adapter_loaded','adapter_invoked','runtime_invoked','executor_invoked','scheduler_invoked','authority_consumed','mutation_performed'}
INV={'passive_only':True,'executable':False,'adapter_loaded':False,'adapter_invoked':False,'runtime_invoked':False,'executor_invoked':False,'scheduler_invoked':False,'authority_consumed':False,'mutation_performed':False}
def build_runtime_adapter_invocation_descriptor(request:Mapping[str,Any],eligibility:Mapping[str,Any],admission:Mapping[str,Any])->dict[str,Any]:
 if not validate_runtime_adapter_preparation_request(request).valid or not validate_runtime_adapter_preparation_eligibility(eligibility).valid or eligibility.get('eligibility_status')!='eligible':
  return stable_artifact({'schema':SCHEMA,'preparation_request_id':request.get('preparation_request_id'),'preparation_request_fingerprint':request.get('fingerprint'),'preparation_eligibility_id':eligibility.get('preparation_eligibility_id'),'preparation_eligibility_fingerprint':eligibility.get('fingerprint'),'runtime_adapter_admission_id':request.get('runtime_adapter_admission_id'),'runtime_adapter_admission_fingerprint':request.get('runtime_adapter_admission_fingerprint'),'engineering_runtime_handoff_id':request.get('engineering_runtime_handoff_id'),'execution_session_id':request.get('execution_session_id'),'adapter_id':request.get('requested_adapter_id'),'adapter_version':request.get('requested_adapter_version'),'operation':{},'admitted_scope':{},'prepared_scope':{},'input_bindings':{},'expected_output_contract':{},'resource_constraints':{},'environment_constraints':{},'timeout_constraints':{},'authority_reference':None,'authority_constraints':{},**INV},ID,PREFIX)
 return stable_artifact({'schema':SCHEMA,'preparation_request_id':request.get('preparation_request_id'),'preparation_request_fingerprint':request.get('fingerprint'),'preparation_eligibility_id':eligibility.get('preparation_eligibility_id'),'preparation_eligibility_fingerprint':eligibility.get('fingerprint'),'runtime_adapter_admission_id':request.get('runtime_adapter_admission_id'),'runtime_adapter_admission_fingerprint':request.get('runtime_adapter_admission_fingerprint'),'engineering_runtime_handoff_id':request.get('engineering_runtime_handoff_id'),'execution_session_id':request.get('execution_session_id'),'adapter_id':request.get('requested_adapter_id'),'adapter_version':request.get('requested_adapter_version'),'operation':request.get('requested_operation'),'admitted_scope':admission.get('admitted_scope'),'prepared_scope':request.get('requested_scope'),'input_bindings':request.get('input_bindings'),'expected_output_contract':request.get('expected_output_contract'),'resource_constraints':request.get('resource_constraints'),'environment_constraints':request.get('environment_constraints'),'timeout_constraints':request.get('timeout_constraints'),'authority_reference':request.get('authority_reference'),'authority_constraints':request.get('authority_constraints'),**INV},ID,PREFIX)
def validate_runtime_adapter_invocation_descriptor(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,statuses=set(),id_key=ID,prefix=PREFIX,fields=FIELDS); e=list(r.errors)
 if isinstance(v,Mapping):
  for k,val in INV.items():
   if v.get(k) is not val: e.append('passive_invariant_violation')
  if not operation_valid(v.get('operation')): e.append('invalid_operation')
  if not scope_bounded(v.get('prepared_scope'),v.get('admitted_scope')): e.append('scope_expansion')
  if not authority_valid(v.get('authority_constraints'),v.get('prepared_scope')): e.append('invalid_authority_constraints')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_invocation_descriptor(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_invocation_descriptor(v); return {'schema':SCHEMA,'valid':r.valid,'reason_codes':list(r.errors)}
