from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_authorization_common import *
SCHEMA='zero.engineering.runtime_adapter_activation_authorization_request.v1';ID='activation_authorization_request_id';PREFIX='engineering-runtime-adapter-activation-authorization-request-'
FIELDS={'activation_eligibility_handoff_id','activation_eligibility_handoff_fingerprint','activation_eligibility_id','activation_eligibility_fingerprint','activation_eligibility_status','activation_eligibility_closure_id','activation_eligibility_closure_fingerprint','activation_eligibility_closure_status','activation_eligibility_request_id','activation_eligibility_policy_id','activation_constraint_profile_id','activation_eligibility_evaluation_id','preparation_review_handoff_id','preparation_review_id','preparation_review_closure_id','preparation_id','invocation_descriptor_id','runtime_adapter_admission_id','engineering_runtime_handoff_id','execution_session_id','adapter_id','adapter_version','eligible_activation_scope','requested_authorized_scope','authorization_constraints','resource_constraints','timeout_constraints','environment_constraints','authority_reference','authority_constraints','authorization_context','request_input_fingerprint'}
def build_runtime_adapter_activation_authorization_request(handoff:Mapping[str,Any],eligibility_closure:Mapping[str,Any],requested_authorized_scope:Any,authorization_constraints:Mapping[str,Any],resource_constraints:Mapping[str,Any],timeout_constraints:Mapping[str,Any],environment_constraints:Mapping[str,Any],authorization_context:Mapping[str,Any])->dict[str,Any]:
 p={'schema':SCHEMA,'activation_eligibility_handoff_id':handoff.get('activation_eligibility_handoff_id'),'activation_eligibility_handoff_fingerprint':handoff.get('fingerprint'),'activation_eligibility_id':handoff.get('activation_eligibility_id'),'activation_eligibility_fingerprint':handoff.get('activation_eligibility_fingerprint'),'activation_eligibility_status':handoff.get('eligibility_status'),'activation_eligibility_closure_id':eligibility_closure.get('activation_eligibility_closure_id'),'activation_eligibility_closure_fingerprint':eligibility_closure.get('fingerprint'),'activation_eligibility_closure_status':eligibility_closure.get('package_status'),'activation_eligibility_request_id':handoff.get('activation_eligibility_request_id'),'activation_eligibility_policy_id':handoff.get('activation_eligibility_policy_id'),'activation_constraint_profile_id':handoff.get('activation_constraint_profile_id'),'activation_eligibility_evaluation_id':handoff.get('activation_eligibility_evaluation_id'),'preparation_review_handoff_id':handoff.get('preparation_review_handoff_id'),'preparation_review_id':handoff.get('preparation_review_id'),'preparation_review_closure_id':handoff.get('preparation_review_closure_id'),'preparation_id':handoff.get('preparation_id'),'invocation_descriptor_id':handoff.get('invocation_descriptor_id'),'runtime_adapter_admission_id':handoff.get('runtime_adapter_admission_id'),'engineering_runtime_handoff_id':handoff.get('engineering_runtime_handoff_id'),'execution_session_id':handoff.get('execution_session_id'),'adapter_id':handoff.get('adapter_id'),'adapter_version':handoff.get('adapter_version'),'eligible_activation_scope':handoff.get('eligible_activation_scope'),'requested_authorized_scope':requested_authorized_scope,'authorization_constraints':dict(authorization_constraints),'resource_constraints':dict(resource_constraints),'timeout_constraints':dict(timeout_constraints),'environment_constraints':dict(environment_constraints),'authority_reference':handoff.get('authority_reference'),'authority_constraints':{**dict(handoff.get('authority_constraints') or {}),'scope':handoff.get('eligible_activation_scope')},'authorization_context':dict(authorization_context),'request_input_fingerprint':canonical_fingerprint({'handoff':handoff,'eligibility_closure':eligibility_closure,'requested_authorized_scope':requested_authorized_scope,'authorization_constraints':authorization_constraints,'resource_constraints':resource_constraints,'timeout_constraints':timeout_constraints,'environment_constraints':environment_constraints,'authorization_context':authorization_context})}
 return stable_artifact(p,ID,PREFIX)
def validate_runtime_adapter_activation_authorization_request(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS); e=list(r.errors)
 if isinstance(v,Mapping):
  if v.get('activation_eligibility_status')!='eligible': e.append('eligibility_not_eligible')
  if v.get('activation_eligibility_closure_status')!='closed': e.append('eligibility_closure_not_closed')
  if contains_wildcard(v.get('requested_authorized_scope')) or contains_wildcard(v.get('eligible_activation_scope')): e.append('wildcard_scope')
  if not scope_bounded(v.get('requested_authorized_scope'),v.get('eligible_activation_scope')): e.append('scope_expansion')
  if not authorization_constraints_valid(v.get('authorization_constraints')): e.append('invalid_authorization_constraints')
  if not resources_valid(v.get('resource_constraints')): e.append('unbounded_resources')
  if not timeout_valid(v.get('timeout_constraints')): e.append('invalid_timeout')
  if not environment_valid(v.get('environment_constraints')): e.append('invalid_environment_constraints')
  if not authority_valid(v.get('authority_constraints'),v.get('eligible_activation_scope')): e.append('unbounded_authority')
  if not passive_mapping(v.get('authorization_context')): e.append('malformed_authorization_context')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_authorization_request(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_authorization_request(v); return {'schema':SCHEMA,'valid':r.valid,'reason_codes':list(r.errors)}
