from __future__ import annotations
from typing import Any,Mapping
from core.engineering.engineering_runtime_adapter_activation_token_common import *
from core.engineering.engineering_runtime_adapter_activation_token_eligibility import validate_runtime_adapter_activation_token_eligibility
from core.engineering.engineering_runtime_adapter_activation_token_preparation import validate_runtime_adapter_activation_token_preparation
from core.engineering.engineering_runtime_adapter_activation_token_review import validate_runtime_adapter_activation_token_review,validate_runtime_adapter_activation_token_review_request
POLICY_SCHEMA='zero.engineering.runtime_adapter_activation_token_authorization_policy.v1';SCHEMA='zero.engineering.runtime_adapter_activation_token_authorization.v1';POLICY_ID='token_authorization_policy_id';ID='token_authorization_id';POLICY_PREFIX='engineering-runtime-adapter-activation-token-authorization-policy-';PREFIX='engineering-runtime-adapter-activation-token-authorization-'
POLICY_FIELDS={'requires_eligible','requires_prepared','requires_approved_review','requires_exact_linkage','requires_bounded_constraints','requires_unconsumed_authority','prohibits_token_material','prohibits_runtime_execution'}
FIELDS={'token_authorization_policy_id','token_authorization_policy_fingerprint','token_review_request_id','token_review_request_fingerprint','token_review_id','token_review_fingerprint','token_preparation_id','token_preparation_fingerprint','token_eligibility_id','token_eligibility_fingerprint','activation_authorization_handoff_id','activation_authorization_id','adapter_id','adapter_version','authorized_token_scope','max_uses','token_constraints','authority_reference','authority_constraints','authorization_status','reason_codes','passive_only','token_issuance_authorized','token_issued','token_consumed','token_material_present','adapter_loaded','adapter_activated','adapter_invoked','runtime_invoked','authority_consumed','mutation_performed'}
def build_default_runtime_adapter_activation_token_authorization_policy()->dict[str,Any]: return stable_artifact({'schema':POLICY_SCHEMA,'requires_eligible':True,'requires_prepared':True,'requires_approved_review':True,'requires_exact_linkage':True,'requires_bounded_constraints':True,'requires_unconsumed_authority':True,'prohibits_token_material':True,'prohibits_runtime_execution':True},POLICY_ID,POLICY_PREFIX)
def validate_runtime_adapter_activation_token_authorization_policy(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=POLICY_SCHEMA,id_key=POLICY_ID,prefix=POLICY_PREFIX,fields=POLICY_FIELDS); e=list(r.errors)
 if isinstance(v,Mapping) and not all(v.get(k) is True for k in POLICY_FIELDS): e.append('invalid_policy')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_token_authorization_policy(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_token_authorization_policy(v); return {'schema':POLICY_SCHEMA,'valid':r.valid,'reason_codes':list(r.errors)}
def build_runtime_adapter_activation_token_authorization(review_request:Mapping[str,Any],review:Mapping[str,Any],preparation:Mapping[str,Any],eligibility:Mapping[str,Any],policy:Mapping[str,Any])->dict[str,Any]:
 rv=validate_runtime_adapter_activation_token_review_request(review_request).valid; dv=validate_runtime_adapter_activation_token_review(review).valid; pv=validate_runtime_adapter_activation_token_preparation(preparation).valid; ev=validate_runtime_adapter_activation_token_eligibility(eligibility).valid; pov=validate_runtime_adapter_activation_token_authorization_policy(policy).valid
 linked=review.get('token_review_request_id')==review_request.get('token_review_request_id') and review.get('token_review_request_fingerprint')==review_request.get('fingerprint') and review_request.get('token_preparation_id')==preparation.get('token_preparation_id') and review_request.get('token_eligibility_id')==eligibility.get('token_eligibility_id')
 ok=rv and dv and pv and ev and pov and linked and review.get('review_status')=='approved' and preparation.get('preparation_status')=='prepared' and eligibility.get('eligibility_status')=='eligible' and authority_valid(review.get('authority_constraints'),review.get('authorized_scope'))
 return stable_artifact({'schema':SCHEMA,'token_authorization_policy_id':policy.get(POLICY_ID),'token_authorization_policy_fingerprint':policy.get('fingerprint'),'token_review_request_id':review_request.get('token_review_request_id'),'token_review_request_fingerprint':review_request.get('fingerprint'),'token_review_id':review.get('token_review_id'),'token_review_fingerprint':review.get('fingerprint'),'token_preparation_id':preparation.get('token_preparation_id'),'token_preparation_fingerprint':preparation.get('fingerprint'),'token_eligibility_id':eligibility.get('token_eligibility_id'),'token_eligibility_fingerprint':eligibility.get('fingerprint'),'activation_authorization_handoff_id':review.get('activation_authorization_handoff_id'),'activation_authorization_id':review.get('activation_authorization_id'),'adapter_id':review.get('adapter_id'),'adapter_version':review.get('adapter_version'),'authorized_token_scope':review.get('requested_token_scope') if ok else {},'max_uses':review.get('max_uses'),'token_constraints':review.get('token_constraints'),'authority_reference':review.get('authority_reference'),'authority_constraints':review.get('authority_constraints'),'authorization_status':'authorized' if ok else ('invalid' if not (rv and dv and pv and ev and pov) else 'not_authorized'),'reason_codes':normalize_reasons([] if ok else ['token_authorization_not_permitted']),'passive_only':True,'token_issuance_authorized':ok,'token_issued':False,'token_consumed':False,'token_material_present':False,'adapter_loaded':False,'adapter_activated':False,'adapter_invoked':False,'runtime_invoked':False,'authority_consumed':False,'mutation_performed':False},ID,PREFIX)
def validate_runtime_adapter_activation_token_authorization(v:Any)->ValidationResult:
 r=validate_artifact(v,schema=SCHEMA,id_key=ID,prefix=PREFIX,fields=FIELDS,status_key='authorization_status',statuses={'authorized','not_authorized','invalid'}); e=list(r.errors)
 if isinstance(v,Mapping) and (v.get('token_issuance_authorized') is not (v.get('authorization_status')=='authorized') or not passive_invariants_valid(v) or v.get('token_issued') is not False or v.get('token_consumed') is not False): e.append('passive_invariant_violation')
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
def inspect_runtime_adapter_activation_token_authorization(v:Any)->dict[str,Any]:
 r=validate_runtime_adapter_activation_token_authorization(v); return {'schema':SCHEMA,'valid':r.valid,'authorization_status':v.get('authorization_status') if isinstance(v,Mapping) else 'invalid','reason_codes':list(r.errors)}
