from __future__ import annotations
from typing import Any
from core.engineering.repository_analysis_common import ValidationResult,artifact,linked,validate_artifact
SCHEMA="zero.engineering.repository_analysis_report.v1";ID_KEY="repository_analysis_report_id";PREFIX="engineering-repository-report-"
def build_repository_analysis_report(request,admission,snapshot,topology,language,build,test,dependency,inventory,evidence):
 sources=[admission,snapshot,topology,language,build,test,dependency,inventory,evidence];partial=any(x.get("status") in {"partial","rejected","invalid"} for x in sources)
 next_stage="analysis_incomplete" if partial else "engineering_planning_pending";status="partial" if partial else "reported"
 ids=[x["evidence_id"] for x in evidence.get("evidence_items",[])]
 payload={**linked(request,"analysis_request","repository_analysis_request_id"),**linked(admission,"root_admission","repository_root_admission_id"),**linked(snapshot,"snapshot","repository_snapshot_id"),**linked(topology,"topology","repository_topology_id"),**linked(language,"language_discovery","repository_language_discovery_id"),**linked(build,"build_discovery","repository_build_discovery_id"),**linked(test,"test_discovery","repository_test_discovery_id"),**linked(dependency,"dependency_analysis","repository_dependency_analysis_id"),**linked(inventory,"engineering_inventory","repository_engineering_inventory_id"),**linked(evidence,"analysis_evidence","repository_analysis_evidence_id"),"repository_summary":{"entry_count":len(snapshot.get("entries",[])),"snapshot_status":snapshot.get("status")},"topology_summary":{"top_level_directory_count":len(topology.get("top_level_directories",[])),"package_root_count":len(topology.get("package_roots",[]))},"language_summary":{"languages":language.get("languages",[]),"primary_candidates":language.get("primary_language_candidates",[])},"build_summary":{"systems":build.get("detected_build_systems",[]),"manifest_count":len(build.get("manifest_paths",[]))},"test_summary":{"test_file_count":test.get("test_file_count",0),"framework_count":len(test.get("framework_evidence",[]))},"dependency_summary":{"view":"static_bounded_dependency_view","edge_count":len(dependency.get("python_import_edges",[]))},"engineering_surface_summary":{k:len(inventory.get(k,[])) for k in ("core_modules","runtime_modules","engineering_modules","cli_modules","test_modules")},"limitations":["bounded_inventory","static_import_analysis_only","no_repository_code_execution"],"warnings":snapshot.get("warnings",[]),"evidence_index":ids,"next_stage":next_stage}
 return artifact(SCHEMA,status,payload,ID_KEY,PREFIX)
def validate_repository_analysis_report(v:Any,evidence:Any=None):
 links={"source_analysis_request_id","source_analysis_request_fingerprint","source_root_admission_id","source_root_admission_fingerprint","source_snapshot_id","source_snapshot_fingerprint","source_topology_id","source_topology_fingerprint","source_language_discovery_id","source_language_discovery_fingerprint","source_build_discovery_id","source_build_discovery_fingerprint","source_test_discovery_id","source_test_discovery_fingerprint","source_dependency_analysis_id","source_dependency_analysis_fingerprint","source_engineering_inventory_id","source_engineering_inventory_fingerprint","source_analysis_evidence_id","source_analysis_evidence_fingerprint"};fields=links|{"repository_summary","topology_summary","language_summary","build_summary","test_summary","dependency_summary","engineering_surface_summary","limitations","warnings","evidence_index","next_stage"};r=validate_artifact(v,schema=SCHEMA,statuses={"reported","partial","invalid"},id_key=ID_KEY,prefix=PREFIX,fields=fields);e=list(r.errors)
 if isinstance(v,dict) and v.get("next_stage") not in {"engineering_planning_pending","needs_clarification","analysis_incomplete"}:e.append("invalid_next_stage")
 if evidence is not None:
  ids={x.get("evidence_id") for x in evidence.get("evidence_items",[])}
  if not set(v.get("evidence_index",[]))<=ids:e.append("unknown_evidence_reference")
 return ValidationResult(not e,tuple(dict.fromkeys(e)))
__all__=["build_repository_analysis_report","validate_repository_analysis_report"]
